### DISCUSSION TITLE
Can't make rtx use system python as default global

### DISCUSSION THREAD

**Discussion by tony-sol** [jdx/mise#1090] [Q&A] [answered]
Can't figure out how to make rtx use system python as default
I've tried like this:

```bash
~/.config ✘ $ python3 --version
Python 3.11.6

~/.config ✔ $ which python3
/Users/tony/.local/share/rtx/shims/python3

~/.config ✔ $ python --version
rtx No version is set for shim: python
Set a global default version with one of the following:
rtx use -g python@3.9.16
rtx Run with RTX_DEBUG=1 for more information

~/.config ✘ $ rtx list
node   16.17.0
node   20.6.0 (outdated) ~/.config/rtx/config.toml latest
python system          ~/.config/rtx/config.toml system
python 3.9.16

~/.config ✔ $ rtx use -g python@system
rtx ~/.config/rtx/config.toml python@system

~/.config ✔ $ python --version
rtx No version is set for shim: python
Set a global default version with one of the following:
rtx use -g python@3.9.16
rtx Run with RTX_DEBUG=1 for more information
```

And here is my config file:
```toml
[tools]
node = "latest"
python = "system"

[settings]
asdf_compat = false
trusted_config_paths = [
	'~/Projects',
]
```

Can't understand what i'm missing
