### DISCUSSION TITLE
@jdx's recommendations: Fish & Starship

### DISCUSSION THREAD

**Discussion by rsyring** [jdx/mise#1550] [General]
I happened across an [older version of the Tips & Tricks page](https://github.com/jdx/mise-docs/commit/4fbf961650ed8db74448d476e1fd246e587184be) that has some recommendations from @jdx regarding his shell tools.  In particular, he recommended:

* [Fish shell](https://fishshell.com/): I'd tried it once before but had some problems and decided to punt.  Given this recommendation, I've picked it up again, spent the day tooling around while watching the football, and believe this will be my new shell.
* [Starship](https://starship.rs/): cross-shell customizable prompt (which mise will install/manage)

And in relatively short order, I have  an amazingly better and more useful cli experience:

![image](https://github.com/jdx/mise/assets/109467/5e6b15de-6c53-4490-a4dd-4c5a42dfe03b)

My Starship config:

```toml
# Notes:
#
# starship print-config > ~/.config/starship-print-config.toml
#
# colors: https://i.stack.imgur.com/KTSQa.png


# format = ' $git_branch$status$cmd_duration$fill$python$all $directory$character'
format = ' $status$cmd_duration${env_var.VENV_NAME}$directory$git_branch$fill$python$all $character'

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "fg:69 bold"

[directory]
# truncate_to_repo = false

[env_var.VENV_NAME]
variable = 'VIRTUAL_ENV_NAME'
format = '[\($env_value\)]($style) '
style = "yellow bold"

[fill]
style = "bold black"
symbol = "#"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_state]
disabled = true

[git_status]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"
version_format = "${raw}"
symbol = "❯ js "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )]($style)'
version_format = "${raw}"
symbol = "❯ py "

[status]
format = "[$symbol$status]($style) "
symbol = "rc "
disabled = false
style = "bold fg:196"
```

And my Fish config: 

```fish
if status is-interactive
    # Commands to run in interactive sessions can go here

    /usr/bin/mise activate fish | source

    ~/.local/share/mise/installs/starship/latest/bin/starship init fish | source
end

# Facilitates showing just the venv name in the prompt.  I wanted that and the Python version in separate places.
function __venv_name_eval --on-event fish_prompt
    if test -n "$VIRTUAL_ENV"
        set --global --export VIRTUAL_ENV_NAME (basename "$VIRTUAL_ENV")
    else
        set --erase VIRTUAL_ENV_NAME
    end
end
```

I plan to check out just a few more tools:

- Directory traversal:  [z](https://github.com/jethrokuan/z) or [zoxide](https://github.com/ajeetdsouza/zoxide)
- [fzf](https://github.com/junegunn/fzf): command line fuzzy finder
- [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish)
- [fisher](https://github.com/jorgebucaran/fisher)

Although, I think one of the benefits of my current setup is that its pretty simple so I'm not planning to rush into anything.

HTH.
