### DISCUSSION TITLE
Continue running tasks after the first exits with non-zero code

### DISCUSSION THREAD

**Discussion by bryanwweber** [jdx/mise#1750] [Q&A] [answered]
I'm using mise tasks defined in TOML to run my linters:
```toml
[tasks]
ruff_check_lint = { description = "Run the ruff linter", run = "ruff check ."}
ruff_format_lint = { run = "ruff format --check .", description = "Run the ruff formatter in check mode"}
markdownlint_lint = {run = "markdownlint-cli2", description = "Run markdownlint"}
lint = { depends = ["ruff_check_lint", "ruff_format_lint", "markdownlint_lint"], description = "Run all the linter tools"}
```
If I run each linter individually, they all find errors. If I run `mise run lint`, it only runs the `ruff_check_lint` task because that exits with error code 1 (since it found errors). How can I configure mise to continue running all the tasks in this case?
