### DISCUSSION TITLE
Any plans for self-bootstrapping to ease onboarding

### DISCUSSION THREAD

**Discussion by prashantv** [jdx/mise#2041] [General]
I've been using mise for my personal projects, which works great. I'd like to use it in projects with other users, but this requires every user has set up mise to take advantage of it. Self-bootstrapping via a script in a bin directory would make onboarding a lot easier, as I can point my build tools to use `bin/<tool>`, and have it automatically set up mise + the tool at the right version if required.

For example, with [hermit](https://github.com/cashapp/hermit), I can install a tool, say terraform, which creates `bin/terraform` that's a shell script that can self-bootstrap hermit + install the appropriate version. 

This is slower (similar to shims), but it avoids explicit onboarding steps and requiring all project users to adopt mise to use the right versions.

**Comment by dudicoco** [comment]
How is this different than creating a shell script to install mise?

**Comment by hverlin** [comment]
There is an issue about it here: https://github.com/jdx/mise/issues/3306

**Comment by syhol** [comment]
I thought I would have a go at creating something like this.

> ## Generate executables in `bin/` for every mise task and tool in a project that auto-installs mise if its missing

First, 3 helper shell scripts in the bin directory

`bin/_mise_manager.sh` (heavily inspired by https://github.com/jdx/mise/issues/3306#issuecomment-2520509606) makes sure mise is installed and returns the path to the executable
```shell
#!/bin/sh
set -eu

find_mise() {
  if command -v mise >/dev/null 2>&1; then
    command -v mise
    return 0
  fi

  if [ -x "$HOME/.local/bin/mise" ]; then
    echo "$HOME/.local/bin/mise"
    return 0
  fi

  return 1
}
export -f find_mise

# Make sure mise is installed
MISE=$(find_mise || true)
if [ -z "${MISE:-}" ]; then
  echo "Mise not installed, installing now"
  curl https://mise.run | sh
fi

# Trust this projects mise.toml
MISE=$(find_mise)
$MISE trust "$(dirname "$(dirname "$0")")/mise.toml" 2>/dev/null
```

`bin/_mise_task_runner.sh`
```shell
#!/bin/sh
set -eu
source "$(dirname "$0")/_mise_manager.sh"
MISE="$(find_mise)"
exec $MISE run "$(basename "$0")" ${@:1}
```

`bin/_mise_tool_runner.sh`
```shell
#!/bin/sh
set -eu
source "$(dirname "$0")/_mise_manager.sh"
MISE="$(find_mise)"
exec $MISE exec -- "$(basename "$0")" ${@:1}
```


And tasks to create symlinks `mise.toml`
```toml
[tasks]
symlink-tasks = 'mise tasks --no-header | cut -d " " -f1 | xargs -n1 -I{} ln -s _mise_task_runner.sh bin/{}'
symlink-tools = 'mise ls --no-header | cut -d " " -f1 | xargs mise bin-paths | xargs -n1 -I{} find {} -type f 2>/dev/null | xargs basename | xargs -n1 -I{} ln -s _mise_tool_runner.sh bin/{}'
terraform-help = "terraform --help"

[tools]
terraform = "latest"
node = "23.3.0"
```

Now run `symlink-tasks` and `symlink-tools`:
```console
❯ mise symlink-tasks
[symlink-tasks] $ mise tasks --no-header | cut -d " " -f1 | xargs -n1 -I{} ln -s _mise_task_runner.sh bin/{}

❯ mise symlink-tools
[symlink-tasks] $ mise ls --no-header | cut -d " " -f1 | xargs mise bin-paths | xargs -n1 -I{} find {} -type f 2>/dev/null | xargs basename | xargs -n1 -I{} ln -s _mise_tool_runner.sh bin/{}
```
This creates symlinks for each task and tool in bin that points to \_mise\_{task|tool}_runner.sh. These can now be run without explicitly installing mise:
```console
❯ bin/terraform-help
[terraform-help] $ terraform --help
Usage: terraform [global options] <subcommand> [args]

The available commands for execution are listed below.
The primary workflow commands are given first, followed by
...

❯ bin/node --version
v23.3.0
```

## Caveats

1. These symlinks won't work outside of the directory containing the mise.toml, I don't think there is a good way around this.
2. The tasks symlink-tasks and symlink-tools will symlink ALL your tasks and tools, not just the ones in this mise.toml.
