### DISCUSSION TITLE
watch task: can it be simplified?

### DISCUSSION THREAD

**Discussion by mustafa0x** [jdx/mise#2338] [Q&A]
In the following config, is there a way to remove `watch_mkdb`? I want to start the server and watch for changes with `mise r`.

```toml
[tasks.mkdb]
run = [
	'rm -f public/db.db',
	'sqlite3 public/db.db < db.sql',
]
sources = ['db.sql']

[tasks.watch_mkdb]
run = 'mise watch -t mkdb'

[tasks.client]
run = 'pnpm dev'

[tasks.dev]
depends = ['watch_mkdb', 'client']
alias = 'default'
```

**Comment by JamBalaya56562** [comment]
Yes — `watch_mkdb` can go. `mise watch` takes multiple tasks with `:::`, the same separator `mise run` uses. Measured on **v2026.8.3** (with `mkdb` and `client` replaced by stand-ins that just echo, so the timings mean nothing — the point is that both ran under one `mise watch`):

```console
$ mise watch mkdb ::: client
[Running: mise run mkdb ::: client]
[mkdb] $ echo "MKDB ran"
[client] $ echo "CLIENT ran"
[mkdb] MKDB ran
[client] CLIENT ran
Finished in 46.6ms
```

So the config collapses to:

```toml
[tasks.mkdb]
run = [
  'rm -f public/db.db',
  'sqlite3 public/db.db < db.sql',
]
sources = ['db.sql']

[tasks.client]
run = 'pnpm dev'

[tasks.dev]
run = 'mise watch mkdb ::: client'
alias = 'default'
```

**One behavioural difference to be aware of**: this watches *both* tasks, so a change re-runs `client` as well, not only `mkdb`. `--on-busy-update` controls what happens to a still-running command — `do-nothing` (the default), `queue`, `restart`, or `signal`. If you specifically want `mkdb` re-run while the dev server keeps running untouched, the wrapper task you already have is still the way to express that.

`mise watch` needs `watchexec` on PATH (`mise use -g watchexec@latest`); it tells you so if it is missing.
