### DISCUSSION TITLE
Have tasks require specific tools

### DISCUSSION THREAD

**Discussion by qbedard** [jdx/mise#2379] [Ideas]
Has there been any consideration toward having a task require one or more tools such that when attempting to run the task, the user would be prompted if the required tool is not installed?

**Comment by JamBalaya56562** [comment]
Good news — this is supported now! 🎉

Tasks can declare the tools they need via a `tools` key. When you run the task, mise will make sure those tools are installed and activated first (and install them if they're missing), scoped to just that task. This was added in **[#3599 `feat: task tools`](https://github.com/jdx/mise/pull/3599)** (merged 2024-12-16).

**TOML tasks** — `mise.toml`:
```toml
[tasks.build]
tools.rust = "1.50.0"
run = "cargo build"

# multiple tools / inline table form also works
[tasks.test]
tools = { node = "20", python = "3.12" }
run = "npm test"
```

**File tasks** — declare them in the `#MISE` header:
```bash
#!/usr/bin/env bash
#MISE tools={rust="1.50.0"}
cargo build
```

When you run `mise run build`, mise resolves and activates `rust@1.50.0` for that task only (it won't leak into dependencies or your ambient toolset). If the version isn't installed yet, it gets installed automatically before the task runs.

A couple of related notes:
- You can skip this auto-install behavior for a single invocation with `mise run --skip-tools <task>`.
- Docs: [Task configuration → `tools`](https://mise.en.dev/tasks/task-configuration.html#tools).

Hope that covers what you were after — feel free to reopen/comment if your use case needs something more (e.g. prompting rather than auto-installing).

*This comment was generated by an AI coding assistant.*
