### DISCUSSION TITLE
Cache in CI

### DISCUSSION THREAD

**Discussion by hverlin** [jdx/mise#2879] [Q&A]
Can you confirm that it is safe to use `mise` the following way in CI?
Looking at the code of the GitHub action (https://github.com/jdx/mise-action), it appears that it's what it's doing?

Here is what I would do on GitLab CI:
```yml
stages:
  - build

build:
  stage: build
  image: some-image-with-mise
  variables:
    MISE_DATA_DIR: .mise/mise-data
    MISE_CACHE_DIR: .mise/mise-cache
  script: |
    mise install
    mise x -c 'pnpm i'
  cache:
    - key:
        prefix: mise
        files: ['mise.toml']
      paths:
        - .mise/mise-cache
        - .mise/mise-data
```

I am happy to make an MR to update this page: https://mise.jdx.dev/continuous-integration.html#continuous-integration
I can add a GitLab CI section at the bottom
