### DISCUSSION TITLE
How to avoid conflicts between `lockfile`/`pin` settings between global and project configs?

### DISCUSSION THREAD

**Discussion by powerman** [jdx/mise#2888] [Q&A] [answered]
If I change some of global settings like `experimental`, `lockfile` and `pin` in `~/.config/mise/config.toml` because I need them for managing global tools, then it looks like I must restore them to default values in `~/.mise.toml` - otherwise some projects may breaks. Is this correct? If yes, then it probably worth mentioning in the docs.

**Comment by jdx** [comment]
> I must restore them to default values in ~/.mise.toml

I don't understand what this means

**Reply by powerman** [reply]
Here is an example:

- `~/.config/mise/config.toml`:
  ```toml
  [settings]
  paranoid = true
  trusted_config_paths = [
    "~/.config/mise/config.toml",
    "~/.mise.toml",
    "~/proj/soft/golangci-lint-strict/",
  ]

  # These settings are for global tools only!
  # WARNING: Restore these settings back to default value in ~/.mise.toml!
  experimental = true # Need to use experimental go backend.
  lockfile = true

  [settings.pipx]
  uvx = true

  [tools]
  ...
  ```

- `~/.mise.toml`:
  ```toml
  # Reset settings modified in ~/.config/mise/ back to defaults, to not affect projects.
  [settings]
  experimental = false
  lockfile = false
  pin = false
  ```
