### DISCUSSION TITLE
Suggestions for auto-updating mise and plugins?

### DISCUSSION THREAD

**Discussion by nickchomey** [jdx/mise#2964] [Q&A]
Any suggestions for auto updating mise and its plugins on a regular basis? Just a cronjob like `echo "0 0 * * * /home/nick/.local/bin/mise self-update -y`?

**Comment by dudicoco** [comment]
With the new `hooks` feature that have been released I was able to implement this:

`.mise.toml`
```toml
[hooks]
[[watch_files]]
patterns = ["update_mise.sh"]
run = "./update_mise.sh"
```

`update_mise.sh`
```sh
#!/usr/bin/env bash

set -euo pipefail

mise_version="2024.11.37"

command_output=$(mise --version 2>/dev/null)

desired_mise_version="${mise_version#v}"

# Extract the version from the output
current_mise_version=$(echo "$command_output" | awk '{print $1}')

if [ "$current_mise_version" != "$desired_mise_version" ]; then
  mise self-update "$mise_version" --no-plugins --yes
fi
```

Bonus - if you would like to auto install tools add the following hook:

```toml
[[watch_files]]
patterns = [".mise.toml"]
run = "mise install"
```
