### DISCUSSION TITLE
Setting PATH to node module cli tool

### DISCUSSION THREAD

**Discussion by dudicoco** [jdx/mise#3330] [Q&A] [answered]
Hi,

I have a hook to install pnpm node modules:
```toml
[[watch_files]]
patterns = ["package.json", "pnpm-lock.yaml"]
run = "pnpm install"
```

This installs a cli tool to local node modules:
`package.json`
```json
{
  "name": "root",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "markdown-cli": "1.6.0"
  }
}
```

The bin path ends up at `./node_modules/.bin/markdown-cli`.
Is there a way to automatically add it to PATH without resorting to writing a script?

**Comment by jdx** [comment, marked as answer]
just add `./node_modules/.bin` to PATH:

```toml
[env]
_.path = ["./node_modules/.bin"]
```
