### DISCUSSION TITLE
Scaling Mise to large organizations with too many tasks

### DISCUSSION THREAD

**Discussion by stevelandeyasana** [jdx/mise#3436] [Ideas]
I work at an organization with its own custom task runner that is the canonical entry point to all our internal tools. Mise can do most things our custom task runner can do, but there are UX problems that would prevent it from scaling.

Today, `mise task ls` gives you a nice 3-column table with Name, Description, and Source. For example...

```
Name          Description       Source
build:mac     Build for Mac     mise.toml
build:windows Build for WIndows mise.toml
```

Now suppose there are 500 tasks, with some nested 3 groups deep, and you joined the company last week so you don't know exactly what something is called.

One way of addressing this would be to add a new command such as `mise task search` which would let you interactively fuzzy-find a task. Does that seem like a reasonable addition to this project, or is Mise not a good fit for this use case?

I'd also love for some way to type a prefix and have Mise show me all the tasks with that prefix. Maybe it can already do this and I missed it.

**Comment by syhol** [comment]
`mise run`
![image](https://github.com/user-attachments/assets/9e64e234-0605-438e-bf44-f295885bacdb)

You can filter it and there is some discussion about adding fuzzy finding.

Also if you have mise shell completions setup, you should be able to use your shells completion system, I use fzf shell integration for fuzzy finding in completions:
![image](https://github.com/user-attachments/assets/30576897-f15b-451f-84aa-37822e60d411)

**Reply by stevelandeyasana** [reply]
It looks like a bare `mise run` doesn't show descriptions, which is unfortunate. And I'd rather not try to make custom shell completion scale to an entire eng org if I can help it. :-)

**Reply by syhol** [reply]
> And I'd rather not try to make custom shell completion scale to an entire eng org if I can help it

I don't blame you.

You could always extend mise with your own `mise search`:

```toml
[tools]
jq = "latest"
fzf = "latest"

[tasks.search]
run = "exec mise run $(mise tasks ls --json | jq '.[] | .name + \" --- \" + .description' --raw-output | fzf | cut -d' ' -f1)"

[tasks.start]
run = "echo starting..."
description = "start all the services"

# ...
```

https://github.com/user-attachments/assets/1cef3449-e4de-431c-a31a-fab754731dbe
