### DISCUSSION TITLE
Is there a way to hide variables from being output in Tasks?

### DISCUSSION THREAD

**Discussion by aclarknexient** [jdx/mise#3524] [Q&A]
I created a simple mise task to test it out:
```
[tasks.tfcmods]
description = "Show the latest versions of TFC modules"
run = """
curl -s --header "Authorization: Bearer {{env.TFC_GROUP_TOKEN_DEV}}" \
  "https://app.terraform.io/api/v2/organizations/REDACTED/registry-modules?page%5Bnumber%5D=1&page%5Bsize%5D=100" \
  | jq -r '.data[].attributes | {name, "version" : ."version-statuses"[0].version} | join(" ")' \
  | column -t \
  | grep REDACTED
"""
```

When ran, the token is displayed in output. Is there a way to not display variable values during tasks?

**Comment by jdx** [comment]
I'm wondering how this could be implemented, here's my first thought:

```toml
[tasks.tfcmods]
description = "Show the latest versions of TFC modules"
run = """
curl -s --header "Authorization: Bearer {{env.TFC_GROUP_TOKEN_DEV | redact}}"
"""
```

but then I thought you probably want to redact it from anything mise outputs so we should have this at a higher level, maybe like this:

```toml
[redactions]
env = ["TFC_GROUP_TOKEN_DEV"]
```
