### DISCUSSION TITLE
Cross-shell aliases

### DISCUSSION THREAD

**Discussion by Ernest0-Production** [jdx/mise#3551] [Ideas]
I would like to be able to specify `aliases` for built-in scripts in the mise configuration, so as not to specify the full path to them or parameters for launching:
```bash
# define
alias myTool='path/to/my_tool.sh --default-option'

# usage 
myTool subcommand <path...> --argument Value --some-option 
```

I know it's possible to create a `mise task`, but calling mise run seems like a longer command, especially when my script can also take many parameter and component arguments:
```bash
mise run myTool subcommand <path...> --argument Value --some-option 
```

If I understand correctly, you can use the `env._.source` directive and specify the path to the script (for example `aliases.sh`) in which all aliases will be declared.

BUT I want to avoid spreading the project settings across several files, and keep everything in one configuration mise:
```toml
# Aliases of bash scripts
[alias.bash] 
myTool='path/to/my_tool.sh --default-option'
# Aliases of ruby scripts
[alias.ruby]
myRubyTool='path/to/stuff.rb'
```

**Comment by jdx** [comment]
I think there would be value in having cross-shell aliases in mise similar to https://github.com/cpendery/kaldo

We would probably want to use the top-level [alias] key in the config, which unfortunately is already used for tools. We could probably still do this but have a migration path for people to move over to [tool_alias] or something similar to that. Or maybe we have [shell_alias] and [tool_alias] to avoid conflicting and support [alias] for backwards compatibility.

**Comment by Ernest0-Production** [comment]
Hi! It may make sense to add the env._.alias directive, since this functionality is close to the path/source directives. 

And thanks for kaldo. I didn't know about the existence of such a tool!)

**Comment by jdx** [comment]
yeah it could go there too

**Comment by egnor** [comment]
(re the OP https://github.com/jdx/mise/issues/2034#issue-2281176873 I think `env._.source` doesn't quite do this, as it only pulls environment variables, not aliases or other shell-internal things. What you'd probably do is use `env._.path` to add a local directory to `$PATH`, and then put little mini scripts in there for each of your commands. this would still involve the more-distributed configuration the OP doesn't like of course)

**Comment by psvmcc** [comment]
It will be great to have such feature!

**Comment by Ryiski** [comment]
I would like to see this happen 🙏

**Comment by betaboon** [comment]
until this is a feature, I'm using this, which is "ugly" but works:
```toml
[env]
_.path = [
  "{{ vars.mise_bin_dir }}",
]

[vars]
mise_bin_dir = "{{ config_root }}/.mise_bin"

[hooks]
enter = "mise run build-mise-bin"

[tasks.build-mise-bin]
hide = true
silent = true
run = """
  rm -rf {{ vars.mise_bin_dir }}
  mkdir -p {{ vars.mise_bin_dir }}
  echo 'bazelisk $@' > {{ vars.mise_bin_dir }}/bazel
  chmod +x {{ vars.mise_bin_dir }}/bazel
"""
```

**Reply by dapicester** [reply]
I wonder if it's possible to make this a plugin.

**Comment by krishnakumarg1984** [comment]
This is exactly what [`aliae`](https://aliae.dev/) does. If `mise` can simply add it as a backend, it would help us to bring our `.aliae`  config files to mise without having to manually port anything.

**Reply by jdx** [reply]
not sure I understand why it would be a backend, if you mean a tool, it can probably be installed with ubi or aqua

**Reply by krishnakumarg1984** [reply]
It is not currently installable through mise. I would like all my favourite CLI tools installed with a single front end i.e. Mise. This is what I meant by backend (sorry for using the term loosely). 

P.S I would also like my pixi global tools to be also installed using Mise so that I will have a single source of truth as a mise toml config that can be put under version control to use across all my machines without admin access.

**Reply by risu729** [reply]
I think you can install it using `mise use ubi:jandedobbeleer/aliae`.

**Reply by krishnakumarg1984** [reply]
Nice. Didn't know that. Thank you!

**Reply by egnor** [reply]
`mise` + `ubi` = ✨ magic ✨

**Reply by krishnakumarg1984** [reply]
I remember reading in the docs about choosing aqua binaries over ubi binaries. Since aliae is not currently available from aqua, ubi is the only backend for this.

**Comment by benjaminwestern** [comment]
+1 to this for me. I would love to see the ability to alias my 'core' tooling from my global mise config so that regardless of shell or machine I retain my 'tf' = 'terraform' alias for example.

**Comment by AndydeCleyre** [comment]
Another workaround I'm surprised hasn't been mentioned is to have alias-setting enter hooks:

```toml
[hooks.enter]
shell = "zsh"
script = "alias dev-run=\"ansible-playbook -i $PWD/inventory/dev --limit=dev_local\""
```

**Reply by Frederick888** [reply]
Clean-up is a bit tricky here. For example, you want an alias `foo` to be different things in different projects.

If you do
```toml
[hooks]
[hooks.enter]
shell = "zsh"
# Project A
script = "alias foo='hello'"
# Project B
script = "alias foo='world'"
[hooks.leave]
shell = "zsh"
script = "unalias foo"
```
It breaks when you `cd` from A to B since B's enter hook runs before A's leave hook, so A's leave hook will unalias B's alias.

I ended up doing something like
```toml
[hooks]
[hooks.enter]
shell = "zsh"
script = """
    mise_alias='A'
    alias foo='hello'
"""
[hooks.leave]
shell = "zsh"
script = """
    if [[ "$mise_alias" == 'A' ]]; then
        unalias foo
        unset mise_alias
    fi
"""
```
Obviously not very scalable but thankfully my use case's not that complex.
