### DISCUSSION TITLE
Is there a key in the tasks that may be used to specify a specific tool version

### DISCUSSION THREAD

**Discussion by reverendpaco** [jdx/mise#3574] [Q&A] [answered]
Let's say I have 3 tasks that I run with different forms of tools that are mise controlled.  In the below example, mise is managing my typst and pandoc binaries.   

But during the individual runs, you can see that I am calling `mise exec --`  with the relevant version 
of the tools before I invoke my shell script (each shell-script has different arguments, etc.)

This works. But I have "Questions/Suggestions" after the code:

```toml
[tools]
pandoc = "3.1.9"
typst = "0.12.0"

[tasks."pdf/latex/pandoc3.6"]
run = "mise exec pandoc@3.6  -- ./bin/to_pandoc3.6_latex_pdf.sh reference_pandoc3.6_latex.pdf"

[tasks."pdf/typst/pandoc3.6"]
run = "mise exec pandoc@3.6 typst@0.12.0 -- ./bin/to_pandoc3.6_typst_pdf.sh reference_pandoc3.6_typst.pdf"

[tasks."pdf/latex/pandoc3.1.9"]
run = "mise exec pandoc@3.1.9 -- ./bin/to_pandoc3.1.9_latex_pdf.sh reference_pandoc3.1.9_latex.pdf"
```

I am wondering though if 

1. there is any mechanism to specify the tool versions as attributes of the tasks themselves so that I don't have to do the `mise exec <version> --` which causes my line to be long and feels a bit weird
2. if there's not, could a solution like this work:

```toml
[tasks."pdf/typst/pandoc3.6"]
use = [ "pandoc@3.6", "typst@0.12.0"]  # this use is only in effect during the task invocation
# run = "mise exec pandoc@3.1.9 typst@0.11.0 -- ./bin/to_pandoc3.6_typst_pdf.sh reference_pandoc3.6_typst.pdf"
run = "./bin/to_pandoc3.6_typst_pdf.sh reference_pandoc3.6_typst.pdf"
```

Apologies if this has already been answered but I can't seem to find the question posed.
