### DISCUSSION TITLE
Request for cookbook contributions

### DISCUSSION THREAD

**Discussion by jdx** [jdx/mise#3645] [Ideas]
I'd like to create a [cookbook](https://mise.jdx.dev/mise-cookbook.html) section for the docs. Show me parts of your mise.toml you think are interesting.

In particular I think tasks, hooks, and env would be really helpful for people to see examples of.

**Comment by hverlin** [comment]
There is already an example for a Node.js project here (https://mise.jdx.dev/templates.html#a-node-js-project). Here is what I usually do with `pnpm`. This ensures that dependencies are installed before running any scripts in the `package.json`.
```toml
[tools]
node = '22'

[tasks.pnpmInstall]
alias = 'pi'
description = 'Installs dependencies with pnpm'
run = 'corepack enable && pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'node --run dev'
depends = ['pnpmInstall']

[tasks.nodeRun]
alias = 'nr'
description = 'Call any script in your package.json file. Example: mise nr lint'
run = 'node --run {{arg(name="script")}}'
depends = ['pnpmInstall']
```

Note that `pnpm run` will support such feature behind a setting in the next release (https://github.com/pnpm/pnpm/issues/8585)

**Comment by syhol** [comment]
presets: https://github.com/jdx/mise/issues/3320#issuecomment-2510282208

**Comment by erickguan** [comment]
For additional context on the "template documentation". I wrote a few to demonstrate templates without readers needed to try in mise.toml.

I would merge them into cookbooks to demonstrate the real world setup.

I would also reduce the template documentation examples when cookbooks have good examples.

**Comment by hverlin** [comment]
Agree that the existing examples could be moved to cookbooks now. We can do a page for each language (example: one page for Node.JS, one for terraform, one for python, etc.)

Also, when seeing `templates` the first time in the sidebar, I thought this was going to be a page showing some example projects using `mise`. I think the page should probably be renamed to something like `Templating` or `Templating mise.toml files`

**Comment by syhol** [comment]
Mise search

https://github.com/jdx/mise/issues/3364#issue-2719788807

```toml
[tasks.search]
run = "mise use --pin $(mise registry -b aqua | fzf --multi | awk '{print $2}')"
```

Might want to adapt it to not be aqua specific

**Comment by hverlin** [comment]
> Mise search

I think it could be implemented internally, like for `mise run`.
 `mise use` without any tools provided could show a (multi) selector.

**Comment by syhol** [comment]
I know skim can be imported as a library and has a very similar feature set to fzf.

**Comment by jdx** [comment]
we don't need no skim, we have [demand](https://github.com/jdx/demand)

**Comment by syhol** [comment]
> we don't need no skim, we have [demand](https://github.com/jdx/demand)

Not sure I trust the author of that library. I hear bad things 👀

**Comment by jdx** [comment]
this is a way to convert from `.tool-versions` to `mise.toml`:

```
cat ~/.tool-versions | tr ' ' '@' | xargs -n2 mise use -g
```

though I'd like this to be a part of `mise config generate`, which maybe should be `mise generate config` to match the other generators

**Comment by syhol** [comment]
I've been using docker to debug issues in a clean environment over the weekend:
```toml
[tasks.docker]
run = "docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest"
```
Puts me in a fresh debian shell with mise installed. I then normally run the following manually:
```console
❯ mise docker
[docker] $ docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest
latest: Pulling from jdxcode/mise
Digest: sha256:eecc479b6259479ffca5a4f9c68dbfe8631ca62dc59aa60c9ab5e4f6e9982701
Status: Image is up to date for jdxcode/mise:latest
root@75f179a190a1:/mise# eval "$(mise activate bash)"
root@75f179a190a1:/mise# echo "" >/mise/config.toml
root@75f179a190a1:/mise# mise prune --yes
mise pruned configuration links
mise python@3.13.1 ✓ remove /mise/cache/python/3.13.1
```
But it might be nice to automate that bit too.

**Comment by joshbode** [comment]
Using `record-query` you can inspect the `__MISE_DIFF` and `__MISE_SESSION` variables to see what's changing in your environment due to the `mise` hook.

```toml
# ~/.config/mise/config.toml
[tools]
"cargo:record-query" = "latest"
```

```zsh
function mise_parse_env {
  rq -m < <(
    zcat -q < <(
      printf $'\x1f\x8b\x08\x00\x00\x00\x00\x00'
      base64 -d <<< "$1"
    )
  )
}
```

```shell
$ mise_parse_env "${__MISE_DIFF}"
{
  "new": {
    ...
  },
  "old": {
    ...
  },
  "path": [
    ...
  ]
}
```

**Comment by syhol** [comment]
Nice one @joshbode! It could also be a great showcase of the new task tools feature that was recently merged, because cargo:record-query can be defined as a task tool.

**Reply by joshbode** [reply]
good idea! I haven't tried that feature yet

**Comment by joshbode** [comment]
Another trick that works with the latest version (required #3640 to make `__MISE_DIFF` more deterministic)

In ZSH to set the prompt colour whenever `mise` updates the environment (e.g. on `cd` into a project, or due to modification of the `.mise*.toml`):

```zsh
# activate mise like normal
source <(command mise activate zsh)

typeset -i _mise_updated

# replace default mise hook
function _mise_hook {
  local diff=${__MISE_DIFF}
  source <(command mise hook-env -s zsh)
  [[ ${diff} == ${__MISE_DIFF} ]]
  _mise_updated=$?
}

_PROMPT="❱ "  # or _PROMPT=${PROMPT} to keep the default

function _prompt {
  if (( ${_mise_updated} )); then
    PROMPT='%F{blue}${_PROMPT}%f'
  else
    PROMPT='%(?.%F{green}${_PROMPT}%f.%F{red}${_PROMPT}%f)'
  fi
}

add-zsh-hook precmd _prompt
```

Now, when `mise` makes any updates to the environment the prompt will go blue :)
There's probably a way to do it without overriding the hook, but I couldn't be bothered figuring out the hook order ;)

**Comment by syhol** [comment]
I've seen a few similar requests around this behaviour: https://github.com/jdx/mise/issues/3808#issuecomment-2561850395

**Comment by jbduncan** [comment]
I think this trimmed-down `mise.toml` from my Go project is useful.

```toml
min_version = "2025.2.5"

[tasks.build]
description = "Build the project"
run = "go build ./..."
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
depends = ["generate"]
alias = "b"

[tasks.check]
description = "Run linters and tests"
depends = ["lint", "test"]
alias = "c"

[tasks.fix]
description = "Fix as many lint errors as possible"
run = "golangci-lint run --fix"
depends = ["build"]
alias = "f"

[tasks.generate]
description = "Run go:generate instructions located in the project's source code"
run = "go generate ./..."
depends = ["go-sanity-check"]
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "g"

[tasks.go-mod-graph]
description = "Generate graph of this project's module dependencies"
run = """
#!/usr/bin/env bash
go mod graph | digraph to dot > module-graph.dot
printf "Install Graphviz https://graphviz.org/, run 'dot -Tsvg -o module-graph.svg module-graph.dot' and open module-graph.svg in your web browser.\n"
"""

[tasks.go-sanity-check]
description = "Run various quick Go-related sanity checks"
hide = true
run = [
  "go mod verify",
  "go mod download",
  "go mod tidy",
  "git diff --exit-code -- go.mod go.sum",
]

[tasks.golangci-lint]
# Edit .golangci.yml to set the linters used
description = "Run golangci-lint"
hide = true
run = "golangci-lint run"
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
# If this task and test run at the same time, force it to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.lint]
description = "Run linters"
hide = true
depends = [
  "go-sanity-check",
  "golangci-lint",
]

[tasks.test]
description = "Run tests"
run = "go test -shuffle=on -race ./..."
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "t"

[tasks.update-versions]
description = "Update tools and dependencies"
run = [
  "mise x -- go get -u -t ./...",
  "mise up"
]
alias = "u"

[tools]
go = "latest"
"go:golang.org/x/tools/cmd/digraph" = "latest"
golangci-lint = "latest"
```

**Reply by jbduncan** [reply]
Also it's possible to write `mise` tasks in Go, but it is quite verbose.

For example, the example above can be expanded to run https://github.com/tailscale/depaware in parallel on all Go packages.

```toml
[tasks.depaware]
hide = true
run = "go run internal/tasks.go depaware"
depends = ["build"]
sources = ["go.mod", "go.sum", "**/*.go", "**/depaware.txt"]
outputs = { auto = true }

[tasks.fix]
description = "Fix as many lint errors as possible"
run = [
  "golangci-lint run --fix",
  "go run internal/tasks.go depaware-fix"
]
depends = ["build"]
alias = "f"

[tasks.lint]
description = "Run linters"
hide = true
depends = [
  "go-sanity-check",
  "golangci-lint",
  "depaware"
]

[tools]
...
"go:github.com/tailscale/depaware" = "latest"
```

<details>
  <summary>internal/tasks.go</summary>

```go
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"golang.org/x/sync/errgroup"
)

func main() {
	doMain := func() error {
		switch os.Args[1] {
		case "depaware":
			return doDepaware()
		case "depaware-fix":
			return doDepawareFix()
		default:
			return fmt.Errorf("invalid command: %s", os.Args[1])
		}
	}

	os.Exit(toExitCode(doMain()))
}

func doDepaware() error {
	depawareFileDirs := make(chan string)
	group, ctx := newErrorGroup()
	group.Go(func() error {
		defer close(depawareFileDirs)
		return filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if !d.Type().IsRegular() {
				return nil
			}
			if filepath.Base(path) != "depaware.txt" {
				return nil
			}

			select {
			case depawareFileDirs <- "./" + filepath.Dir(path):
			case <-ctx.Done():
				return ctx.Err()
			}
			return nil
		})
	})

	for dir := range depawareFileDirs {
		group.Go(func() error {
			fmt.Printf("Linting with depaware concurrently on directory %s...\n", dir)
			return cmd("depaware", "--check", dir).Run()
		})
	}

	return group.Wait()
}

func doDepawareFix() error {
	depawareFiles := make(chan string)
	group, ctx := newErrorGroup()
	group.Go(func() error {
		defer close(depawareFiles)
		return filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if !d.Type().IsRegular() {
				return nil
			}
			if filepath.Base(path) != "depaware.txt" {
				return nil
			}

			select {
			case depawareFiles <- "./" + path:
			case <-ctx.Done():
				return ctx.Err()
			}
			return nil
		})
	})

	for file := range depawareFiles {
		group.Go(func() error {
			dir := "./" + filepath.Dir(file)
			fmt.Printf("Fixing with depaware concurrently on directory %s...\n", dir)
			c := cmd("depaware", dir)
			var b bytes.Buffer
			c.Stdout = &b
			if err := c.Run(); err != nil {
				return err
			}
			return os.WriteFile(file, b.Bytes(), 0o600)
		})
	}

	return group.Wait()
}

func newErrorGroup() (*errgroup.Group, context.Context) {
	group, ctx := errgroup.WithContext(context.Background())
	group.SetLimit(max(1, runtime.NumCPU()-1))
	return group, ctx
}

func cmd(name string, args ...string) *exec.Cmd {
	result := exec.Command(name, args...)
	result.Stdout = os.Stdout
	result.Stderr = os.Stderr
	return result
}

func toExitCode(err error) int {
	if err == nil {
		return 0
	}

	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		_, _ = fmt.Fprintf(os.Stderr, "%v\n", err)
		return exitErr.ExitCode()
	}

	fmt.Printf("%v\n", err)
	return 1
}
```

</details>

**Reply by powerman** [reply]
Mise tasks in Go not necessarily should be that verbose.

Also, there is a way to run them much faster with `gorun` tool:
```toml
[tools]
# gorun: improved `go run`
"go:github.com/erning/gorun" = "latest"
```

I've equivalent implementation of same script in Bash and Go ([hack with GOWORK](https://github.com/erning/gorun/issues/31) is needed to avoid `cd scripts` before `gorun` or have scripts-specific `go.mod` file in repo root):
```toml
[tasks."convert/1.60.3"]
sources = ['1.60.3/reference/.golangci.yml']
outputs = ['1.60.3/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 1.60.3 1.60'
# run = 'scripts/convert.sh 1.60.3 1.60'
```
<details><summary>scripts/convert.sh is 21 lines</summary>

```sh
#!/bin/bash
die() { echo "$@" >&2; exit 1;}

test $# -eq 2 || die "Usage: $0 config-version schema-version"
SOURCE="$1/reference/.golangci.yml"
OUTPUT="$1/.golangci.yml"
SCHEMA="jsonschema/golangci.v$2.jsonschema.json"
test -f "$SOURCE" || die "source file not exists: $SOURCE"
test -f "$SCHEMA" || die "schema file not exists: $SCHEMA"

# Strip non-EOL comments.
yq -P -oy "$SOURCE" | grep -E -v '^\s*#' > "$OUTPUT"
# Strip all invalid empty properties.
DEL_INVALID="$(jv "$SCHEMA" "$OUTPUT" | grep ': got null, want' | sed $'s,.*\'\\(.*\\)\'.*,del(\\1) |,; s,/,.,g')"
yq -i "$DEL_INVALID ." "$OUTPUT"
# Strip all properties with empty object value.
sed -i -e '/: {}$/d' -e '/^\s*$/d' "$OUTPUT"

sed -i -e "1i# Origin: https://github.com/powerman/golangci-lint-strict version $1" "$OUTPUT"

jv "$SCHEMA" "$OUTPUT"
```
</details>

<details><summary>scripts/convert//main.go is 78 lines, but without CLI boilerplate same logic as in Bash is 27 lines</summary>

```go
package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/bitfield/script"
)

func main() {
	ctx := kong.Parse(&cmd{},
		kong.Description("Tool for converting config file to concise version."),
		kong.ShortUsageOnError(),
	)
	ctx.FatalIfErrorf(ctx.Run())
}

type cmd struct {
	Config string `arg:"" help:"config version"`
	Schema string `arg:"" help:"schema version"`
}

func (c cmd) source() string { return c.Config + "/reference/.golangci.yml" }
func (c cmd) output() string { return c.Config + "/.golangci.yml" }
func (c cmd) schema() string { return "jsonschema/golangci.v" + c.Schema + ".jsonschema.json" }

func (c cmd) Validate() error {
	reVersion := regexp.MustCompile(`^[0-9.]+$`)
	errNoSource := script.IfExists(c.source()).Error()
	errNoSchema := script.IfExists(c.schema()).Error()
	switch {
	case !reVersion.MatchString(c.Config):
		return fmt.Errorf("<config>: invalid version %q", c.Config)
	case !reVersion.MatchString(c.Schema):
		return fmt.Errorf("<schema>: invalid version %q", c.Schema)
	case errNoSource != nil:
		return fmt.Errorf("<config>: wrong version %q: %w", c.Config, errNoSource)
	case errNoSchema != nil:
		return fmt.Errorf("<schema>: wrong version %q: %w", c.Schema, errNoSchema)
	}
	return nil
}

func (c cmd) Run() error {
	re := regexp.MustCompile
	header := "# Origin: https://github.com/powerman/golangci-lint-strict version " + c.Config + "\n"
	cmdLineValidate := fmt.Sprintf("jv %s %s", c.schema(), c.output())

	_, err := newPipe(nil).
		Exec(`yq --prettyPrint --output-format yaml ` + c.source()).
		RejectRegexp(re(`^\s*(?:#|$)`)).
		WriteFile(c.output()) // jv can't read from stdin, so we need a file.
	rules, _ := newPipe(err).
		Exec(cmdLineValidate).
		Match(`: got null, want`).
		ReplaceRegexp(re(`.*'(.*)'.*`), `del($1)`).
		Replace(`/`, `.`).
		Slice()
	rule := strings.Join(append(rules, "."), "|")
	lines, err := newPipe(err).
		Exec(fmt.Sprintf(`yq "%s" %s`, rule, c.output())).
		RejectRegexp(re(`^(?:.*: {}|\s*)$`)).
		String()
	_, err = newPipe(err).Echo(header + lines).WriteFile(c.output())
	_, _ = newPipe(err).Exec(cmdLineValidate).Stdout()

	if err != nil {
		_ = os.Remove(c.output())
	}
	return err
}

func newPipe(err error) *script.Pipe {
	return script.NewPipe().WithStderr(os.Stderr).WithError(err)
}
```
</details>

**Comment by calebhearth** [comment]
Whatever tool I use to manage Rubies, I end up trying to re-create RVM's gemsets to allow each app to run in a relatively clean environment, usually with some allowances for sharing certain gems.

This sets up Ruby's `gem(1)` to only load gems from and install gems to a project-local gem directory and adds its `bin` to PATH. It also ensures that the directory exists when entering and installs a gem that's not part of the project's bundle as it's a tool only I'm using.

```toml
[[env]]
GEM_HOME = "{{config_root}}/.gem/ruby/{{exec(command='cat .ruby-version')}}"
GEM_PATH = "{{env.GEM_HOME}}"
[[env]]
_.path = "{{env.GEM_HOME}}/bin"
[hooks]
enter = [
  "[ -d \"$GEM_HOME\" ] || mkdir -p \"$GEM_HOME\"",
  "gem which ruby-lsp > /dev/null 2>&1 || gem install ruby-lsp"
]
```

**Reply by jn64** [reply]
Thanks. I'm only using some tools distributed as gems within a specific (non-Ruby) project, so I don't have Ruby-specific files like `.ruby-version`.

Also, I didn't have to ensure `GEM_HOME` exists. `gem install` creates it.

```toml
# project mise.toml
[tools]
ruby = "3"

[[env]]
GEM_HOME = "{{config_root}}/.gems/{{exec(command='mise tool ruby --active')}}" # .gems/3.4.5
GEM_PATH = "{{env.GEM_HOME}}"
_.path = "{{env.GEM_HOME}}/bin"
```
