### DISCUSSION TITLE
Using eval to export env vars

### DISCUSSION THREAD

**Discussion by dudicoco** [jdx/mise#3653] [Q&A]
I am trying to export env vars using an enter hook:
```toml
[hooks]
enter = "eval $(pixi shell-hook)"
```
However, this does not take effect.

With direnv this does work, and direnv will also unload the env vars on exit.

**Comment by jdx** [comment]
we have `env._.source` for this purpose

**Reply by dudicoco** [reply]
Thanks, just tried it and still got nothing, called a script which contains
```sh
eval "$(pixi shell-hook)"
```

**Reply by dudicoco** [reply]
ok so after some troubleshooting I see that it does export all env vars except for the PATH which is the most important one.
Why doesn't it export the PATH and is there a way around it?

**Reply by syhol** [reply]
Looks like this was fixed here: https://github.com/jdx/mise/issues/3646 if you want to mark this discussion as resolved.

**Reply by dudicoco** [reply]
Thanks, https://github.com/jdx/mise/issues/3646 indeed fixed it.
I'm still having a problem with the flow though, here's the config i've ended up with:
```toml
[env]
_.source = { value = "{{ cwd }}/pixi.sh", tools = true }

[tools]
"ubi:prefix-dev/pixi" = "0.39.2"

[tasks.install-static-packages]
run = "mise install --jobs 2"

[tasks.install-linked-packages]
depends = ["install-static-packages"]
run = "pixi install"

[tasks.all]
depends = [
  "install-static-packages",
  "install-linked-packages",
]

[hooks]
enter = "mise run all"
```

`pixi.sh`
```sh
eval "$(pixi shell-hook --no-install)"
```

The problem is that on a clean install sourcing will fail because `pixi` hasn't been installed yet.
The ideal solution would most likely be to be able to source within the hook itself.
