### DISCUSSION TITLE
Allow passing arguments/options/flags to subtasks

### DISCUSSION THREAD

**Discussion by bartsmykla** [jdx/mise#3760] [Ideas]
### Problem

Mise doesn’t currently support passing dynamic arguments, options, or flags from a main task to its subtasks. This makes it difficult to create workflows where all subtasks share a common argument, like a policy name.

Here are possible approaches to solve this:

#### Inline argument substitution
```toml
["generate:policy"]
depends = [
    "generate:tools:policy-gen",
    "generate:policy:core-resources {{ arg(name='policy-name') }}",
    "generate:policy:other-resources {{ arg(name='policy-name') }}",
]

["generate:policy:core-resources"]
depends = ["generate:tools:policy-gen"]

run = """
echo "Generating core resources for {{ arg(name='policy-name') }}"
"""

["generate:policy:other-resources"]
depends = [
    "generate:tools:policy-gen",
    "generate:policy:core-resources {{ arg(name='policy-name') }}",
]

run = """
echo "Generating other resources for {{ arg(name='policy-name') }}"
"""
```

#### Automatic argument passing
```toml
["generate:policy"]
pass_args_to_depends = true  # Automatically pass arguments to subtasks

depends = ["generate:tools:policy-gen", "generate:policy:core-resources", "generate:policy:other-resources"]

["generate:policy:core-resources"]
depends = ["generate:tools:policy-gen"]

run = """
echo "Generating core resources for {{ arg(name='policy-name') }}"
"""

["generate:policy:other-resources"]
depends = ["generate:tools:policy-gen", "generate:policy:core-resources"]

run = """
echo "Generating other resources for {{ arg(name='policy-name') }}"
"""
```

#### Using environment variables from parent task
```toml
["generate:policy"]
env.POLICY_NAME = "{{ arg(name='policy-name') }}"

depends = ["generate:tools:policy-gen", "generate:policy:core-resources", "generate:policy:other-resources"]

["generate:policy:core-resources"]
depends = ["generate:tools:policy-gen"]

run = """
echo "Generating core resources for {{ env.POLICY_NAME }}"
"""

["generate:policy:other-resources"]
depends = ["generate:tools:policy-gen", "generate:policy:core-resources"]

run = """
echo "Generating other resources for {{ env.POLICY_NAME }}"
"""
```

### Expected Behavior

When running:
```bash
mise run generate:policy circuit-breaker
```

All subtasks should receive the `circuit-breaker` argument. Expected output:
```plaintext
Generating core resources for circuit-breaker
Generating other resources for circuit-breaker
```

### Benefits

- Makes workflows easier by reducing repeated code when subtasks use the same arguments  
- Lets you pass arguments dynamically to adjust subtask behavior  
- Keeps tasks cleaner and simpler to manage

**Comment by jdx** [comment]
I don't think this is necessary. You can just set an environment variable like this:

```toml
[tasks."generate:policy"]
run = "POLICY_NAME=circuit-breaker mise run generate:tools:policy-gen ::: generate:policy:core-resources ::: generate:policy:other-resources"
```
