### DISCUSSION TITLE
method for running tasks in series

### DISCUSSION THREAD

**Discussion by jdx** [jdx/mise#3761] [Ideas]
I've been trying to avoid having the capability of defining task dependencies in series as an explicit feature just to keep things simple since it's trivially done just by calling `mise run` inside of a task:

```toml
[tasks.build]
run = ['mise run a', 'mise run b', 'mise run c']
```

however, because of several reasons (which I can explain if people are curious but I don't think it matters all that much), this just isn't good enough. I think we may need a way to explicitly define dependencies should run in series. I think users will like this because `mise run` I've often thought users see as a bit of a kluge even though it works fine. How do you think this could look in `mise.toml`? I think I only have terrible ideas:

```toml
[tasks.build]
depends_series = ['a', 'b', 'c']
```

```toml
[tasks.build]
depends = ['a', '+', 'b', '+', 'c']
```

I'm not 100% sure I would actually implement this. The drawbacks of not having this are not things we can't live with. Part of the issue is coming up with good syntax but the other is the complexity in the codebase this would add (which I'm not too sure about right now). Also the complexity of just having more features to document and explain to people how to use is a cost I'm weighing. Still, good syntax is definitely a blocker for starting it.

**Comment by EricDriussi** [comment]
Personally, I don't really have a use case for explicitly running tasks in series.
What I would say is that using `mise run` seems in general counter intuitive, since there is specific syntax to handle deps. Plus, it gets messy when tasks get more complex.

A fair example of this is, with all respect, this very project's `tasks.toml`, IMO.
I was trying to understand the docker setup and got lost at the second `mise run`. Maybe I'm just grug brained but I'm guessing more people also are.

Regarding semantics, I would expect this feature to exist for `depends_post` as well, so having a `depends_series` would maybe also introduce `depends_post_series`, for a total of 4 properties to handle dependencies.
Maybe an [inline table](https://toml.io/en/v1.0.0#inline-table) is in order at that point? Something like:

```toml
depends = { pre = { sync = ["a"], async = ["b"] }, post = { sync = ["c"], async = ["d"] } }
``` 

Or maybe a mix of full and inline tables?

```toml
[tasks.build.depends]
pre = { sync = ["a"], async = ["b"] }
post = { sync = ["c"], async = ["d"] }
``` 

Breaking changes suck but the old syntax could be preserved quietly for current users, while documenting the new one for new ones.
Just some thoughts!

**Reply by vic1707** [reply]
\+ 1 on `pre`/`post` keys

**Comment by justbispo** [comment]
I've got to this discussion post a couple of times before. I've tried a few times to have task dependencies running in series, mainly because I find it annoying to have the output of the task have the dependencies outputs intertwined:
```console
> mise lint
[format-check] $ typstyle --diff .
[lint] $ biome lint
[format-check] $ tombi format --diff --check
[lint] Checked 8 files in 1687µs. No fixes applied.
[lint] $ tombi lint
[format-check] 6 files did not need formatting
[format-check] $ biome check
[lint] 6 files linted successfully
[lint] Finished in 51.7ms
[format-check] Checked 8 files in 1975µs. No fixes applied.
[format-check] Finished in 63.4ms
```
(I would actually not mind them being in parallel in this case, if the output of each dependency was all together (tho it wouldn't represent the reality, it would seem from the output that they were executed in series))
Indeed it's not that important since there's an alternative way to get this behavior and the number of cases where it's absolutely important to have it is small.

I had an idea which should not change the syntax. Since mise already has [`jobs`](https://mise.jdx.dev/configuration/settings.html#jobs), `jobs.depends` and `jobs.depends_post` could be created and would only apply to those properties. Like `jobs`, `1` would force the dependencies to run in series and above `1` they would run concurrently.
A `jobs.run` could also be created since, if I'm not mistaken, there's no way to make the commands run in parallel.
BTW, I tried to use `env = { MISE_JOBS = 1 }` and `env.MISE_JOBS = 1` inside the task but it didn't work, only the global setting and env var worked. So, the new settings could also be available globally or per task.

**Reply by justbispo** [reply]
I came back to this post and noticed that maybe my possible solution wasn't very clear. Here's an example:
```toml
[settings]
jobs.depends = 1  # run in series
jobs.depends_post = 5  # run concurrently
# And potentially...
jobs.run = 2

[tasks.example]
depends = ["depends1", "depends2", "depends3", "depends4"]
run = "echo 'Running example'"
depends_post = ["depends_post1", "depends_post2", "depends_post3", "depends_post4"]

[tasks.depends1]
run = "echo 'Running depends1'"

[tasks.depends2]
run = "echo 'Running depends2'"

[tasks.depends3]
run = "echo 'Running depends3'"

[tasks.depends4]
run = "echo 'Running depends4'"

[tasks.depends_post1]
run = "echo 'Running depends_post1'"

[tasks.depends_post2]
run = "echo 'Running depends_post2'"

[tasks.depends_post3]
run = "echo 'Running depends_post3'"

[tasks.depends_post4]
run = "echo 'Running depends_post4'"
```

The syntax would be the same, you'd only need to add 2 new settings options. The drawback is, if I create a new task with dependencies, I couldn't say that for this task the dependencies should run in a specific mode.

You could add new properties for tasks to solve this, something like:

```toml
[tasks.example1]
jobs.depends = 1
jobs.depends_post = 5
depends = ["depends1", "depends2", "depends3", "depends4"]
run = "echo 'Running example1'"
depends_post = ["depends_post1", "depends_post2", "depends_post3", "depends_post4"]

[tasks.example2]
jobs.depends = 5
jobs.depends_post = 1
depends = ["depends1", "depends2", "depends3", "depends4"]
run = "echo 'Running example2'"
depends_post = ["depends_post1", "depends_post2", "depends_post3", "depends_post4"]
```

Or even simplify and use inline table for both the global and task property:

```toml
[settings]
jobs = { depends = 1, run = 2, depends_post = 5 }

[tasks.example]
jobs = { depends = 5, run = 1, depends_post = 1 }
depends = ["depends1", "depends2", "depends3", "depends4"]
run = ["echo 'Running first run'", "echo 'Running second run'"]
depends_post = ["depends_post1", "depends_post2", "depends_post3", "depends_post4"]
```
