### DISCUSSION TITLE
tools separation

### DISCUSSION THREAD

**Discussion by rafaScalet** [jdx/mise#3819] [Q&A]
i think it would be pretty cool, if as in Node.JS, we had the separations of "dependencies":

```toml
[tools]
node = "lts"
pnpm = "latest"

[tools.dev]
lazygit = "latest"
github-cli = "latest"
httpie-go = "latest"
```

not like in the `mise.local.toml` , this tools can be in git, leaving the entire development environment ready and the production without useless tools

**Comment by syhol** [comment]
You can use Config Environments for this: https://mise.jdx.dev/configuration/environments.html

`mise.toml`
```toml
[tools]
node = "lts"
pnpm = "latest"
```

`mise.dev.toml`
```toml
[tools]
lazygit = "latest"
github-cli = "latest"
httpie-go = "latest"
```

And make sure your devs have MISE_ENV=dev

---

If you want the dev tools to be included by default you can flip it with disable_tools:

`mise.toml`
```toml
[tools]
node = "lts"
pnpm = "latest"
# You can add a comment here if you like to help separate the tools
lazygit = "latest"
github-cli = "latest"
httpie-go = "latest"
```

`mise.production.toml`
```toml
[settings]
disable_tools = [
  "lazygit",
  "github-cli",
  "httpie-go",
]
```

And make sure your prod has MISE_ENV=production
