### DISCUSSION TITLE
Support forwarding all args to tasks that use `{{option}}`

### DISCUSSION THREAD

**Discussion by orf** [jdx/mise#3863] [Ideas]
It's handy to support forwarding all arguments to a task, even if it uses `option()`. For example:

```toml
[tasks.cross-build]
run = 'echo cross build --target={{option(name="target")}} --locked'
```

I'd like to be able to run `mise run cross-build --target=foo --release`, and have it forward `--release` to the task.

In this simple case I could forward everything, but what if I wanted to do something specific with the flag before? It now becomes impossible:

```toml
[tasks.cross-build]
run = """
if [ '{{option(name="target")}}' = 'some-specific-thing' ]; then
  echo 'doing something specific'
fi
echo cross build --target={{option(name="target")}} --locked
"""
```
