### DISCUSSION TITLE
Unset env var for specific tasks

### DISCUSSION THREAD

**Discussion by psvmcc** [jdx/mise#3916] [General]
Hi, is it possible to unset specific env var for task? I have config like
```
[env]
MY_VAR_MISE = '1234'

[tasks.test]
env.MY_VAR_MISE = false
env.MY_VAR_SHELL = false
run = [
    "env|grep MY_VAR"
]
```

and when I doing:
```
$ export MY_VAR_SHELL=qwerty
$ mise run test
[test] $ env|grep MY_VAR
MY_VAR_MISE=1234
MY_VAR_SHELL=qwerty
```

or maybe I'm doing something wrong?

**Comment by syhol** [comment]
I don't think its possible today, but you can set them to an empty string:
```toml
[env]
MY_VAR_MISE = '1234'

[tasks.test]
env.MY_VAR_MISE =""
env.MY_VAR_SHELL = ""
run = [
    "env|grep MY_VAR"
]
```

```console
❯ mise run test
[test] $ env|grep MY_VAR
MY_VAR_MISE=
MY_VAR_SHELL=
```

Many (but not all) programs check that an env var is not empty rather than not set, so this is normally good enough
