### DISCUSSION TITLE
How to set `tera` variables?

### DISCUSSION THREAD

**Discussion by sermuns** [jdx/mise#3922] [Troubleshooting and bug reports] [answered]
First of all, this is an amazing tool!

I am trying to using templating in my `mise.toml` so as to not have to repeat myself. A simple use case would be to define the build dir, and reuse it in all relevant commands.

How can we use the `set` statement from tera ? 

I got this to work, but this seems like a verbose and roundabout way to accomplish what i want:

```toml
[env]
OUTPUT_DIR = 'build'

[tasks.build]
run = "gogio --target js -o {{ get_env(name='OUTPUT_DIR') }} ."
sources = ['main.go']
outputs = ["{{ get_env(name='OUTPUT_DIR') ~ '/*' }}"]

[tasks.clean]
run = "rm -rf {{ get_env(name='OUTPUT_DIR') }}"
```

**Comment by sermuns** [comment]
I was completely focused on tera templating and forgot that the `[env]` block actually set environment variables. 

This config is a little slimmer:

```toml
[env]
OUTPUT_DIR = 'build'

[tasks.build]
run = "gogio --target js -o $OUTPUT_DIR ."
sources = ['main.go']
outputs = ["{{ get_env(name='OUTPUT_DIR') ~ '/*' }}"]

[tasks.clean]
run = "rm -rf $OUTPUT_DIR"
```

**Reply by hverlin** [reply, marked as answer]
You can use `vars` also: https://mise.jdx.dev/tasks/task-configuration.html#vars

**Reply by sermuns** [reply]
Exactly what I was looking for! Thank you!

**Reply by sermuns** [reply]
For reference: this is my working config now:

```toml
[vars]
output_dir = 'build'

[tasks.build]
run = "gogio --target js -o {{ vars.output_dir }} ."
sources = ['main.go']
outputs = ["{{ vars.output_dir ~ '/*' }}"]

[tasks.clean]
run = "rm -rf {{ vars.output_dir }}"
```
