### DISCUSSION TITLE
mise should not default to use `uv` for creating virtual environments

### DISCUSSION THREAD

**Discussion by tyilo** [jdx/mise#3964] [Troubleshooting and bug reports] [answered]
`uv venv` creates a virtual environment without a `pip` binary inside it.
Thus it is not possible to use `pip install ...` inside the virtual environment and so it seems weird to use `uv` for creating virtual environments as the default.

**Comment by tyilo** [comment]
Alternatively `mise` could use `uv venv --seed`

**Reply by jdx** [reply]
I believe you can do this with https://mise.jdx.dev/lang/python.html#python.uv_venv_create_args

**Reply by hverlin** [reply]
Maybe we need to document it in the python cookbook, as it might be straightforward to find in the `uv` docs
```toml
[tools]
python = 'latest'

[env]
_.python.venv = { path = "venv", create = true }

[settings]
python.uv_venv_create_args = ['--seed']
```
