### DISCUSSION TITLE
Dynamic sources for tasks

### DISCUSSION THREAD

**Discussion by iilyak** [jdx/mise#3970] [Q&A]
I would like to be able to lint only files which are under version control. Currently I use Makefile as a task runner and considering switching over to mise. Here is what I do currently

```Makefile
ERLFMT?=erlfmt
ERL_SRCS?=$(shell git ls-files -- "*/rebar.config" "*.erl" "*.hrl" "*.app.src" "*.escript")

.PHONY: check-fmt
# target: check-fmt - Check mis-formatted code
check-fmt:
	@$(ERLFMT) --verbose --check -- $(ERL_SRCS) | tee artifacts/erlfmt.log
```

I wanted to replace it with 

```
[tasks.lint-erlfmt]
sources = ["**/rebar.config", "**/*.erl", "**/*.hrl", "**/*.app.src", "**/*.escript"]
run = erlfmt -verbose --check -- $(sources)
```

But this would run linter against experimental files in the repo.

I've considered

```toml
[tasks.lint-erlfmt]
run = """
#!/usr/bin/env bash
ERL_SRCS=$(git ls-files -- "*/rebar.config" "*.erl" "*.hrl" "*.app.src" "*.escript")
erlfmt -verbose --check -- $(ERL_SRCS)
"""
```

However version with run script wouldn't integrate with `watch` as well.

Maybe I can use the `exec` in the template somehow. However this wouldn't integrate with `watch` either. Also I am not sure at what point in time the erl_sources would be evaluated and whether it would be cached or not.

```
[vars]
erl_sources = "{{ exec(command='git ls-files -- "*/rebar.config" "*.erl" "*.hrl" "*.app.src" "*.escript"') }}"

[tasks.lint-erlfmt]
run = "erlfmt -verbose --check -- {{vars.erl-sources}}"
```
