### DISCUSSION TITLE
Ubi support of GitLab

### DISCUSSION THREAD

**Discussion by q-b** [jdx/mise#4020] [Ideas]
Hi,

We would like to see `mise` support for GitLab as a forge. It has been added to `ubi` [v0.3.0](https://github.com/houseabsolute/ubi/releases/tag/v0.3.0) which is the version currently included in `mise`.

Our use case would be to retrieve some softwares from a private self-hosted repository (*not* gitlab dot com).

Thank you for help.

**Comment by efussi** [comment]
I think this entails two things:
- support `ubi`'s `--api-base-url` parameter to point to a self-hosted github / gitlab
- a means to supply a token for that self-hosted forge different from the one used for `github.com`

**Comment by efussi** [comment]
@q-b Is my understanding correct? The enhancement suggestion is to expose `ubi`'s [support for GitHub Enterprise / GitLab for Enterprise](https://github.com/houseabsolute/ubi#using-ubi-with-github-enterprise-or-gitlab-for-enterprise). Something like this:
```toml
[tools]
slsa-verifier = "latest"
"ubi:asquad/cool-tool" = { version = "latest", forge = "gitlab", api_base_url = "https://gitlab.acme.com/api/v2", token = "ACME_GITLAB_TOKEN" }
```

Still use `$GITHUB_TOKEN` for public GItHub access, but `$ACME_GITLAB_TOKEN` for access to the self-hosted GitLab.
