### DISCUSSION TITLE
Bug: pipx/uv extra index url not used

### DISCUSSION THREAD

**Discussion by Finkregh** [jdx/mise#4084] [Troubleshooting and bug reports]
I'd like to install a cli tool from a local python registry/index:

```toml
# config.toml

[tools."pipx:commandname"]
version = "latest"
extras = "full"
uvx_args = '--index=https://internal/artifactory/api/pypi/bar/simple --from actual-package-name'
```

I have also tried to set `UV_INDEX` and `PIP_EXTRA_INDEX_URL`, I always get this error:

```text
mise ERROR [~/.config/mise/config.toml] pipx:commandname@latest: HTTP status client error (404 Not Found) for url (https://pypi.org/pypi/actual-package-name/json)
```

When setting `UV_INDEX` I can use `uvx --from actual-package-name commandname` w/o error.

**Comment by jdx** [comment]
it's probably not a bug, it's happening because listing versions doesn't use `uvx_args`. I assume if you specify a full version it will work. We will either need `index` (or something) as a new option which would handle this.

Code is here: https://github.com/jdx/mise/blob/033aa149e8b7a45ea750c09c31438709420214c8/src/backend/pipx.rs#L50-L60

**Reply by Finkregh** [reply]
If I use a specific version, I still get the same error (just with the specific version):

```toml
[tools."pipx:commandname"]
version = "6.0.8"
extras = "full"
uvx_args = '--index=https://internal/artifactory/api/pypi/bar/simple --from actual-package-name'
```

```text
mise ERROR [~/.config/mise/config.toml] pipx:commandname@6.0.8: HTTP status client error (404 Not Found) for url (https://pypi.org/pypi/commandname/json)
```

And I just saw that I did not replace the names properly in the initial post. It tries to look at `/pypy/commandname/json` instead of the value from `--from`.
Is the config from the initial post correct, if the package is named `actual-package-name` and provides an executable `commandname`?
