### DISCUSSION TITLE
Using `vars` in `[env]` templates does not work

### DISCUSSION THREAD

**Discussion by hverlin** [jdx/mise#4099] [Troubleshooting and bug reports]
The following configuration does not work

```toml
[vars]
my_var = 'something'

[env]
SOME_ENV_VAR = '{{vars.my_var}}'
```

Output:
```
mise ERROR failed to parse template: '{{vars.my_var}}'  
```
