### DISCUSSION TITLE
How to remove/override a hook using `mise.local.toml`?

### DISCUSSION THREAD

**Discussion by hverlin** [jdx/mise#4139] [Troubleshooting and bug reports]
If I have the following setup, it appears that it will merge the `postinstall` hooks:

`mise.toml`
```toml
[hooks]
postinstall = 'echo mise.toml'
````

`mise.local.toml`
```toml
[hooks]
postinstall = 'echo mise.local.toml'
````

```sh 
root@38603606ed29:~/prj# mise i
mise all runtimes are installed
mise.local.toml
mise.toml
```

How can I opt out of a `postinstall` hook?  (without relying on environment variables/templating to skip it)
