### DISCUSSION TITLE
Dynamically set `sops.age_key`

### DISCUSSION THREAD

**Discussion by srnnkls** [jdx/mise#4165] [Q&A]
I have my private age key stored in 1password (but it could also live somewhere else). Now, I want to set the `sops.age_key` or `MISE_SOPS_AGE_KEY` dynamically like so:

```toml
# mise.toml

[env]
# second thing I tried
MISE_SOPS_AGE_KEY = "{{ exec(command='op read op://Employee/mise-demo/age_key', cache_key='age_key', cache_duration = '10s') }}"
_.file = ".env.yaml"

[tools]
age = "latest"
sops = "latest"

[settings]
# first thing I tried
sops.age_key = "{{ exec(command='op read op://Employee/mise-demo/age_key', cache_key='age_key', cache_duration = '10s') }}"
experimental = true
```

It seems that tera templates are not evaluated for `sops` settings? (Recursively) setting `MISE_SOPS_AGE_KEY` within mise's own env seems to come too late, though.
