### DISCUSSION TITLE
Pass tool directory and version as environment variable into postinstall hook

### DISCUSSION THREAD

**Discussion by iilyak** [jdx/mise#4189] [Ideas]
I am trying to write an aqua registry.yaml for https://github.com/spotbugs/spotbugs. The release of spotbugs doesn't have an executable flag set. So I am trying to use the posthook to set it.

```toml
[tools]
"aqua:iilyak/spotbugs/spotbugs" = { version = '4.9.0', postinstall = """\
    chmod +x bin/spotbugs
"""}
```

```yaml
❯ cat /Users/iilyak/Library/Caches/mise/aqua-registry/pkgs/iilyak/spotbugs/spotbugs/registry.yaml
packages:
  - name: spotbugs/spotbugs
    type: github_release
    repo_owner: spotbugs
    repo_name: spotbugs
    description: A tool for static analysis to look for bugs in Java code.
    asset: spotbugs-{{trimV .Version}}.tgz
    format: tar.gz
```

However the chmod command will fail because it runs in the current directory. I think the mise should pass `MISE_TOOL_DIR` (or some other suitably named) environment when it runs postinstall hook defined for the tool. The `MISE_TOOL_VERSION` would be nice as well.

**Comment by jdx** [comment]
any reason spotbugs can't set the executable bit in their tarball?

I'm also open to adding an env var around this but it definitely seems like something that should be fixed upstream too

**Reply by hoshsadiq** [reply]
I think having at least the tool dir and version passed in would be a great idea. My use case is to basically create a link for another file so that i can have the binary called by multiple names:

```toml
"aqua:itchyny/gojq" = { version = "latest", postinstall = """\
  ln -fs _gojq $(mise where aqua:itchyny/gojq)/*/jq
""" }
```

I've found a workaround similar to the others by using find, but it'd be nicer to have something more concrete

**Comment by iilyak** [comment]
I was able to temporary workaround this issue. But it is bad. Ideally this should go into aqua registry spec. Some yaml field to update permission for a file matching the pattern. Requiring the user of the tool to do it manually every time is bad UX. I realize that it might be hard to convince aquaproj to change the spec.

```toml
"aqua:iilyak/spotbugs/spotbugs" = { version = '4.9.0', postinstall = """\
    mise where aqua:cloudant/spotbugs/spotbugs | xargs -I {} chmod +x {}/spotbugs/bin/spotbugs
"""}
```

**Reply by jdx** [reply]
this isn't a common problem, I don't think I've seen where we've needed to do this for a tool in the past

**Comment by mxcoder** [comment]
Hello! I was just trying to find exactly this :)
Basically the idea is that I want to follow the recommendation of **not** using `mise activate` by default, but still I would like mise to help me manage `uv` and `usage` (for mise autocompletion!)

So my current `~/.config/mise/config.toml` has this:
```toml
[tools]
usage = { version = "latest", postinstall = '''
	find $(mise where usage) -executable -name "usage" | xargs -I {} ln -s {} $HOME/bin/usage
''' }
uv = { version = "latest", postinstall = '''
	find $(mise where uv) -executable -name "uv" | xargs -I {} ln -s {} $HOME/bin/uv
''' }
```

Seems to be working, but maybe something that could be a bit easier?
```toml
[tools]
usage = { version = "latest", postinstall = 'ln -s $path $HOME/bin/$tool' }
uv = { version = "latest", postinstall = 'ln -s $path $HOME/bin/$tool' }
```

The general idea is that these two tools, I do want available by default, all the time. And also I want mise to be able to update them.

But for the rest, I will let local mise configs do the job.

Also it would be even nicer if we had a way to run:
```sh
mise use -g uv --bin-link $HOME/bin/
```
Or something like that.

Thanks a lot for the tool! its amazing!
