### DISCUSSION TITLE
bug: The symbolic links are not created when it is not a top level

### DISCUSSION THREAD

**Discussion by iilyak** [jdx/mise#4206] [Ideas]
The aquaproj registry supports [definition of files](https://aquaproj.github.io/docs/reference/registry-config/files). The `mise` creates the symlink named as specified in the `name` field and pointing to the file mentioned in the `src`.

For example [the following](https://github.com/aquaproj/aqua-registry/blob/0f03159c30ed88d00c4b75df675afcb159a41aaf/pkgs/sue445/plant_erd/registry.yaml#L12) would create a symlink named `plant_erd` pointing to `plant_erd_linux_x86` 

```yaml
    files:
      - name: plant_erd
        src: plant_erd_{{.OS}}_{{.Arch}}
```

Unfortunately it doesn't work when the `src` [has slashes in it](https://github.com/aquaproj/aqua-registry/blob/0f03159c30ed88d00c4b75df675afcb159a41aaf/pkgs/clok/sm/registry.yaml#L16).

```yaml
    files:
      - name: sm
        src: sm_{{trimV .Version}}_{{.OS}}_{{.Arch}}/sm
```

The symlink is not created

```
❯ ls -la /Users/iilyak/.local/share/mise/installs/aqua-clok-sm/0.1.3
total 0
drwxr-xr-x  3 iilyak  staff   96 Jan 24 08:30 ./
drwxr-xr-x  7 iilyak  staff  224 Jan 24 08:30 ../
drwxr-xr-x  6 iilyak  staff  192 Jan 24 08:30 sm_0.1.3_darwin_arm64/
```
