### DISCUSSION TITLE
MISE_TRUSTED_CONFIG_PATHS working but with a string value only

### DISCUSSION THREAD

**Discussion by davlgd** [jdx/mise#4212] [Troubleshooting and bug reports]
My application is in `~/app_0f5a5bcb-cd94-488b-b54e-768cc4f036d7` which is untrusted.

To trust it, I add a setting which is not working: 

```
[settings]
trusted_config_paths = ["~/app_0f5a5bcb-cd94-488b-b54e-768cc4f036d7"]
```

![image](https://github.com/user-attachments/assets/78964b6a-f459-4434-828b-53a4209ef6cf)

If I use the `MISE_TRUSTED_CONFIG_PATHS` environment variable, I face the same problem. But if y set this env var to `~/app_0f5a5bcb-cd94-488b-b54e-768cc4f036d7` (just a string, no array), it's working and I have no warning:

![image](https://github.com/user-attachments/assets/9b6b8059-a96a-47f2-9a06-22c462011559)

But documentation [states](https://mise.jdx.dev/configuration/settings.html#trusted_config_paths) that a string array is expected and that's what's produced by `mise settings set` command.

Mise doctor: 

```
version: 2025.1.6 linux-x64 (2025-01-13)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Mon, 13 Jan 2025 18:09:04 +0000
  Rust Version: rustc 1.84.0 (9fc6b4312 2025-01-07) (built from a source tarball)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise
```
