### DISCUSSION TITLE
Hanging (circular?) dependencies in tasks

### DISCUSSION THREAD

**Discussion by EricDriussi** [jdx/mise#4222] [Troubleshooting and bug reports] [answered]
Followup of #3965 and [this comment](https://github.com/jdx/mise/issues/4009#issuecomment-2600940911).

For this setup:

```toml
[tasks.A]
run = "echo A"

[tasks.B]
depends = ["A"]
run = "echo B"

[tasks.C]
depends_post = ["B"]
run = "echo C"

[tasks.D]
depends_post = ["C"]
run = "echo D"
```

Task `D` hangs with this output:

```sh
mise run D

[A] $ echo A
[D] $ echo D
[A] A
[A] Finished in 3.5ms
[D] D
[D] Finished in 4.2ms
```

Running `mise tasks deps --dot D` shows this digraph:

```sh
digraph {
    0 [ label = "D"]
    1 [ label = "B"]
    2 [ label = "C"]
    3 [ label = "A"]
    1 -> 0 [ ]
    2 -> 0 [ ]
    1 -> 2 [ ]
    1 -> 3 [ ]
    2 -> 1 [ ]
    2 -> 3 [ ]
}
```

Given the setup, these deps seem odd, since there is no direct dependency between B and D or C and D (at least not directly/in that order):

```
1 -> 0 [ ]
2 -> 0 [ ]
```

Something similar happens with this setup:

```toml
[tasks.A]
run = "echo A"

[tasks.B]
depends = ["A"]
run = "echo B"

[tasks.C]
depends_post = ["A"]
run = "echo C"

[tasks.D]
depends_post = ["C", "B"]
run = "echo D"
```

Where it also hangs, and the deps are shown as:

```sh
digraph {
    0 [ label = "D"]
    1 [ label = "C"]
    2 [ label = "B"]
    3 [ label = "A"]
    1 -> 0 [ ]
    2 -> 0 [ ]
    3 -> 0 [ ]
    1 -> 3 [ ]
    2 -> 3 [ ]
    1 -> 2 [ ]
    3 -> 2 [ ]
    3 -> 1 [ ]
    2 -> 1 [ ]
}
```

Where are these coming from?

```
1 -> 2 [ ]
2 -> 1 [ ]
```

To be clear, I'm not really familiar with DOT digraphs so I might just not understand the output.
Still, these setups fail to run.

I tried to give this a shot myself following [these changes](https://github.com/jdx/mise/pull/4010) but could not get the e2e test to work.

I have a gut feeling that using `HashSet` [here](https://github.com/jdx/mise/blob/main/src/task/mod.rs#L58-L63) instead of `Vec` might help, but I'm not sure.
