### DISCUSSION TITLE
Environment selector (for bash shells)

### DISCUSSION THREAD

**Discussion by mastertheif** [jdx/mise#4268] [Show and tell]
# Environment selector (for bash shells)

First, thanks everyone who have worked on Mise, it really changed my workflow in an wonderful way! :)  

I'm not sure if this will be useful for anyone but me, but there is a little script (bash only) that scans the project/.config directory to be able to select an environment and set MISE_ENV using gum.

Just type selectEnv anywhre in your project

ex:

[![asciicast](https://asciinema.org/a/sC0peZGstyzJhMR1JBZv76nQK.svg)](https://asciinema.org/a/sC0peZGstyzJhMR1JBZv76nQK)

## Organization tree

```
project/
└── .config/
    ├── selectEnvMiseProject
    ├── mise.toml
    ├── mise.nameEnv1.toml
    ├── mise.nameEnv2.toml
    ├── mise.nameEnv3.toml
    └── mise.nameEnv4.toml
```

## mise.toml

```toml
[settings]
status = {show_env = true, show_tools = true, missing_tools = "always"}

[env]
MISE_CONFIG_ROOT="{{config_root}}"

[tools]
"aqua:charmbracelet/gum" = "latest"
```

## mise.nameEnvX.toml

It will print the current environment you are in on your shell

```toml
[env]
PROMPT_COMMAND="echo \"Current env: {{env.MISE_ENV}}\""
```

## selectEnvMiseProject

```bash
#!/usr/bin/env bash

# Check if gum is installed
if ! command -v gum &> /dev/null
then
  echo "gum is not installed"
  return 1
fi

if [[ -z $MISE_CONFIG_ROOT ]]
then
  echo "The environment variable MISE_CONFIG_ROOT is not set"
  return 1
fi

declare -a detected_config_names=()

for mise_detected_env_file in "$MISE_CONFIG_ROOT"/.config/*
do
    if [[ $mise_detected_env_file =~ mise\.(.+)\.toml$ ]]
    then
        detected_config_names+=("${BASH_REMATCH[1]}")
    fi
done

GUM_SELECTED_ENV=$(gum choose --height 15 --header="Select an environment" "reset" "${detected_config_names[@]}")

# if the gum prompt was exited without choosing any option, it will reset the MISE_ENV variable 
if [[ $? -ne 0 ]]
then
  GUM_SELECTED_ENV="reset"
fi

unset detected_config_names

export MISE_ENV="$GUM_SELECTED_ENV"

if [[ $GUM_SELECTED_ENV == reset ]]
then
  unset -v MISE_ENV
fi

# Force Mise reload
cd .
```

## .bashrc
Add this to your .bashrc file and reload your shell

```bash
alias selectEnv='[ ! -e "$MISE_CONFIG_ROOT/.config/selectEnvMiseProject" ] || command source "$MISE_CONFIG_ROOT/.config/selectEnvMiseProject"'
```
