### DISCUSSION TITLE
Enhancement: python.uv_venv_auto should take into account UV_PROJECT_ENVIRONMENT

### DISCUSSION THREAD

**Discussion by rsyring** [jdx/mise#4301] [Ideas]
uv's default is to use `.venv` for a project's virtualenv.  However, a different path can be provided by using [UV_PROJECT_ENVIRONMENT](https://docs.astral.sh/uv/configuration/environment/#uv_project_environment).

Currently, mise [doesn't check](https://github.com/jdx/mise/blob/67eb899d6ef306c25c83281ff9c750b7e377cff7/src/uv.rs#L70) for an alternate location.

This is probably obvious, but the variable being used should come from the result of mise's environment variable processing pipeline.  

My current workaround is to set:

```toml
[env]
_.python.venv.path = '{{ env.UV_PROJECT_ENVIRONMENT }}'
_.python.venv.create = true
```

But it would be cleaner if I could just:

```toml
[settings]
python.uv_venv_auto = true
```

and trust that whatever uv is doing, mise will play along.

FWIW, my higher-level goal is to support some of our users wanting to use `.venv` and some users wanting to put those files in a temporary/cache location.  So, our actual project files look like:

```toml
[env]
VENV_IDENT = 'foo-app'

_.python.venv.path = '{{ env.VIRTUALENV_DIR }}'
_.python.venv.create = true
```

And then `~/mise.toml` has:

```toml
[env]
VIRTUALENV_DIR = '.venv'
```

or:

```toml
[env]
VIRTUALENV_DIR = { value='{% if env.VENV_IDENT %}~/.cache/venvs/{{ env.VENV_IDENT }}{% endif %}', tools = true }
UV_PROJECT_ENVIRONMENT = { value='{% if env.VIRTUALENV_DIR %}{{ env.VIRTUALENV_DIR }}{% endif %}', tools = true }
```

**Comment by rsyring** [comment]
@jdx with [uv integration enhancements a stated goal for 2025](https://github.com/jdx/mise/discussions/4057#uv-integration), might this warrant an issue?

The workaround is ok, but it would be nice to be able to set `python.uv_venv_auto` at the user level and remove all venv activation config from a project's `mise.toml`. 

Thanks for considering.

**Comment by rsyring** [comment]
FWIW, here is how I'm currently handling this to get support for devs who do and don't want to use a local .venv:

```toml
# ~/.config/mise.toml

[env]
UV_PROJECT_ENVIRONMENT = { value='{% if env.PROJECT_SLUG %}/home/rsyring/.cache/uv-venvs/{{ env.PROJECT_SLUG }}{% endif %}', tools = true }

[settings]
python_venv_auto_create = true
```

And then in a project's `mise.toml`:

```toml
PROJECT_SLUG = '{{ config_root | basename | slugify }}'

_.python.venv.path = '{% if env.UV_PROJECT_ENVIRONMENT %}{{ env.UV_PROJECT_ENVIRONMENT }}{% else %}.venv{% endif %}'
_.python.venv.create = true
```

Would still be nice to see mise recognize `UV_PROJECT_ENVIRONMENT` and use it for the Python venv path.  

The upstream solution would be for uv to support a centralized location for virtualenvs.  That is being tracked at: https://github.com/astral-sh/uv/issues/1495

**Reply by Marukome0743** [reply]
This is supported now following [PR #11475](https://github.com/jdx/mise/pull/11475).

With current mise, `python.uv_venv_auto = true` honors `UV_PROJECT_ENVIRONMENT` when selecting the project virtualenv path. The value can come from either the process environment or mise’s processed config environment, so a user-level configuration can provide the custom path without requiring each project to repeat the explicit `_.python.venv.path` directive.

For example:

```toml
[env]
UV_PROJECT_ENVIRONMENT = "/path/to/custom/venv"

[settings]
python.uv_venv_auto = true
```

Updating to a current mise release should allow the simpler configuration requested here.

*AI-assisted — Tool: Codex; model: OpenAI/GPT-5; version: unavailable.*
