### DISCUSSION TITLE
How setup local aqua registry for private packages in mise?

### DISCUSSION THREAD

**Discussion by Ernest0-Production** [jdx/mise#4306] [Q&A]
I'm trying to create `registry.yml` directly in my project's repository to install dependencies that are currently missing from the default registry. 
```yml
packages:
- type: github_release
repo_owner: eroshenkoam
repo_name: xcresults
asset: "xcresults.tar.gz"
description: Command line tool to convert Xcode test results to JUnit format
supported_envs:
- darwin/amd64
- darwin/arm64
checksum:
type: github_release

```

But I don't understand how to properly connect it to `mise.toml`.

If this is still not possible, would it be possible to configure an asdf plugin that will be located in the project's repository itself, and not in a separate one, as is usually done?

**Comment by JamBalaya56562** [comment]
Yes, this is possible — and the part that was blocking your actual requirement has just been fixed.

**1. The setting is `aqua.registries`**

It takes a repository URL, a direct URL to a `registry.yaml`, or a `file://` URL to a local file or directory. (`aqua.registry_url`, which older threads mention, is the deprecated single-source form.)

**2. A registry committed inside the project now works**

This was the real obstacle: a relative entry used to fail with `invalid aqua registry URL registry.yaml: relative URL without a base`, and `{{config_root}}` is not expanded in `[settings]`, so the only working form was an absolute path — which you cannot commit. #11804 makes a non-URL entry resolve against the config root of the file that declared it:

```toml
[settings]
aqua.registries = ["registry.yaml"]
```

Merged, but **not yet in a release** — v2026.8.3 was cut before it landed. Until then, use an absolute `file://` URL, or set it per machine:

```console
$ MISE_AQUA_REGISTRIES="file:///home/me/proj/registry.yaml" mise ls-remote aqua:myorg/mytool
2.96.0
2.97.0
```

(env-var and CLI values still need an absolute URL, since there is no config file to resolve against.)

**3. Your YAML will not parse as written**

The package fields sit at the same indentation as `packages:`, so it is not a list. It needs to be:

```yaml
packages:
  - type: github_release
    repo_owner: eroshenkoam
    repo_name: xcresults
    asset: xcresults.tar.gz
    supported_envs:
      - darwin/amd64
      - darwin/arm64
```

Then refer to it as **`aqua:eroshenkoam/xcresults`**. aqua package ids are `owner/repo`, taken from `repo_owner`/`repo_name` unless you set `name:`; a single-segment `aqua:xcresults` produces `invalid aqua tool`.

**On the asdf fallback question** — you do not need it. And if you want *only* your registry to be installable, add `aqua.baked_registry = false`, which stops the built-in registry being consulted at all.
