### DISCUSSION TITLE
Be able to pass arguments to task dependencies

### DISCUSSION THREAD

**Discussion by jansepke** [jdx/mise#4309] [Ideas]
We are currently trying to integrate mise task in a monorepo where we want to run and build the different applications that all have a frontend and a backend. we want to utilize task dependencies for this but don't find a way to pass arguments to the task dependencies.

```toml
[tasks.start-backend]
dir = "apps"
run = "cd app1/backend && pnpm run dev"
depends = "install-deps"

[tasks.start-frontend]
dir = "apps"
run = "cd app1/frontend && pnpm run dev"
depends = "install-deps"

[tasks.start]
run = ""
depends = ["start-backend", "start-frontend"]
```

the "app1" should be configurable by the `start` so that the `start` task could have an `arg()` that could be passed to its dependencies. This would be similar to how Taskfile supports passing variables to dependencies https://taskfile.dev/usage/#calling-another-task
