### DISCUSSION TITLE
Optional positional args

### DISCUSSION THREAD

**Discussion by davidolrik** [jdx/mise#4320] [Ideas]
I have a task with one option, but also want the rest of what ever args passed after that option to be passed to one of the commands I'm running.

As it is now, if you specify an `arg`, it becomes required which is not what I want.

The closest I can come is `{{arg(name='args', var=true, default='')}}` which gives me on single arg: `''`.

I propose a `default=nil` or a `optional=true` to solve this issue.

**Comment by rsyring** [comment]
I was just having this problem and came to create a similar discussion.  I'd also like to be able to use it with `var=true` in order to create a default command that works without any args but can also receive all the rest of the args/options on the command line.

I'm going to propose `req=false` since it matches `var`'s semantics of short & bool.  Could also do `opt=true` but that could lead to confusion that it's referring to something to do with options instead of being optional.  

Example:

```toml
[tasks.media-ls]
description = "List ALL files on R2"
# Lists all files at root by default but user has option of being more explicit
run = 'rclone ls $MEDIA_R2/{{ arg(name="path", req=false) }}'
```

```
$ mise media-ls
[media-ls] $ rclone ls $MEDIA_R2/
...

$ mise media-ls videos
[media-ls] $ rclone ls $MEDIA_R2/videos
...
```

FWIW, this particular use case could just use the default.  But I had a use case last night where it wouldn't and can't remember the exact semantics right now.  If you want a real use case, let me know, and I'll go back and figure out what I was doing.

**Comment by mohannad-musleh** [comment]
I have the same problem too, any workarounds available?

**Comment by sergei-ivanov** [comment]
I have the same problem with variadic arguments. I had to find a harmless option to pass to the tool by default, so that it does not complain about an empty argument.

My proposal would be to make `default` a list when `var=true`:
```
docker buildx build . {{arg(name="var_args", var=true, default=[])}}
```
or
```
docker buildx build . {{arg(name="var_args", var=true, default=["--progress", "plain"])}}
```

**Reply by sergei-ivanov** [reply]
See also https://github.com/jdx/mise/discussions/6256

**Comment by maxandersen** [comment]
same issue here, want to be able to allow optional pass additional args for gradle test runs, i.e.:

```
[tasks.itest]
depends = "build"
description = "Run integration tests"
run = "./gradlew integrationTest {{arg(var=true,default='')}}"
```

lets me run it ..but empty arg fails gradle as it see it as an empty path.

in justfile where I'm trying to port from I do: 

```
itest *args:
    {{preitest}}
    ./gradlew integrationTest {{args}}
```

the *{{args} means 0 to n...

**Comment by risu729** [comment]
I think we can add an option to disable quoting. See https://github.com/jdx/mise/discussions/4604

**Comment by sergei-ivanov** [comment]
I think I have just cracked it. It does require a bit of template scripting, but it works marvellously:

```toml
[tasks.plan]
description = "Run a plan against the specific environment"
run = '''
{% set _environment = arg(name="environment", default="dev") %}
{% set _terraform_args = arg(name="terraform_args", var=true, default="") %}
TF_WORKSPACE={{ _environment }} terraform -chdir={{ config_root }} plan {% if _terraform_args != "''" %}{{ _terraform_args }}{% endif %}
'''
```

The part that gave me grief was that the default value was internally resolved not as an empty string `""`, but as a shell-escaped empty string `"''"`. Once I figured it out, the rest was easy.

So with the above in place, I can run mise tasks as follows (the rendered command is shown in the mise output):

```
$ mise plan
[plan] $ TF_WORKSPACE=dev terraform -chdir=/home/sergey/projects/xxxx/terraform plan
...

$ mise plan dev
[plan] $ TF_WORKSPACE=dev terraform -chdir=/home/sergey/projects/xxxx/terraform plan
...

$ mise plan staging
[plan] $ TF_WORKSPACE=staging terraform -chdir=/home/sergey/projects/xxxx/terraform plan
...

$ mise plan staging -target='x.x[0]' -refresh-only
[plan] $ TF_WORKSPACE=staging terraform -chdir=/home/sergey/projects/xxxx/terraform plan '-target=x.x[0]' -refresh-only
...
```

There you go, feel free to use.

@jdx maybe it's worth adding the above example to the official docs?
