### DISCUSSION TITLE
Be able to pass arguments to task dependencies

### DISCUSSION THREAD

**Discussion by jansepke** [jdx/mise#4331] [Ideas]
We are currently trying to integrate mise task in a monorepo where we want to run and build the different applications that all have a frontend and a backend. we want to utilize task dependencies for this but don't find a way to pass arguments to the task dependencies.

```toml
[tasks.start-backend]
dir = "apps"
run = 'cd {{arg(name="app")}}/backend && pnpm run dev'

[tasks.start-frontend]
dir = "apps"
run = 'cd {{arg(name="app")}}/frontend && pnpm run dev'

[tasks.start]
dir = "apps"
run = ""
depends = [
    'start-backend {{arg(name="app")}}',
    'start-frontend {{arg(name="app")}}',
]
```

Executing it with `mise run start my-app`.

The "app" should be configurable by the `start` so that the `start` task could have an `arg()` that could be passed to its dependencies. This would be similar to how Taskfile supports passing variables to dependencies https://taskfile.dev/usage/#calling-another-task

**Comment by jdx** [comment]
I would just use an env var

**Comment by jansepke** [comment]
yes that is possible, but not so convenient and does not support autocomplete for the argument
`ENV=my-app mise run start` vs. `mise run start my-app`

**Reply by jdx** [reply]
you could do this:

```toml
[tasks.start-backend]
dir = "apps"
run = 'cd {{env.APP}}/backend && pnpm run dev'

[tasks.start-frontend]
dir = "apps"
run = 'cd {{env.APP}}/frontend && pnpm run dev'

[tasks.start]
dir = "apps"
run = '''
APP={{arg(name="app")}} mise run start-backend ::: start-frontend
'''
```

**Reply by qoomon** [reply]
sure that would work as a workaround, however it would feel so much more natural to have variable resolution also within `depends`  values

**Reply by qoomon** [reply]
and you can run all task the same way `mise run start-frontend --name foo` as well as `mise run start --name foo`

**Reply by jdx** [reply]
I'd probably accept a PR, but I think it might be tricky to do

**Reply by jansepke** [reply]
I also tried running mise with multiple commands but this will behave differently compared to mise running in multiple dependency mode:
* `task_output` does not automatically switch to `prefix`
* `Ctrl+C` does not work at all

**Reply by qoomon** [reply]
@jdx could you guide me to the right entrypoint to implement variable resolution within depdendencies?

**Reply by jdx** [reply]
well the way args/flags work is placeholders like `MISE_TASK_ARG:app:MISE_TASK_ARG` get injected and are later replaced via regexes. I think that concept needs to be completely rethought for this to work correctly: https://github.com/jdx/mise/blob/cd8dc01d80b8d46d9985736bf745069da9e18afe/src/task/task_script_parser.rs#L311

notably though that logic has other problems like that you can't use arg values inside of templates.

Also this commit is likely useful for arguments were added to task definitions: https://github.com/jdx/mise/commit/686158747aa2469248caa98cc5cf1007407de853#diff-63c4ec542e3c7285826dc853a62d78aaa9550e6bfc28225945e805701d794740

**Reply by qoomon** [reply]
It's probably an issue that i don't know rust :-D I expected to just resolve the variables directly after the depends tasks have been read. Thanks anyway. I'm looking forward when this feature gets implemented.

**Reply by qoomon** [reply]
@jdx can we just pass there args to the render tery.render_str function as additional context ?
https://github.com/jdx/mise/blob/f7c62d899fec4fdb020664fb206a9b3e2450320f/src/task/task_dep.rs#L20-L23

**Reply by jdx** [reply]
I don't think it is quite that simple

**Comment by boris-smidt-klarrio** [comment]
Using env variables also causes the issue that you have to run mise for every env option.
You can't do:
```bash
mise run build app1 :: build app2
```

I've also had a look at the code and it indeed needs quite some restructuring since you need to template the dependencies and add the arg to the 'graph' calculation and the task names have to be updated, otherwise you will see 
```
[build] x
[build] y
```
where the only difference is the color of build to mark what is being build.

**Reply by boris-smidt-klarrio** [reply]
A possible way to implement it is to:

Concat the dependencies with the task string and pass it to this functions to know all 'template' values.
https://github.com/jdx/mise/blob/b4db2249e6a27ed051e61d68e883d247def6d20d/src/task/task_script_parser.rs#L29C12-L29C29

Then each dependency and task could be passed to individually to resolve the template values:
https://github.com/jdx/mise/blob/b4db2249e6a27ed051e61d68e883d247def6d20d/src/task/task_script_parser.rs#L311

Sadly the run task is resolved just before running it so the code needs to be reorganized to resolve it before the graph (DAG) is build.
My rust skills are a bit lacking so i had trouble to pick this up and refactor it.

**Comment by nicholaschiasson** [comment]
Can we convert this discussion into an issue, or create an issue from it? Since it's not a straightforward Q&A and rather, more of a feature request, I think it would make sense. Plus I would love to see this feature myself 🙂

**Reply by jdx** [reply]
I'm not convinced yet at all

**Reply by mands** [reply]
I think this feature becomes more important with the advent of "Monorepo tasks" (#6564), as it's not uncommon to have a monorepo with a collection of root tasks that would need to call subtasks across the projects with specific parameters.

**Comment by sermuns** [comment]
It sounds like [process-compose](https://github.com/F1bonacc1/process-compose) could help you out?

I tried creating a simple example for your use case, although I realise it still doesnt offer what you are seeking; to be able to provide arbitrary app directory:

```yaml
# process-compose.yaml

processes:

  frontend:
    working_dir: frontend
    command: pnpm run dev

  backend:
    working_dir: backend
    command: pnpm run dev
```

**Comment by norbertkeri** [comment]
What's the correct way to do this? I've seen the advice "just use env variables" but I can't figure it out:

```toml
[tasks.build]
run = 'echo building image with tag {{arg(name="tag")}}'


[tasks.push]
depends = ["build ???"] # Can't use {{ env.* }} here
run = 'echo pushing image with tag {{arg(name="tag")}}'
```

**Comment by nikitalocalhost** [comment]
I have the following use case: multiplatform C++ build with multiple build prefixes: build/linux and build/windows. So, something like this:
```toml
[tasks.configure]
usage = '''
arg "<platform>" help="Target platform" default="{{ os() }}"
'''
run = '''
meson setup build/{{usage.platform}}
'''

[tasks.build]
usage = '''
arg "<platform>" help="Target platform" default="{{ os() }}"
'''
depends = [
    { task = "configure", args = ["{{usage.platform}}"] },
]
run = '''
meson compile -C build/{{usage.platform}}
'''
```

So when i'm writing `mise build` it configures and builds for native, and with explicit argument: `mise build linux` it configures and builds for specified platform.

And then you can imagine if you have prefix variants with build config: Release, Debug, etc... you want to have more arguments that configures behavior for tasks

And argument
> I would just use an env var

IMHO then why do you need `usage` anyway if you could use env? IMHO: DX. So when you have multiple switches and parameters for script s there is type checking, help, etc.

```toml
[env]
BUILD_PLATFORM = "{{env.BUILD_PLATFORM | default(value=os())}}"
BUILD_CONFIG = "{{env.BUILD_CONFIG | default(value='release'}}"

[tasks.configure]
run = '''
meson setup build/{{env.BUILD_PLATFORM}} --buildtype {{env.BUILD_CONFIG}} # Oops - bad platform, bad config, no type checking
'''

[tasks.build]
depends = [
    { task = "configure" },
]
run = '''
meson compile -C build/{{env.BUILD_PLATFORM}} # Oops, i forgor to unset BUILD_PLATFORM, so F me
'''
```

**Comment by syedways** [comment]
I think this is a fundamental problem with mise tasks and a big reason I can't use it as much as I want to. I want to use it for parallelizing simple commands under the umbrella of a parent task - all of the commands use the same argument(s). For example, I have a `lint` task that needs to call 5 different tasks, all of which take an optional 'folder' argument, in parallel - there is no way to do this without doing things that nullify the purpose of using the task system in the first place (and the niceties it entails such as prefixed output, timings, etc.) ie. `mise run <task> <arg> ::: <task> <arg> ::: <task> <arg>`. Task templates seem like a perfect fit but they don't work either because the tasks are provided no native way to access the parent task's arguments.

**Comment by jdx** [comment]
I've opened a PR that implements this feature: https://github.com/jdx/mise/pull/8893

You can now pass arguments to task dependencies using `{{usage.*}}` templates:

```toml
[tasks.start-backend]
usage = 'arg "<app>"'
run = 'cd {{usage.app}}/backend && pnpm run dev'

[tasks.start-frontend]
usage = 'arg "<app>"'
run = 'cd {{usage.app}}/frontend && pnpm run dev'

[tasks.start]
usage = 'arg "<app>"'
depends = [
    { task = "start-backend", args = ["{{usage.app}}"] },
    { task = "start-frontend", args = ["{{usage.app}}"] },
]
```

Then `mise run start my-app` passes `my-app` to both dependencies. It also works with flags, string syntax (`depends = ["build {{usage.app}}"]`), and chains through multiple levels of dependencies.

*This comment was generated by Claude Code.*
