### DISCUSSION TITLE
Post-hook for self-update

### DISCUSSION THREAD

**Discussion by reitzig** [jdx/mise#4335] [Ideas]
I've taken to installing shell completions through postinstall hooks, which goes something like this:

```toml
[tools.chezmoi]
version = "latest"
postinstall = 'chezmoi completion fish > "$FISH_COMPLETION_DIR/chezmoi.fish"'
```

What I _haven't_ been able to figure out is how to run

```fish
mise completion fish > "$FISH_COMPLETION_DIR/mise.fish"
```

after I `mise self-update`.

`hooks.postinstall` seems to run after installing any tool _through_ mise, which is not what I would need.
Did I miss anything?

If not, I'd propose `hooks.postselfupdate` for the purpose.
