### DISCUSSION TITLE
postuninstall hook for tools

### DISCUSSION THREAD

**Discussion by reitzig** [jdx/mise#4337] [Ideas]
I've taken to installing shell completions through postinstall hooks, which goes something like this:

```toml
[tools.chezmoi]
version = "latest"
postinstall = 'chezmoi completion fish > "$FISH_COMPLETION_DIR/chezmoi.fish"'
```

How to ever _remove_ them again, though?

I'm thinking something like

```toml
postuninstall = 'rm -f "$FISH_COMPLETION_DIR/chezmoi.fish"'
```

What I'm not clear about is how to handle multiple installed versions of the same tool. With the `postinstall` hook as above, the last installed version would win out for the completion (can't be helped), but we wouldn't want to remove the completion as long as at least one version remains. 🤔

Also, I guess there's a can of worms when thinking about how to handle hooks included in multiple `mise.toml` -- which would trigger? (_I_ don't know, but there's certainly a way it works for the existing hooks.)
