### DISCUSSION TITLE
installing ossf/scorecard is messy

### DISCUSSION THREAD

**Discussion by timothysparg** [jdx/mise#4352] [General]
I was trying to use [ossf/scorecard](https://github.com/ossf/scorecard) but things started to get messy.

Installing with `mise use ubi:ossf/scorecard` fails as the binary has a different name to the project (foreshadowing...)

<details><summary>Stacktrace</summary>

> mise ERROR failed to install ubi:ossf/scorecard@5.0.0
mise ERROR Failed to install with ubi 'ubi:ossf/scorecard@5.0.0': could not find any files named scorecard in the downloaded tarball
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information

</details> 

This can be resolved by specifying the exe parameter as part of the call `mise use "ubi:ossf/scorecard[exe=scorecard-darwin-arm64]"`.
However this gives me a mac specific `mise.toml`.

I can make things more portable if I start doing some templating in the config file

```TOML
[env]
MISE_OS = "{{ os() | replace(from='macos', to='darwin') }}"

[tools]
"ubi:ossf/scorecard" = { version = "latest", exe = "scorecard-{{ get_env(name='MISE_OS') }}-{{ arch() }}"}
```

This solves the portability issue - it should install on different environments now, but we're still left with the binary have a different name across different platforms, which is less than ideal.

I tried to setup a `postinstall` step to move the binary from the something like `scorecard-darwin-arm64` to `scorecard` but I feel like I'm diving down a rabbit hole here. 
This is what I've come up with so far (it fails with some templating issue currently that I'm trying to resolve) but I thought I would at least ask the question to see if I'm heading in the right direction.

```TOML
[env]
MISE_OS = "{{ os() | replace(from='macos', to='darwin') }}"

[tools."ubi:ossf/scorecard"]
version = "latest"
exe = "scorecard-{{ get_env(name='MISE_OS') }}-{{ arch() }}"
postinstall = "mv {{ exec(command='mise bin-paths ubi:ossf/scorecard') }}/scorecard-{{ get_env(name='MISE_OS') }}-{{ arch() }} {{ exec(command='mise bin-paths ubi:ossf/scorecard') }}/scorecard"
``` 

**Note** there's some extra context around this here: https://github.com/houseabsolute/ubi/issues/96

**Comment by JamBalaya56562** [comment]
This is much simpler now — scorecard is in the default registry, via aqua rather than ubi. Measured on **v2026.8.2**:

```console
$ mise registry scorecard
scorecard  aqua:ossf/scorecard

$ mise ls-remote scorecard | tail -1
5.5.0
```

So the whole config collapses to:

```toml
[tools]
scorecard = "latest"
```

No `exe=` parameter, no `MISE_OS` templating to keep it portable across mac and linux, and no postinstall rename. The aqua package definition carries the per-platform asset names and the binary name, which is the layer that was missing when you were driving it through `ubi` directly.

Your instinct that you were heading down a rabbit hole was right — the templated `exe` plus a postinstall move was the only way to express it at the time, and it was solving a problem the registry entry is meant to solve.
