### DISCUSSION TITLE
Redact redacts too much

### DISCUSSION THREAD

**Discussion by davidolrik** [jdx/mise#4368] [Troubleshooting and bug reports] [answered]
Given this `mise.toml` file:

```toml
[env]
STATIC_STRING = "HELLO"
RANDOM_STRING1 = "{{ exec(command='pwgen -n 32 1') }}"
RANDOM_STRING2 = { value = "{{ exec(command='pwgen -n 32 1') }}", redact = true }

[tasks."echo:static_string"]
run = [
  "echo \"This is the static string $STATIC_STRING\"",
]

[tasks."echo:string1"]
run = [
  "echo \"This is string 1 $RANDOM_STRING1 $STATIC_STRING\"",
]

[tasks."echo:string2"]
run = [
  "echo \"This is string 2 $RANDOM_STRING2 $STATIC_STRING\"",
]
```

I'm seeing some weird behaviour:

```sh
$ mr echo:static_string
[echo:static_string] $ echo "This is the static string $STATIC_STRING"
This is the static string [redacted]
$ mr echo:string1
[echo:string1] $ echo "This is string 1 $RANDOM_STRING1 $STATIC_STRING"
This is string 1 [redacted] [redacted]
$ mr echo:string2
[echo:string2] $ echo "This is string 2 $RANDOM_STRING2 $STATIC_STRING"
This is string 2 [redacted] [redacted]
```

Only `$RANDOM_STRING2` should be redacted here, but all of them are redacted.

<details>
<summary>I'm running 2025.2.3 macos-arm64 (2025-02-09)</summary>
<pre><tt>$ mise doctor
version: 2025.2.3 macos-arm64 (2025-02-09)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Sun, 9 Feb 2025 10:52:50 +0000
  Rust Version: rustc 1.84.0 (9fc6b4312 2025-01-07)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (arm64-apple-darwin24.0)

dirs:
  cache: ~/Library/Caches/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  /REDACTED/.mise.toml
  /REDACTED/.mise.local.toml
  /REDACTED/mise-redact/mise.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  just       https://github.com/olofvndrhr/asdf-just.git#3f907ee
  perl       https://github.com/ouest/asdf-perl.git#2b4609b
  php        https://github.com/mise-plugins/mise-php.git#e361a2c
  raku       https://github.com/m-dango/asdf-raku.git#dd8c1ef
  usage      https://github.com/jdx/mise-usage.git#fe3888a
  watchexec  https://github.com/nyrst/asdf-watchexec.git#b667a08

toolset:
  aqua:sigstore/cosign@2.4.2
  asdf:perl@5.40.1
  asdf:raku@2025.01
  asdf:usage@2.0.4
  core:go@1.23.6
  core:node@22.11.0
  core:python@3.13.2
  core:ruby@3.4.1
  core:rust@1.84.1
  ubi:slsa-framework/slsa-verifier@2.6.0

path:
  ~/.local/share/mise/installs/cosign/2.4.2
  ~/.local/share/mise/installs/slsa-verifier/2.6.0/bin
  ~/.local/share/mise/installs/go/1.23.6/bin
  ~/.local/share/mise/installs/node/22.11.0/bin
  ~/.local/share/mise/installs/perl/5.40.1/bin
  ~/.local/share/mise/installs/python/3.13.2/bin
  ~/.local/share/mise/installs/raku/2025.01/bin
  ~/.local/share/mise/installs/raku/2025.01/share/perl6/site/bin
  ~/.local/share/mise/installs/ruby/3.4.1/bin
  ~/.cargo/bin
  ~/.local/share/mise/installs/usage/2.0.4/bin
  ~/.local/bin
  ~/bin
  /usr/local/sbin
  /usr/local/bin
  /opt/homebrew/opt/openssl@3/bin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  [...]

env_vars:
  MISE_SHELL=zsh
  MISE_GITHUB_TOKEN=REDACTED

settings:

No problems found
</pre></tt>
</details>
