### DISCUSSION TITLE
Env variable in `get_env` default

### DISCUSSION THREAD

**Discussion by tony-sol** [jdx/mise#4371] [Q&A]
Is there a way to resolve env variables inside `default` key of `get_env` function?

Use case: i have some poetry configs in env variables, like

```toml
[env]
POETRY_DATA_DIR = "{{ env.XDG_DATA_HOME }}/pypoetry"
```
And want be sure about default location if for example XDG_CONFIG_HOME doesn't exist.

I've tried `default` like this:
```toml
[env]
POETRY_DATA_DIR = "{{ env.XDG_DATA_HOME | default(value='~/.local/share') }}/pypoetry"
```
but after all resolving, i've got `"~/.local/share"`.

---

I've also tried to use `| canonicalize`, but got strange NotFoundError, e.g.:
```toml
[env]
TEST = "{{ '~/' | canonicalize }}"
```
gives me:
```
mise ERROR failed to parse template: '{{ '~/' | canonicalize }}'
mise ERROR Failed to render '__tera_one_off'
mise ERROR Filter call 'canonicalize' failed
mise ERROR Io error while writing rendered value to output: NotFound
mise ERROR No such file or directory (os error 2)
```

---

The best case i could find my own is call `get_env()` directly, but it cannot be interpolated, like this
```toml
[env]
TEST = "{{ get_env(name='TEST_HOME', default=get_env(name='HOME')) }}"
```
will export `TEST` as real `$HOME` value if `TEST_HOME` doesn't exist, but this
```toml
[env]
TEST = "{{ get_env(name='TEST_HOME', default=get_env(name='HOME')/test-home ) }}"
```
is not possible.

I'd glad to know this is me missing something and it is not an impossible to do something like that

**Comment by JamBalaya56562** [comment]
Both things you hit come from the same cause: **`~` is not expanded in templates.**

The `default` handling itself is fine. Measured on **v2026.8.2**:

```console
# XDG_DATA_HOME unset
export A_DEFAULT=/fallback/poetry     # {{ env.XDG_DATA_HOME | default(value='/fallback') }}/poetry
export B_GETENV=/fallback/poetry      # {{ get_env(name='XDG_DATA_HOME', default='/fallback') }}/poetry

# XDG_DATA_HOME=/custom
export A_DEFAULT=/custom/poetry
export B_GETENV=/custom/poetry
```

Both forms pick the environment value when it is set and the default when it is not. What made it look otherwise is that your default was `~/.local/share`, and that tilde survives verbatim:

```console
export TILDE='~/.local/share/poetry'
```

so the result looks like "the default won" even when it did not.

The `canonicalize` error is the same thing one step further along — it calls `Path::canonicalize` on the literal string `~/`, which is not a path that exists:

```console
mise ERROR failed to parse template: '{{ '~/' | canonicalize }}'
mise ERROR error: Io error while writing rendered value to output: NotFound
```

Use `{{ env.HOME }}` instead of `~`:

```toml
[env]
POETRY_DATA_DIR = "{{ get_env(name='XDG_DATA_HOME', default=env.HOME ~ '/.local/share') }}/pypoetry"
```

One fair complaint remains: that `canonicalize` error names neither the path nor the reason, which is why it reads as a template parse failure rather than "this path does not exist".
