### DISCUSSION TITLE
Enter hooks loop infinitely when shell is set to fish

### DISCUSSION THREAD

**Discussion by reitzig** [jdx/mise#4378] [Troubleshooting and bug reports] [answered]
Say I want to use tasks to perform certain actions when entering and leaving the project directory. Let's start with this MWE:

```toml
[hooks]
enter = "mise run entering"
leave = "cd $MISE_PREVIOUS_DIR; mise run leaving"

[tasks.entering]
hide = true
run = "echo \"I'm here!\""

[tasks.leaving]
hide = true
run = "echo \"I'm gone!\""
```

The behaviour is as expected:

```
> cd foobar
[entering] $ echo "I'm here!"
I'm here!

~/foobar
> cd ..
[leaving] $ echo "I'm gone!"
I'm gone!
```

Now say I want the tasks to run in `fish`. Following the documentation:

```toml
[hooks]
enter = "mise run entering"
leave = "cd $MISE_PREVIOUS_DIR; mise run leaving"

[tasks.entering]
hide = true
shell = "fish -c"
run = "echo \"I'm here!\""

[tasks.leaving]
hide = true
shell = "fish -c"
run = "echo \"I'm gone!\""
```

Now, the behaviour is decidedly _not_ okay:

```
~
> cd foobar/
[entering] $ echo "I'm here!"
[entering] $ echo "I'm here!"
[entering] $ echo "I'm here!"
[entering] $ echo "I'm here!"
[entering] $ echo "I'm here!"
[entering] $ echo "I'm here!"
mise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exitmise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exit

mise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exit
mise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exit
mise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exit
mise WARN  Ctrl-C pressed, please wait for tasks to finish or press Ctrl-C again to force exit
[entering] ERROR fish exited with non-zero status: no exit status
[entering] ERROR fish exited with non-zero status: no exit status
[entering] ERROR fish exited with non-zero status: no exit status[entering]
 ERROR task failed
[entering] ERROR task failed
[entering] ERROR task failed
[entering] ERROR fish exited with non-zero status: no exit status
[entering] ERROR task failed
[entering] ERROR fish exited with non-zero status: no exit status
[entering] ERROR task failed
```

The task runs repeatedly until I hit CTRL+C (multiple times). When leaving the directory, the behaviour is similar.

I'm stumped:

- it works with `bash -c`
- `fish -c` _should_ behave just like `bash -c`

Not sure if the problem is with mise, fish, my holding either of them, or a combination. Any ideas? 

<details><summary>mise doctor</summary>

```
version: 2025.2.3 linux-x64 (2025-02-09)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Sun, 9 Feb 2025 10:53:31 +0000
  Rust Version: rustc 1.84.1 (e71f9a9a9 2025-01-27)
  Profile: release

shell:
  /usr/bin/fish
  fish, version 3.7.1

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  ~/foobar/mise.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  aqua:astral-sh/uv@0.5.29
  aqua:charmbracelet/gum@0.15.2
  core:python@3.13.2
  ubi:dandavison/delta@0.18.2
  ubi:jdx/usage@2.0.4
  ubi:starship/starship@1.22.1
  ubi:twpayne/chezmoi@2.59.0

path:
  ~/.local/share/mise/installs/usage/2.0.4
  ~/.local/share/mise/installs/python/3.13.2/bin
  ~/.local/share/mise/installs/chezmoi/2.59.0
  ~/.local/share/mise/installs/delta/0.18.2
  ~/.local/share/mise/installs/gum/0.15.2/gum_0.15.2_Linux_x86_64
  ~/.local/share/mise/installs/starship/1.22.1
  ~/.local/share/mise/installs/uv/0.5.29/uv-x86_64-unknown-linux-musl
  ~/.local/share/aquaproj-aqua/bin
  ~/.local/bin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/local/sbin
  /usr/bin/site_perl
  /usr/bin/vendor_perl
  /usr/bin/core_perl
  /var/lib/snapd/snap/bin
  ~/software/ghostty/zig-out/bin

env_vars:
  MISE_SHELL=fish

settings:
  disable_backends  ["asdf"] ~/.config/mise/config.toml
  experimental      true     ~/.config/mise/config.toml
  pipx_uvx          true     ~/.config/mise/config.toml

No problems found
```

</details>
