### DISCUSSION TITLE
If multiple `depends_post` tasks are provided, mise hangs

### DISCUSSION THREAD

**Discussion by IxDay** [jdx/mise#4398] [Troubleshooting and bug reports]
As mentioned in the title, if I have the following `mise.toml` file:

```toml
[tasks.bar]
run = 'echo "bar"'

[tasks.foo]
run = 'echo "foo"'

[tasks."baz"]
run = 'echo "baz"'
depends_post = ["foo", "bar"]
```

If I run `mise run baz` it will hang forever. Remove one entry in `depends_post` and it will work once again.

**Comment by IxDay** [comment]
I narrowed down a bit the issue. 
It seems that the dependency resolver is not behaving well with `depends_post`. 
If I run `mise tasks deps` I loops infinitely. If I remove only one `depends_post` entry (let's say `bar`) the output of `mise tasks deps` is:
```
bar
baz
foo
├── bar
└── baz
```
Interesting isn't it? However, when I run this `baz` task I get:

```
[baz] $ echo "baz"
baz
[foo] $ echo "foo"
foo
```

There is a dependence between `foo` and `bar` out of nowhere, but it is not called when I invoke the tasks.
I guess it is also related to: https://github.com/jdx/mise/discussions/4222

**Comment by dboune** [comment]
Additional Related: https://github.com/jdx/mise/issues/4009#issuecomment-2600940911

The same issue occurs with depends.

**Version**: 2025.8.7 macos-arm64 (2025-08-06)
**OS**: macOS Sequoia 15.5
**Concurrency**: reproduces with `MISE_JOBS=1` and `>1`

## Expected
- Multiple `depends_post` entries should attach independent edges from the main task to each post task.

## Actual

Multiple `depends_post` creates a cycle and panics

```toml
[tasks.one]
run = "echo one"

[tasks.two]
run = "echo two"

[tasks.three]
run = "echo three"

[tasks.boom]
depends = ["one"]
depends_post = ["two", "three"]
```

Run:

```sh
❯ RUST_BACKTRACE=full mise boom
```

Output (excerpt):

```sh
[one] $ echo one
one
The application panicked (crashed).
Message:  Infinitive loop detected, all tasks are finished but the graph isn't empty two, three Graph {
    Ty: "Directed",
    node_count: 2,
    edge_count: 2,
    edges: (0, 1), (1, 0),
    ...
```

Shows a two-node cycle between `two` and `three`. Also reproduces with `MISE_JOBS=1`.

**Workaround A (aggregator):**

Does not panic, but **post step runs in parallel** with depends (not strictly “after” the main task):

```toml
[tasks.unboom]
depends = ["two", "three"]

[tasks.noboom]
depends = ["one"]
depends_post = ["unboom"]
```

**Workaround B (avoid depends_post):**

Functional today:
```toml
[tasks.two]
wait_for = ["one"]
run = "echo two"

[tasks.three]
wait_for = ["one"]
run = "echo three"

[tasks.ordered]
depends = ["one", "two", "three"]
```

If `depends_post` has different intended semantics, I'm happy to adjust. Otherwise, I see two scheduler issues:
1. Multiple `depends_post` introduce post↔post edges.
2. A `depends_post` task with its own `depends` can start before the`depends` task completes.
