### DISCUSSION TITLE
Specify multiple rust crate names when installing from git

### DISCUSSION THREAD

**Discussion by sripwoud** [jdx/mise#4441] [Ideas]
Re https://github.com/jdx/mise/issues/3143

The extra [`crate` cargo tool opt](https://mise.jdx.dev/dev-tools/backends/cargo.html#crate) works perfectly as long as I only need to install 1 crate from a git repo.
I'd like to be able to install multiple crates from a same git repo by passing an array of crate names.

eg
```toml
[tools]
"cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = ["cast", "forge"] }
```
Right now this is not supported and will throw an error.
```
mise ERROR TOML parse error at line 29, column 49
   |
29 | "cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = [
   |
 ```

I can't duplicate the tool key either
```toml
[tools]
"cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = "cast" }
"cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = "forge" }
```

```
Error loading settings file: TOML parse error at line 30, column 1
   |
30 | "cargo:https://github.com/foundry-rs/foundry" = { version = "tag:stable", crate = "cast" }
   | ^
duplicate key `cargo:https://github.com/foundry-rs/foundry` in table `tools`

```

Or if this is already supported:  how should I define the tools properly in my `mise.toml`?

**Comment by andrewthauer** [comment]
You might be able to accomplish this by defining an `alias` and then referencing it in `tools`. That said I haven't tried this specifically myself.

**Reply by jdx** [reply]
this is correct. What OP is trying to do here I don't think would ever be possible with how mise works.

**Reply by sripwoud** [reply]
I confirm the `alias` workaround does what I want :ok_hand: 

```toml
[alias]
anvil = "cargo:https://github.com/foundry-rs/foundry"
cast = "cargo:https://github.com/foundry-rs/foundry"

[tools]
anvil = { version = "tag:stable", crate = "anvil" }
cast = { version = "tag:stable", crate = "cast" }
```
