### DISCUSSION TITLE
File based tasks on Windows under Cygwin

### DISCUSSION THREAD

**Discussion by neongreen** [jdx/mise#4461] [Show and tell]
I spent some time figuring it out, so I'll record it here.

If you want to have a folder with `.sh` tasks, and have them work on WINDOWS under Cygwin, do this:

```toml
# $USERPROFILE/.config/mise/config.toml

[settings]
# Mise assumes only .bat .ps1 etc are executable on Windows, and `chmod +x` does nothing.
# This config setting marks `.sh` as executable.
windows_executable_extensions = ["sh"]

# Use `bash` instead of `cmd /c`
windows_default_file_shell_args = "bash"

# Respect the previous setting (otherwise it still uses cmd /c)
use_file_shell_for_executable_tasks = true
```

And here's I combine .sh files from multiple sources:

```toml
[task_config]
includes = [
  "/workspace/repo1/tasks/",
  "/workspace/repo2/tasks/",
  ...
]
```
