### DISCUSSION TITLE
Command alias possible?

### DISCUSSION THREAD

**Discussion by gmile** [jdx/mise#4462] [Q&A] [answered]
Is it possible to install a tool but have it available in path not by the name of downloaded file? For example, install a tool call `my-tool` for it to become available in the `$PATH` as `my-special-tool`?

Here's a concrete example. I have this `mise` config:

```toml
[tools]
docker-compose = "2.33.0"
```

After installing, there's no `docker-compose` available in `$PATH`. However, a tool with this name becomes available as:

```sh
docker-cli-plugin-docker-compose
```

I want to "remap" it or "alias" it to be available as `docker-compose`. Is it possible to do that?

P.S. mise installs `docker-compose` using `aqua` registry. FWIW, in `aqua`, there appears to be a way to specify what's known as a "[command alias](https://aquaproj.github.io/docs/guides/command-alias)". I am failing to find the way to configure a similar alias in mise.

**Comment by jdx** [comment, marked as answer]
you could probably do this in a postinstall hook

**Reply by gmile** [reply]
This appears to do the trick, and will do for now:

```toml
[tools]
docker-compose = "2.33.0"

[hooks]
postinstall = "cd $HOME/.local/share/mise/installs/docker-compose/$(mise current docker-compose) && ln -sf docker-cli-plugin-docker-compose docker-compose"

[settings]
experimental = true
```
Thank you!
