### DISCUSSION TITLE
How do we protect the age.txt keys when using Secrets?

### DISCUSSION THREAD

**Discussion by nickchomey** [jdx/mise#4486] [Q&A]
I just started using Mise's Secrets feature and it was easy to set up by following [the docs](https://mise.jdx.dev/environments/secrets.html).

My question is how do we protect the `age.txt` file, which seems to contain both the public and private key?

I see that `age` has a [passphrase option](https://github.com/FiloSottile/age?tab=readme-ov-file#passphrases). Is that something we can use with mise in an automated fashion?

Or, better yet, can we integrate it with a password manager, such as Bitwarden, so that we can avoid remembering yet another PW?

I assume the answer to all of the above is yes, but I hope someone might be able to point me in the right direction to figuring it out. Thanks!

**Comment by FracturedCode** [comment]
I ran into this today and thought of a couple ways to solve this problem. There are other options as provided by fnox. However, for reasons™️, I wanted to use the built-in age functionality, and wasn't comfortable with having my key visible in a file at all times.

I was not able to get the passphrase option to work out of the box with mise. Glancing at the code (note that I don't know much about mise or age atp), it appears that mise expects the identity file or input to be the unencrypted plaintext private key. In other words, it does not know to unwrap the encrypted identity file to get at the actual encryption key.

My solution was to bootstrap the `MISE_AGE_KEY` env var during the "enter" hook. This works because mise runs the hook before setting env vars.

## Option 1

You can invoke `age -d` on your passphrase-encrypted identity file and set the last line of that unencrypted output (your private key) as `MISE_AGE_KEY`. This will prompt you for your passphrase when you enter your project's directory.

Create your passphrase-protected age key:

```sh
age-keygen -pq | age -p > ./.config/key.age
```

Create the hook in your `mise.toml`:
```toml
[hooks.enter]
script = "$Env:MISE_AGE_KEY ??= ((age -d {{ config_root }}/.config/key.age) -Split '`n')[-1]"
shell = "pwsh"

[hooks.leave]
script = "$Env:MISE_AGE_KEY = $null"
shell = "pwsh"

[tools]
age = "latest"
```

You may have to adjust the hook based on your shell. Notice the null coalescing assignment operator, `??=`, (only set if null), which may be necessary for compatibility with a CI environment. A further optional enhancement is the leave hook to unset this env var.

## Option 2
You can prompt for the key to set the env var in the hook. This works well if you're putting your passphrase in a password manager anyway. Just generate your age key and plop it into your password manager instead of a passphrase.

```sh
age-keygen -pq  > key.age
# copy the private key to your password manager, then `rm key.age`
```

```toml
[hooks.enter]
script = "$Env:MISE_AGE_KEY ??= Read-Host 'Enter your age key' -AsSecureString"
shell = "pwsh"

[hooks.leave]
script = "$Env:MISE_AGE_KEY = $null"
shell = "pwsh"

```

This option may also be more secure. I do not know the inner workings of age, but I would guess the encryption used for encryption-by-passphrase is not a "post-quantum" algorithm. This would defeat the purpose of that `-pq` flag I used above. Of course, this point is irrelevant if you're not using `-pq`.
