### DISCUSSION TITLE
Reading `name` attribute from `Cargo.toml` as env var

### DISCUSSION THREAD

**Discussion by FalkWoldmann** [jdx/mise#4511] [Q&A] [answered]
Hi, 

I would like to expose the `name` defined in a `Cargo.toml` file as an environment variable, e.g. SERVICE, to avoid duplicating this value. Is there a idiomatic way to do this?

**Comment by hverlin** [comment, marked as answer]
Environment variables can be templates (see https://mise.jdx.dev/environments/#templates)

You can use the `exec` + a tool like https://github.com/TomWright/dasel to get the `name` from the `Cargo.toml` file.
(If you install `dasel` with `mise`, you might need to use [`tools = true`](https://mise.jdx.dev/environments/#lazy-eval))

Example:
```toml
[tools]
dasel = 'latest'

[env]
SERVICE = { value = "{{ exec(command='dasel -r toml -w plain -f Cargo.toml .package.name') }}", tools = true }
```
