### DISCUSSION TITLE
Can we merge mise.toml and mise.local.toml _before_ validation?

### DISCUSSION THREAD

**Discussion by reitzig** [jdx/mise#4514] [Ideas]
I want to commit something like this to my (public) project:

```toml
[tools]
lefthook = "1.10"
```

It's important that all contributers (roughly) agree on the version used.

They do not, however, have to use the same shell, so I would like to put _this_ in `mise.local.toml`:

```toml
[env]
LOCAL_FISH_COMPLETION_DIR = "{{config_root}}/.config/fish/completions"

[hooks]
postinstall = 'mkdir -p "$LOCAL_FISH_COMPLETION_DIR"'

[tools.lefthook]
postinstall = 'lefthook completion fish > "$LOCAL_FISH_COMPLETION_DIR/lefthook.fish"'
```

My expectation is that mise would merge the local config into the "main" config (knowing full well that merging dicts and arrays can be ... fun 😬). However:

```
 ❯ mise list
mise ERROR error parsing config file: ~/code/tools/my-project/.config/mise.local.toml
mise ERROR TOML parse error at line 7, column 1
  |
7 | [tools.uv]
  | ^^^^^^^^^^
missing version

mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
mise ERROR error parsing config file: ~/code/tools/my-project/.config/mise.local.toml
mise ERROR TOML parse error at line 7, column 1
  |
7 | [tools.uv]
  | ^^^^^^^^^^
missing version

mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Never mind the duplicate error ( ;) ), but: can we avoid this somehow?

**Comment by jdx** [comment]
this would not be realistic, no

**Comment by reitzig** [comment]
I found a semi-satisfying workaround by creating an "empty" task that I can call from the main config file, and implement it the local one:

`mise.toml`
```toml
[tools.lefthook]
version = "1.10"
postinstall = "mise run install-completion lefthook completion"

[tasks.install-completion]
run = '' # implement in mise.local.toml
```

`mise.local.toml`
```toml
[env]
LOCAL_FISH_COMPLETION_DIR = "{{config_root}}/.config/fish/completions"

[hooks]
postinstall = 'mkdir -p "$LOCAL_FISH_COMPLETION_DIR"'

[tasks.install-completion]
description = 'Install shell completions'
hide = true
run = '''
    {{arg(name="command")}} {{arg(name="completion_command", var=true)}} fish \
    > "$LOCAL_FISH_COMPLETION_DIR/{{arg(name="command")}}.fish"
'''
```
(see also [#3757](https://github.com/jdx/mise/discussions/3757#discussioncomment-12193706))

This works as long as all completion commands select the shell by a simple trailing argument; there's only one exception in my setup. Other devs should be able to create their own local config to install, say, zsh completions -- and if not, they get a few empty lines of output during installs.
