### DISCUSSION TITLE
Allow referencing other env vars that include an exec block

### DISCUSSION THREAD

**Discussion by FalkWoldmann** [jdx/mise#4520] [Ideas]
Hi, I would like to include env var that has an exec block in another env var, like 

```toml
[env]
SERVICE_NAME = { value = "{{ exec(command='dasel -r toml -w plain -f Cargo.toml .package.name') }}", tools = true }
SOME_REF="/default/{{env.SERVICE_NAME}}"
```

But this does not work: 
```
mise ERROR failed to parse template: '/default/{{env.SERVICE_NAME}}'
mise ERROR Failed to render '__tera_one_off'
mise ERROR Variable `env.SERVICE_NAME` not found in context while rendering '__tera_one_off'
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Setting some fixed value like SERVICE_NAME = "foo" works.

**Comment by JamBalaya56562** [comment]
The `exec` block is not what breaks this — `tools = true` is. Measured on **v2026.8.2**, keeping your `exec` and removing only `tools = true`:

```console
$ mise env
export SERVICE_NAME=hello
export SOME_REF=/default/hello
```

Three cases isolate it:

```console
tools = true alone                        -> export SERVICE_NAME=hello         ok
plain value references a tools = true one -> ERROR: SERVICE_NAME is not defined
tools = true references a tools = true    -> export SOME_REF=/default/hello    ok
```

**So your config works if you mark the referencing value too:**

```toml
[env]
SERVICE_NAME = { value = "{{ exec(command='dasel …') }}", tools = true }
SOME_REF = { value = "/default/{{ env.SERVICE_NAME }}", tools = true }
```

Keep `SOME_REF` declared after `SERVICE_NAME` — within a pass, a value is only visible to values declared later. That is true of plain values too, so it is not a `tools = true` quirk.

The reason is that `[env]` resolves in two passes. The first runs before tools exist and its input has `tools = true` directives filtered out *before* templating, so nothing in that pass can see them — no amount of reordering helps. The second runs after tools are installed and starts from the first pass's results, which is why two `tools = true` values can see each other, and why a `tools = true` value can reference a plain one but not the reverse.

That ordering is deliberate: `tools = true` exists for values that are not knowable until tools are installed, so exposing them earlier would be contradictory.
