### DISCUSSION TITLE
Tasks with multiple dots

### DISCUSSION THREAD

**Discussion by ruzickap** [jdx/mise#4526] [Troubleshooting and bug reports] [answered]
Hello I'm trying to create `mise.toml` which will contain the "dots" like:

```toml
[tasks."create:kind.k8s.local1"]
run = "echo ${MISE_TASK_NAME}"

[tasks."create:kind.k8s.local2"]
run = "echo ${MISE_TASK_NAME}"

[tasks."create:kind.k8s.local3"]
run = "echo ${MISE_TASK_NAME}"
```

Unfortunately mise is displaying only the part of the task:

```
❯ mise tasks
Name             Description
create:kind.k8s
create:kind.k8s
create:kind.k8s

❯ mise run 'create:*'
[create:kind.k8s] $ echo ${MISE_TASK_NAME}
[create:kind.k8s] $ echo ${MISE_TASK_NAME}
[create:kind.k8s] $ echo ${MISE_TASK_NAME}
[create:kind.k8s] create:kind.k8s.local3
[create:kind.k8s] create:kind.k8s.local1
[create:kind.k8s] Finished in 6.8ms
[create:kind.k8s] Finished in 6.8ms
[create:kind.k8s] create:kind.k8s.local2
[create:kind.k8s] Finished in 7.3ms
Finished in 8.1ms
``` 

Is this a bug or mise can not work with multiple dots?

Thank you...
