### DISCUSSION TITLE
Feature Request: OS specific tools

### DISCUSSION THREAD

**Discussion by ras0q** [jdx/mise#4556] [Ideas]
Thanks for developing a great plugin!
I own the dotfliles repository and use the common mise.toml across operating systems!
Some tools can only be installed or used on certain OS or architectures (e.g. aqua tools with  `supported_env` specified), and `mise install` does not always succeed on every OS.
Therefore, we propose the following option to specify the OSs which allow mise to install them.

```toml
[tools]
sometool = { version = "1.0.0", os = ["linux"] }
```
