### DISCUSSION TITLE
Alias `pip` to `uv pip`

### DISCUSSION THREAD

**Discussion by MVanderloo** [jdx/mise#4578] [Q&A] [answered]
Uv doesn't include pip in the default `uv venv` unless you specified, and for good reason. They recommend using `uv pip` as a wrapper meant to emulate pip's features. 

When I enter a directory with a uv.lock, mise will create and activate a venv automatically, which is amazing. But since pip is not included, typing `pip install ...` will use the global pip. Thus typing `pip install` may silently install things into my global environment.

My least intrusive idea is that when activating a .venv, mise could also create a shell alias `pip='uv pip'` so that everything is seamless. Is there a way to do this with hooks or something else?

**Comment by hverlin** [comment, marked as answer]
In case this helps:

You can either use the [`--seed` option](https://docs.astral.sh/uv/reference/cli/#uv-venv--seed) for virtualenv: https://mise.jdx.dev/lang/python.html#automatic-virtualenv-activation
```toml
[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ['--seed'] }
```

or as a setting: https://mise.jdx.dev/lang/python.html#python.uv_venv_create_args
```toml
[settings]
python.uv_venv_create_args = ['--seed']
```
