### DISCUSSION TITLE
Unexpected execution order of hooks

### DISCUSSION THREAD

**Discussion by sakakibara** [jdx/mise#4583] [Troubleshooting and bug reports]
When I have both enter and leave hooks defined in two directories, and if I cd from one to the other, hooks are executed in an unexpected order.

Say I have this mise.toml in directory A,
```toml
[hooks]
enter = "echo 'entering a'"
leave = "echo 'leaving a'"
```

and I have this mise.toml in directory B.
```toml
[hooks]
enter = "echo 'entering b'"
leave = "echo 'leaving b'"
```

When I `cd` from directory A to B, I expect the output to be
```text
leaving a
entering b
```

but the actual output is
```text
entering b
leaving a
```

this is problematic for example, when using hooks for switching github accounts using `gh auth switch --user '{username here}'` on both enter and leave.

Could the default execution order be changed? I think the expected output is more reasonable order.
