### DISCUSSION TITLE
Tasks - Sources relative to cwd, not config_root, per docs

### DISCUSSION THREAD

**Discussion by andrew-womeldorf** [jdx/mise#4596] [Troubleshooting and bug reports]
According to the [tasks docs for sources](https://github.com/jdx/mise/blob/v2025.3.2/docs/tasks/task-configuration.md#sources):

> This can be specified with relative paths to the config file and/or with glob patterns

## Configuration

```
$ tree
.
├── cmd
│   └── foo
│       └── main.go
└── mise.toml

2 directories, 2 files
```

```toml
[tasks.foo]
run = "echo hi"
sources = ["cmd/**/*.go"]
```

## Expected

From within any directory in the project, I can execute `mise watch -t foo`, and the `foo` task will trigger anytime I make a change to `cmd/foo/main.go`.

## Actual

1. Running `mise watch -t foo` **from the project root**, `foo` task is triggered when I modify `cmd/foo/main.go` :+1: : 
2. Running `mise watch -t foo` **from a nested directory, such as `cmd`**, `foo` task is not triggered when I modify `cmd/foo/main.go`. :-1: 

## Discussion

So the paths are relative to CWD, but not the config root.

Additionally, using absolute paths with `{{config_root}}` doesn't seem to work either:

```toml
[tasks.foo]
run = "echo hi"
sources = ["{{config_root}}/cmd/**/*.go"]
```

running with debug logging (`mise watch -t foo -v), `watchexec` is using the absolute path I expect, but the task is still not being triggered when the go file changes.
