### DISCUSSION TITLE
tips: Using `env`/`vars` values in `hooks`

### DISCUSSION THREAD

**Discussion by BayLee4** [jdx/mise#4601] [Ideas]
Currently the following does nothing, not even test is printed:
```toml
[vars]
myvar = "myvar_value"

[hooks]
enter = [
  "echo 'test'",
  "echo '{{vars.myvar}}'",
]
```
If the second echo is commented, then `test` is printed again. It would be great to be able to use `env`/`vars` values when using `hooks`.

**Comment by BayLee4** [comment]
Found a workaround using tasks:
```toml
[vars]
myvar = "myvar_value"

[tasks.test]
run = [
  "echo 'test'",
  "echo '{{vars.myvar}}'",
]

[hooks]
enter = 'mise run test'
```
Now works nicely! I guess it isn't supported by default for performance reasons
