### DISCUSSION TITLE
How to configure a default_packages_file that works only for a specific default venv?

### DISCUSSION THREAD

**Discussion by ssbarnea** [jdx/mise#4622] [Q&A]
I have a set of python packages that I want to be installed in my user level default venv file, but I do not want these to be installed when I create other venvs with mise.

```toml
# ~/.config/mise/config.toml
[env]
_.python.venv = { path = "~/.venv", create = true, uv_create_args = [
    "--system-site-packages",
    "--seed",
], python="3.13" }
```

```ini
# ~/.default-python-packages
black
pre-commit
ruff
```

While this works really cool are mise automatically creates and activates the my .venv it has the downside that it also does this for other python interpreter versions and I do not want this.

How can I configure mise to do this only for this environment in particular, without using any default packages for other ones.

**Comment by ssbarnea** [comment]
A good number of months later and I am still unable to find a way to force mise to auto-install python packages when auto-creating a virtualenv by keeping this inside the repository (isolated from user config).

Apparently `MISE_PYTHON_DEFAULT_PACKAGES_FILE` work only at user level and any of the options below **silently do not work**:

- Define `MISE_PYTHON_DEFAULT_PACKAGES_FILE` inside repo's `.env`
- Define MISE_PYTHON_DEFAULT_PACKAGES_FILE inside repos's `mise.toml` inside `[env]`
- Define `python_default_packages_file` inside repo's `mise.toml` inside `[settings]`

I also tried to use https://sourcegraph.com/search?q=language:toml+default_packages_file&patternType=keyword&sm=0 search to see if anyone used this feature and apparently the answer is not.

Keep in mind that I want to be able to define this inside my repo, without having to touch user level configuration or shell.

**Comment by Marukome0743** [comment]
`python.default_packages_file` applies when installing a Python runtime; it is not scoped to creation of one particular project virtual environment. That default-package mechanism has also been deprecated in favor of package-manager backends or hooks, so I would not recommend extending it for this use case.

A repository-local deps provider can keep both the package list and installation behavior inside the repository:

```toml
[env]
_.python.venv = { path = ".venv", create = true, python = "3.13" }

[deps.project-python-packages]
auto = true
sources = ["requirements.txt"]
outputs = [".venv/.mise-packages-installed"]
run = """
uv pip install --python "$VIRTUAL_ENV/bin/python" -r requirements.txt
touch "$VIRTUAL_ENV/.mise-packages-installed"
"""
```

With the packages listed in the repository’s `requirements.txt`, this provider runs before `mise run` and `mise x`, installs them only into that project’s activated virtual environment, and reruns when `requirements.txt` changes or the marker is missing. It does not affect other Python installations or virtual environments.

If the standard layout fits the project, the built-in `[deps.pip]` or `[deps.uv]` provider can also be used instead of a custom provider.

*AI-assisted — Tool: Codex; model: OpenAI/GPT-5; version: unavailable.*
