### DISCUSSION TITLE
add a lock version

### DISCUSSION THREAD

**Discussion by zeitlinger** [jdx/mise#4682] [Ideas]
A second (lock) version would be used for `mise install` (if available) - while `mise upgrade` continues to work as is.

For example:

```toml
[tools]
teleport-ent = { version = "latest", lock_version = "11.3.11"  } 
```

This would have the following benefit:

A) Renovate would be able to update the tool - because the version requirement is given
B) CI runs would also be predictable, because the version does not change

Currently you have to pick A or B
