### DISCUSSION TITLE
help with Config Environments

### DISCUSSION THREAD

**Discussion by timothysparg** [jdx/mise#4683] [General]
I'm running into an error with mise where it tries to evaluate an environment variable, but the environment variable should be overridden in a CI specific mise config.

I have the following in my `mise.toml` which works on my device.

```toml
[env.ACME_TOKEN]
value = """
    {{ exec( \
        command='dcli read \"dl://ACME_API_TOKEN/password\"',\
        cache_key='ACME_API_TOKEN',\
        cache_duration='1d'\
        ) | trim\
    }}"""
tools = true
redact = true
```

But on Github Actions it fails (correctly) because dcli is not installed.

I then created the following`mise.ci.toml` file which I hoped would override the value in `mise.toml`

```toml
[env]
ACME_API_TOKEN=""
```

The github actions looks as follows

```yml
      - name: Install Mise and dependencies
        env:
          MISE_ENV: ci
        run: |
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0x7413A06D
          curl https://mise.jdx.dev/install.sh.sig | gpg --decrypt > install.sh
          sh ./install.sh
          echo 'eval "$(mise activate bash)"' >> ~/.bashrc
      - name: lint
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          MISE_ENV: ci
        run: |
            # workaround for $GITHUB_PATH not being updated in the same _step_
            export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
            eval "$(mise activate bash --shims)"
            mise install

            echo "All changed files: ${ALL_CHANGED_FILES}"
            mise run lint "${ALL_CHANGED_FILES}"
```

And I get the following error

```
mise ERROR failed to parse template: '    {{ exec( command='dcli read "dl://ACME_API_TOKEN/password"',cache_key='ACME_API_TOKEN',cache_duration='1d') | trim}}'
mise ERROR Failed to render '__tera_one_off'
mise ERROR Function call 'exec' failed
mise ERROR exec command: command ["sh", "-c", "-o", "errexit", "dcli read \"dl://ACME_API_TOKEN/password\""] exited with code 127
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

what am I doing wrong?
