### DISCUSSION TITLE
How to install Rust toolchain components?

### DISCUSSION THREAD

**Discussion by ospfranco** [jdx/mise#4707] [Troubleshooting and bug reports]
I have the following `mise.toml`. I'm now forced to move into nightly Rust as I need to compile the std lib to correctly link to the target iOS version.

```toml
[tools]
rust = { version = "nightly", targets = "x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim,aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android" }
```

In order to compile the stdlib with my crate I use the command:

```
IPHONEOS_DEPLOYMENT_TARGET=14.0 cargo build -Zbuild-std=std --target aarch-apple-ios
```

However, an error pops up:

```text
error: "/Users/osp/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
```

Is there anyway to specify the toolchain component installation (`rustup component add rust-src --toolchain nightly-aarch64-apple-darwin`) in the `mise.toml`?
