### DISCUSSION TITLE
Managing dependencies like FreeTDS

### DISCUSSION THREAD

**Discussion by timothysparg** [jdx/mise#4708] [General]
Hi,
 
I'm trying to setup mise for a python project that depends on FreeTds.

There are a couple of issues that I'm running into:
- I don't see it available in Mise except via ubi ( which just gives the source )
- installation on linux vs macos is different. Mac seems to want you to do a `brew install` whereas linux seems to just work with a `pip install pymssql`

I was thinking of doing something along the lines

```shell
"ubi:FreeTDS/freetds" = { version = "1.4.12", extract_all = "true", post_install = """
echo run make install
"""" }
```

but this all starts to feel very messy as now you're having to start build your toolchain (which will probably start needing its own dependencies), and also be careful that you don't do an install that makes system changes.

I wonder if it makes sense to have some kind of prerequisites section for tools that mise knows that it doesn't want to / can't deal with, but expects to be available.

```TOML
[tools.prerequisites]
freetds = { version = "1.4.12", description = "can be installed with `brew install freetds`" }
op = { version = ">1.0.01", description = "1Password cli can be installed with `brew install op`" }
```
