### DISCUSSION TITLE
mise does not pick up `rust-toolchain.toml` file

### DISCUSSION THREAD

**Discussion by y-nk** [jdx/mise#4729] [Troubleshooting and bug reports] [answered]
**Context:** I'm using mise in a monorepo as toolchain installer and task runner.

The action step is this one (it's in a composite action).
I've been extra verbose to provide as much information as possible:

```yaml
    # manual toolchain install when workspace is passed (to cover installation of dependencies)
    - if: ${{ inputs.workspace }}
      working-directory: ${{ steps.resolve.outputs.path }}
      run: |
        pwd
        echo "${{ steps.resolve.outputs.path }}"
        cat .mise.toml
        cat rust-toolchain.toml
        MISE_VERBOSE=1 mise install
      shell: bash
```

Commented log:

![image](https://github.com/user-attachments/assets/c411b416-ae36-4f5f-9cad-f018966ec025)

We can see the `cat .mise.toml` and `cat rust-toolchain.toml` showing valid file (and nothing really exotic there). the mise log does not seem to pick the `rust-toolchain.toml` tho. meanwhile, locally, with exactly the same mise `2025.3.10`, it works like a charm:

![image](https://github.com/user-attachments/assets/70475948-65cb-42cf-870d-706652779e2f)

I'm confused of why the same mise binary would pick up the `rust-toolchain.toml` locally but not in CI and i don't have a clue where to start debugging this.
