### DISCUSSION TITLE
Potential Issue with Environment Handling and Lock File in mise

### DISCUSSION THREAD

**Discussion by acesyde** [jdx/mise#4755] [Troubleshooting and bug reports]
I'm encountering some behavior that I wanted to confirm is intended before opening a formal issue. Here are the steps I've followed:

## Steps to Reproduce

1) Create a new folder.
2) Add a `mise.toml` and a `mise.lock` empty files.
3) Enable experimental features

```sh
mise settings set experimental true -l
```

4) Install Python (example: version 3.13):

```sh
mise use python@3.13
```

At this point, the files contain the following

mise.toml

```toml
[settings]
experimental = true

[tools]
python = "3.13"
```

mise.lock

```toml
[tools.python]
version = "3.13.2"
backend = "core:python"
```

5) Set the environment variable:

```sh
export MISE_ENV=workspace
```

6) Install pre-commit:

```sh
mise use pre-commit@4.2
```

After this, a new file named `mise.workspace.toml` is created, containing:

```toml
[tools]
pre-commit = "4.2"
```

And the `mise.lock` doesn't seems to be affected

mise.lock

```toml
[tools.python]
version = "3.13.2"
backend = "core:python"
```

### Environment Installation Behavior

When installing pre-commit, I did not specify the -e/--env parameter. Despite this, the tool was added to the mise.workspace.toml file. Is this the expected behavior?

### Lock File Inconsistency

The mise.lock file does not contain the pre-commit package entry. Shouldn't it be listed here as well? Or is the mise.workspace.toml meant to override the lock file under these circumstances?

Would love to get your feedback on whether these behaviors are expected or if I'm perhaps missing a step or misunderstanding how mise is intended to handle this scenario.

Ping @jdx 

#4307 #4730
