### DISCUSSION TITLE
variable arguments don't get completed after the first one

### DISCUSSION THREAD

**Discussion by gturi** [jdx/mise#4774] [Troubleshooting and bug reports]
I found the following completion issue when using varags positional arguments. I was expecting `mise run list-user-completion` to always output "alice    bob      charlie" on tab press. However, after the first argument is completed, pressing tab again does not show the completion anymore.

```toml
[tasks.add-user]
description = "Add a users"
usage = '''
arg "<users>" var=#true default="unknown"
complete "users" run="mise run list-users-completion"
'''
run = 'echo {{arg(name="users")}}'

[tasks.list-users-completion]
description = "List users"
hide = true
quiet = true # this is mandatory to make completion work (makes the mise command just print "alice bob charlie")
run = 'echo -e "alice\nbob\ncharlie"'

# this is another unsuccessful attempt I made
[tasks.list-users-completion2]
description = "List users"
hide = true
quiet = true
usage = """
arg "[users]" var=#true
"""
run = 'echo -e "alice\nbob\ncharlie"'

```

```bash
mise run add-user # tab
alice    bob      charlie

mise run add-user alice # tab
# no output

mise run add-user alice bob # enter
# correctly outputs "alice bob"
```

mise doctor:
```bash
version: 2025.4.0 linux-x64 (2025-04-02)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Wed, 2 Apr 2025 00:11:44 +0000
  Rust Version: rustc 1.85.1 (4eb161250 2025-03-15)
  Profile: release

shell:
  zsh
  zsh 5.9 (x86_64-redhat-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  core:node@22.14.0
  ubi:jdx/usage@2.0.7

path:
  ~/.local/share/mise/installs/node/22.14.0/bin
  ~/.local/share/mise/installs/usage/2.0.7
  /run/user/1000/fnm_multishells/4330_1743581201209/bin
  ~/.local/share/fnm
  /run/user/1000/fnm_multishells/4327_1743581201173/bin
  ~/.local/share/fnm
  ~/.local/bin
  ~/bin
  ~/.cargo/bin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/local/sbin
  /usr/sbin
  /sbin
  /var/lib/snapd/snap/bin

env_vars:
  MISE_SHELL=zsh

settings:

No problems found
```
