### DISCUSSION TITLE
Add a required env variables

### DISCUSSION THREAD

**Discussion by brentmitchell25** [jdx/mise#4776] [Ideas]
It would be nice to have the ability to enforce certain environment variables for tasks. An example of how this could work:

```toml
[tasks.init]
env = { TOKEN = { required = true } }
```
