### DISCUSSION TITLE
lockfile should support task specific tools

### DISCUSSION THREAD

**Discussion by zeitlinger** [jdx/mise#4782] [Ideas]
such as 

```toml
[tasks.native-test]
tools.java = "graalvm-community-22.0.2"
```

The lock file contents should go to either a separate lockfile or a task specific section in the main lock file (which I think would be better).

Currently, the lockfile is updated when this task is run - which can create problems for CI builds.

**Comment by zeitlinger** [comment]
Maybe it's better to use environments for this feature instead - as they cleanly separate the tools.

Here's how the feature would work with environments:

mise.toml:

```toml

[tools]
java = "<your main java>"

[tasks.native-test]
depends = "build"
mise_env = "native"
run = "../../mvnw  test -PnativeTest"
dir = "integration-tests/it-spring-boot-smoke-test"
```

mise.native.toml:

```toml
[tools]
java = "graalvm-22.3.3+java17"
```
