### DISCUSSION TITLE
Force re-installation of Rust targets?

### DISCUSSION THREAD

**Discussion by ospfranco** [jdx/mise#4796] [General]
When I declare Rust targets like so:

```toml
[tools]
rust = { version = "nightly", components = "rust-src", targets = "x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim,aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android" }
```

If I do a `mise install` the first time, it seems like the targets are installed correctly. However, if I later modify the list and do a new `mise install` the new targets are not installed? Can something be done about this?
