### DISCUSSION TITLE
Adapting mise tasks to streamline downloading adhoc artifacts

### DISCUSSION THREAD

**Discussion by timothysparg** [jdx/mise#4801] [Ideas]
I've come across a couple of usecases where I need to download a binary that is not available via the tool backends.
Tasks give a pretty neat framework to download the binary and then setup tasks that just depend on the downloading task.

So conceptually the following

```TOML
[tasks.download-app]
description = "Downloads app"
sources = ['bin/acme']
outputs = ['bin/acme']

run = '''
#!/usr/bin/env bash
set -euxo pipefail

curl -L https://sourceforge.net/acme -o bin/acme
'''

[tasks.run-app]
description = "Build Spring Application Advisor mappings with custom repository and coordinates"
depends = ["setup-app-advisor"]
run = '/bin/acme --version'
```

But this will still download every time we the `run-app` task is executed, even though we have a `sources` and `outputs` value defined.
I think this is because mise checks the source timestamp against the output timestamp to see if it should execute the task again.

My workaround is fairly simple - I just add a `stamp` file that I touch after downloading a file and then set as the output.

```TOML
[tasks.download-app]
description = "Downloads app"
sources = ['bin/acme']
outputs = ['bin/acme.stamp']
run = '''
#!/usr/bin/env bash
set -euxo pipefail

curl -L https://sourceforge.net/acme -o bin/acme
touch 'bin/acme.stamp'
'''
```

But it would be quite nice if we could support this use case.

A solution could be that if no source is provided, but an output is provided then just the existence of the output file would be enough to skip the task.

```TOML
[tasks.download-app]
description = "Downloads app"
outputs = ['bin/acme']
run = '''
#!/usr/bin/env bash
set -euxo pipefail

curl -L https://sourceforge.net/acme -o bin/acme
'''
```

**Comment by JamBalaya56562** [comment]
Your diagnosis is close, but the gate is narrower than it looks — and there is a config that gets you the behaviour you want today, without the stamp file.

## What actually decides it

Skipping is gated on `sources` alone. `outputs` never enables it:

| `sources` | `outputs` | second run |
| --- | --- | --- |
| — | — | runs |
| **set** | — | **skipped** |
| — | **set** | runs |
| **set** | **set** | **skipped** |

`sources` on its own works because mise fills in `outputs = auto` when only `sources` is given. The reverse has no counterpart: `sources_are_fresh` returns false immediately when `sources` is empty, before any timestamp is looked at. So a task with only `outputs` is not "compared and found stale" — it is never compared at all. That matches how `sources` is documented: *"if this **and** `outputs` is defined, mise will skip executing tasks where…"*.

## The shape you want, today

Point `sources` and `outputs` at the same artifact and let equal mtimes count as fresh:

```toml
[settings.task]
source_freshness_equal_mtime_is_fresh = true

[tasks.download-app]
description = "Downloads app"
sources = ['bin/acme']
outputs = ['bin/acme']
run = 'curl -L https://sourceforge.net/acme -o bin/acme'
```

The file is compared against itself, so "it exists" is the whole test — exactly the rule you proposed. Measured on v2026.8.2, six independent trials, skipped on the second run in all six. It also behaves the way you would want at the edges:

```
run 1 (bin/acme absent)   -> $ curl -L …
run 2                     -> sources up-to-date, skipping
delete bin/acme, run 3    -> $ curl -L …            (artifact restored)
edit mise.toml, run 4     -> $ curl -L …
change the run command    -> $ curl -L …            (artifact rebuilt)
```

Deleting the artifact re-downloads it, and editing the task definition re-downloads it, because the config file is an implicit source.

The one caveat: `source_freshness_equal_mtime_is_fresh` (`MISE_TASK_SOURCE_FRESHNESS_EQUAL_MTIME_IS_FRESH`) is project-wide, not per-task, so it relaxes the comparison from `<` to `<=` for every task in that config. If that is not acceptable, this works with no settings change at all:

```toml
[tasks.download-app]
sources = ['mise.toml']
outputs = ['bin/acme']
run = 'curl -L https://sourceforge.net/acme -o bin/acme'
```

Same measured behaviour — skips on re-run, re-downloads when `bin/acme` is deleted — at the cost of re-downloading whenever `mise.toml` changes for any reason.

## About the stamp file

Worth knowing that it has a race in it. The comparison is strict (`newest source < oldest output`), so the stamp has to land on a *later* timestamp tick than the artifact, not the same one. Eight identical trials on Windows:

```
trial 1: ran again   stamp - artifact =  2.0099 ms
trial 2: ran again                    =  0.0000 ms
trial 3: ran again                    =  0.0000 ms
trial 4: skipped                      =  3.5733 ms
trial 5: ran again                    =  0.0000 ms
trial 6: ran again                    =  0.0000 ms
trial 7: ran again                    =  0.0000 ms
trial 8: skipped                      =  2.0009 ms
```

Six of eight landed on the same filesystem tick and re-downloaded. NTFS timestamp granularity is coarse, so this is worse on Windows than it will be for you on a filesystem with finer mtime resolution — but the race is in the comparison, not in the platform, and `source_freshness_equal_mtime_is_fresh = true` removes it for the stamp version too.

One dead end worth saving you the time on: `[tasks.<name>.cache]` is not a route to this. It is gated behind `experimental = true`, and with that set it still refuses — `task download-app cache requires at least one source`.

---

Measured on v2026.8.2 windows-x64 with an isolated config and data directory. I have not tried the same on Linux; the timing numbers in particular will differ there, though the rules they demonstrate are platform-independent.
