### DISCUSSION TITLE
Is `mise fmt` meant to be running in CI?

### DISCUSSION THREAD

**Discussion by dmarcoux** [jdx/mise#4841] [Q&A] [answered]
Hey,

first of all, thank you for mise. It's been awesome in setting up my development environment.

I've recently discovered `mise fmt` and I wonder if it's meant to be running in CI? There doesn't seem to be a way for `mise fmt` to error out if `mise.toml` isn't correctly formatted. In other formatting tools, there's often a flag like `--check` / `--verify`.

I had something like this in mind:
```yaml
name: Ensure mise.toml is formatted

on:
  push:
    paths:
      - 'mise.toml'

jobs:
  format-mise:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup mise
        uses: jdx/mise-action@v2.1.11
        with:
          version: latest # At least for now, we don't pin mise's version locally and in the CI.
          install: false # Do not run `mise install`, we only need mise.
      - name: Ensure mise.toml is formatted
        run: mise fmt --check
```
