### DISCUSSION TITLE
How to escape argument syntax in tasks

### DISCUSSION THREAD

**Discussion by kbarendrecht** [jdx/mise#4851] [Q&A] [answered]
Example task:
```
[tasks.'docker:list']
description = 'List all containers'
run = 'docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.RunningFor}}\t{{.Image}}"'
```

will result in
```
[docker:list] ERROR
   0: docker ps -a --format table {{.ID}}       {{.Names}}      {{.Status}}     {{.RunningFor}} {{.Image}}
   1: Failed to parse '__tera_one_off'
   2:  --> 1:31
        |
      1 | docker ps -a --format table {{.ID}}   {{.Names}}      {{.Status}}     {{.RunningFor}} {{.Image}}
        |                               ^---
        |
        = expected a value that can be negated or an array of values

Location:
   src/task/task_script_parser.rs:282
```
What I've tried:
- Using triple quotations marks
- Swap the quotation marks
- escaping curly braces with \ works, but that messes up the docker command as well.

Is there a way to escape mise's argument syntax while maintaining a valid `docker ps` command?

**Comment by risu729** [comment, marked as answer]
[raw](https://keats.github.io/tera/docs/#raw) worked!

```toml
[tasks.'docker:list']
description = 'List all containers'
run = 'docker ps -a --format "{% raw %}table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.RunningFor}}\t{{.Image}}{% endraw %}"'
```
