### DISCUSSION TITLE
Unable to use Cmake: “CMake.app” is damaged and can’t be opened. You should move it to the Trash.

### DISCUSSION THREAD

**Discussion by ivancuric** [jdx/mise#4866] [Troubleshooting and bug reports]
Installing cmake with mise (v3.31.1) results in this error.

I've tried running the following on both the `cmake` bin and the `Cmake.app`:

- `xattr -cr`
- `codesign --force --deep -s`
- `xattr -d com.apple.quarantine`

```sh
installs/cmake/3.31.1 
➜ codesign --force --deep --sign - CMake.app
CMake.app: replacing existing signature
CMake.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/ivan/.local/share/mise/installs/cmake/3.31.1/CMake.app/Contents/Frameworks/QtWidgets.framework
```

Nothing helps, and I keep getting this error:
![image](https://github.com/user-attachments/assets/ae4846eb-9f16-40dd-acde-9b981c96675b)

The only way to fix the mise installation is to take the install url (https://github.com/Kitware/CMake/releases/download/v4.0.1/cmake-4.0.1-macos-universal.tar.gz), and replace the Mise.app in the mise installs directory with the one from the archive.

Using CMake from homebrew also works fine.

**Comment by smogg** [comment]
samesies ^^^

**Comment by winghouchan** [comment]
Doing the following resolved the issue for me:

1. Open **System Preferences**.
2. Navigate to **Privacy & Security**.
3. Under **Security**, there is a callout saying something like:
    > "CMake" was blocked from use because [...]
4. Press <kbd>Open anyway</kbd>.

**Reply by TroutZhang** [reply]
I did the same, until https://github.com/asdf-community/asdf-cmake/pull/7

**Comment by ivancuric** [comment]
This is far from an acceptable solution for a tool manager

**Comment by tristancartony** [comment]
I'm also hitting this and can't change the security option on our CI pipeline, so it's a non-starter.

I have found that vfox:cmake works as expected, but vfox:cmake on Linux arm does not seem to work.

**Reply by tristancartony** [reply]
This is the error I get when trying to use vfox:cmake on Linux arm:

```
  mise cmake@3.28.4                  install
  mise ERROR failed to install vfox:cmake@3.28.4
  mise ERROR error converting Lua table to PreInstall (no version returned from vfox plugin)
  mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```
So, on a Mac, asdf:cmake doesn't work because of the issue described above, but vfox:cmake works. vfox:cmake also works on Linux amd64 but it fails with the above error on linux arm.

**Reply by ivancuric** [reply]
Is there an easy way to setup which tool to use in which environment?

I can only find the option to enable a certain tool on a certain platform, not taking arch into account:
https://mise.jdx.dev/dev-tools/#os-specific-tools

```toml
[tools]
# Only install on Linux and macOS
ripgrep = { version = "latest", os = ["linux", "macos"] }

# Only install on Windows
"npm:windows-terminal" = { version = "latest", os = ["windows"] }

# Works with other options
"cargo:usage-cli" = { 
    version = "latest", 
    os = ["linux", "macos"],
    install_env = { RUST_BACKTRACE = "1" }
}
```

Also, `vfox:cmake` hasn't been maintained for a long time and the versions are not being updated. It's stuck on 4.0.1.
