### DISCUSSION TITLE
True replacement for `make`

### DISCUSSION THREAD

**Discussion by sermuns** [jdx/mise#4867] [Q&A]
Can `mise` fully replace `make`:s incremental building?

I'm using `make` to compile PDFs with `typst`.

Each source `.typ` file directly corresponds to a compiled `.pdf` file.

**Project structure:**

```
.
├── Makefile
├── sm_2025-04-07.typ
├── sm_2025-04-08.typ
└── sm_2025-04-09.typ
```

**`Makefile`:**
```make
TYP_FILES := $(wildcard *.typ)
PDF_FILES := $(TYP_FILES:%.typ=%.pdf)

all: $(PDF_FILES)

%.pdf: ./%.typ
	@echo "Compiling $< to $@"
	@typst compile $< $@

clean:
	rm -f $(PDF_FILES)

.PHONY: all clean
```

With this structure I can easily compile a single PDF, or all, and prevent unneccessary compilation of those that have already been compiled.

Here's a working, but hardcoded `mise.toml`:
```toml
[tasks.compile]
run = 'typst compile sm_2025-04-07.typ'
sources = [ 'sm_2025-04-07.typ' ]
outputs = { auto = true }
```

Can `mise` do this? Thankful for any input!

**Comment by adamdicarlo0** [comment]
I'm pretty sure you can use wildcards in (at least) `sources`, so `*.typ` should be fine. I'd look at the templating options as well, as you might be able to get the expanded form of `sources` into your `run` command the way you were doing with `make`.

**Reply by fedelibre** [reply]
I'm also interested in this for a similar scenario (PDF music sheets built by lilypond text files).

@adamdicarlo0 Could you show an example? I've searched the docs, but I could not figure out how to do what can be easily done in Make. I started with mise today.

If wildcards don't work fine, can I use `find` to make a list of the source files and save it in a variable mise can then use?

**Reply by adamdicarlo0** [reply]
I've used wildcards in sources successfully, but I'm not sure about getting the list of source files. It looks like it's not available, unfortunately, going by https://mise.jdx.dev/templates.html#mise-template-features.

You might want to ask about it in the Discord, see if somebody has an easy workaround, or if they might consider adding the feature. I haven't touched my mise configs in a while now, so I'm not sure how to get the output of `find` into a mise var, but you could make the `find` part of the command that gets run (or run a script, and put it in the script).

**Comment by izissise** [comment]
I'm also interested in this.

I've been able to make this work successfully using glob patterns in sources, but I've noticed that mise will always rerun the tasks if no outputs are specified.

It would be great if mise could automatically detect that there is "nothing to be done" if the previous run was successful and the sources haven't changed (via checksum/hash), even without explicit output files defined.

To easily implement this mise could create a file in a cache directory when a tasks is successful.

**Comment by iamkroot** [comment]
See https://mise.jdx.dev/templates.html#task-specific-functions - we already have `task_source_files` available

```toml
# Access resolved source files in task scripts
[tasks.example]
sources = ["src/**/*.ts", "package.json"]
run = '''
{% for file in task_source_files() %}
  echo "Processing: {{ file }}"
{% endfor %}
'''
```
