### DISCUSSION TITLE
Hooks are not executed outside project level

### DISCUSSION THREAD

**Discussion by sidkang** [jdx/mise#4875] [Troubleshooting and bug reports]
### Describe the bug
I defined some hooks and they are not executed, tested on my 2 Macs.

1. In a project folder contains a `mise.toml`(hooks defined in the global config file) and its subdirectory, it works as expected.
2. Outside project folders, the hooks never work.

### To Reproduce
Add this to `~/.config/mise/config.toml`:

```toml
# ~/.config/mise/config.toml
[hooks]
enter = 'echo "ENTER"'
leave = 'echo "LEAVE"'
cd = 'echo "CD"'
preinstall = 'echo "PREINSTALL"'
postinstall = 'echo "POSTINSTALL"'

[settings]
experimental = true
```

### Expected Behavior
echos show outputs in terminal.

### `mise doctor` output
```
version: 2025.4.5 macos-arm64 (2025-04-18)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, SELF_UPDATE
  Built: Fri, 18 Apr 2025 01:31:18 +0000
  Rust Version: rustc 1.86.0 (05f9846f8 2025-03-31) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 4.0.1

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:

path:
  ~/.config/cargo/bin
  ~/.config/pyenv/shims
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /opt/homebrew/opt/mise/bin
  /Applications/quarto/bin
  /Applications/Espanso.app/Contents/MacOS
  /usr/local/bin
  /System/Cryptexes/App/usr/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  $PATH

env_vars:
  MISE_SHELL=fish

settings:
  experimental  true ~/.config/mise/config.toml

No problems found
```

**Comment by ActionScripted** [comment]
Ran in to this myself because prefer to use mise for global tool management. Wanted a postinstall hook that would run a script that installs packages for various languages after the upgrade. I am tired of virtual envs after like 15 years of them so I keep global stuff `@latest` and install packages globally after. Anyways...

What I've landed on for now is a global task. So instead of `mise upgrade` with a `postinstall` it's a `mise upgrade-global` with the same effect. Here's my config:

```toml
[tools]
python = "latest"
node = "latest"

[settings]
experimental = true
ignored_config_paths = [
  "~/.dotfiles/dotfiles/",
  "~/.dotfiles/dotfiles/.config/mise/",
]
idiomatic_version_file_enable_tools = ["node", "python"]

[hooks]
# NOTE: this doesn't work for global/non-project stuff...
postinstall = "~/.config/mise/hooks/postinstall.sh"

[tasks.upgrade-global]
description = "Upgrade tools and reinstall global packages"
run = """
mise upgrade
MISE_TOOL_NAME=python ~/.config/mise/hooks/postinstall.sh
MISE_TOOL_NAME=node ~/.config/mise/hooks/postinstall.sh
"""
```

Maybe you can lean on tasks instead of hooks for global/non-project stuff?
