### DISCUSSION TITLE
`mise doctor` does not honor the `redact` flag for `MISE_GITHUB_ENTERPRISE_TOKEN`

### DISCUSSION THREAD

**Discussion by efussi** [jdx/mise#4880] [Troubleshooting and bug reports] [answered]
With this in my **~/.config/mise/config.toml**
```toml
[env]                                                                                                                                                                                                                                                         
# see https://github.com/jdx/mise/issues/2910                                                                                                                                                                                                                 
MISE_GITHUB_TOKEN = { value = "{{env.GH_TOKEN}}", redact = true }                                                                                                                                                                                             
MISE_GITHUB_ENTERPRISE_TOKEN = { value = "{{env.GHE_TOKEN}}", redact = true }                                                                                                                                                                                 
```
running `mise doctor` shows this:
```
: 
env_vars:
  MISE_GITHUB_TOKEN=REDACTED
  MISE_GITHUB_ENTERPRISE_TOKEN=ghp_SJ............................
```

Looking at https://github.com/jdx/mise/blob/020f0d18fec1cc83ffc29ab5aaf5b91e08f9a01f/src/cli/doctor/mod.rs#L416 it seems the list of redacted variables is hard-coded and the ones newly introduced in https://github.com/jdx/mise/pull/4765 yet need to be added.

How is this meant to work? Is it necessary to add `redact = true` to the well-known `MISE_*_TOKEN` variables, or are they automatically considered redacted?

I am using version: 2025.4.5.
