### DISCUSSION TITLE
[vars] don't work in task tools

### DISCUSSION THREAD

**Discussion by neongreen** [jdx/mise#4885] [Troubleshooting and bug reports]
```toml
[vars]
uv_version = "0.5.1"

[tasks.test]
description = "test"
tools.uv = "{{vars.uv_version}}"
run = "uv --version"
```

```bash
$ mise run test

mise ERROR failed to install aqua:astral-sh/uv@{{vars.uv_version}}
mise ERROR HTTP status client error (404 Not Found) for url (https://api.github.com/repos/astral-sh/uv/releases/tags/%7B%7Bvars.uv_version%7D%7D)
mise ERROR HTTP status client error (404 Not Found) for url (https://api.github.com/repos/astral-sh/uv/releases/tags/v%7B%7Bvars.uv_version%7D%7D)
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```
