### DISCUSSION TITLE
Haxe and backends

### DISCUSSION THREAD

**Discussion by pavelzherdin** [jdx/mise#4982] [Troubleshooting and bug reports]
Two questions:
1. haxe backend was changed from asdf to ubi in https://github.com/jdx/mise/pull/4716

I only spotted when haxe stop working after a `mise install` on a clean machine. The one whre I originally installed haxe from asdf just kept working. Is there a recommended approach to dealing with this? Did I miss something in the docs?

2. Installing haxe with mise is weird.

Here's a minimal config that somewhat worked for me. So, the second question: is there a better way to do this?
Should haxe and neko have `extract_all=true` by default in the registry?

```toml
[env]
# Optional. HAXELIB is set to config root to allow project specific haxe libraries.
# Works sort of like a venv.
HAXELIB_PATH = "{{ config_root }}/.haxelib"

# Haxe needs some hand-holding to find neko and libneko.
# This elaborate template is here to account for missing LD_LIBRARY_PATH env variable.
# Do not want to leave it with a trailing :.
# You might get an error until neko is installed, because env is evaluated before tools in mise.
LD_LIBRARY_PATH = """
{%- set neko_path = exec(command='mise where neko') | trim -%}
{%- set existing_ld_path = get_env(name='LD_LIBRARY_PATH', default='') | trim -%}
{%- if existing_ld_path == "" -%}
{{ neko_path }}
{%- else -%}
{{ neko_path }}:{{ existing_ld_path }}
{%- endif -%}
"""

[tools]
# Default mise backend for haxe is now ubi, which only installs the executable matching the tool
# name by default. But for both haxe and neko we need everything, libs, haxelib, std and so on...
# So using extract_all. Also note how neko is a special snowflake and uses dashes for versioning.
haxe = { version = "4.3.6", extract_all = "true" }
neko = { version = "2-4-1", extract_all = "true" }

[tasks]
# This is optional, but nice to have.
[tasks.haxelib-setup]
description = "Install required haxe libraries"
# TODO: might make sense to define outputs here
run = [
  "mkdir -p $HAXELIB_PATH",
  "haxelib install threejs 91.0.1",
]

```
