### DISCUSSION TITLE
tools with plug-ins and the shared install directory

### DISCUSSION THREAD

**Discussion by rafalkrupinski** [jdx/mise#5034] [Troubleshooting and bug reports]
I use sphinx, a python documentation generator. Since it doesn't have to be installed together with the project, I use mise to manage it.
I install it with a bunch of plug-ins via `uvx_args` which are project-specific but mise installs it in a user-shared directory -  `~/.local/share/mise/installs/pipx-sphinx`.
So when two or more projects use the same tool but with different plug-in sets, they're in conflict.

Should hash of any extra args be included in the tool installation path, or is there an option to have a separate install directory for project?

**Comment by rafalkrupinski** [comment]
yes, no, off-topic?

**Comment by rafalkrupinski** [comment]
Same happens when using shims even without any installation options:
Adding simple node@latest will add in common directory. If another project needs node@22 there's conflict.
@jdx

**Reply by risu729** [reply]
I don't understand that situation. Could you provide more details and the `mise doctor` output?
Regarding the original question, I don't think we have options to do so.

**Reply by rafalkrupinski** [reply]
> I don't understand that situation. Could you provide more details and the mise doctor output?

Ah, just found that shims install all tools as a symlink to mise. Please disregard this comment.

The original problem remains

**Comment by risu729** [comment]
jdx told me that [`alias`](https://mise.jdx.dev/dev-tools/aliases.html) works for this use case.

This is another example, but you should be able to do the same for `uvx_args`.
```toml
[alias]
pass = "ubi:docker/docker-credential-helpers[matching=pass,rename_exe=docker-credential-pass]"
secretservice = "ubi:docker/docker-credential-helpers[matching=secretservice,rename_exe=docker-credential-secretservice]"

[tools.pass]
version = "0.9.3"

[tools.secretservice]
version = "0.9.3"
```
