### DISCUSSION TITLE
Running "isolated" is harder than it could be

### DISCUSSION THREAD

**Discussion by rsyring** [jdx/mise#5199] [Ideas]
I want to use mise in CI on Cloudflare Pages to build some documentation using mkdocs, a Python tool.  

One of my "rules" when building CI is to set things up so that the majority of the functionality that is run in CI can be duplicated locally.  My efforts to do this with mise was harder than I expected due to my desire to isolate a local mise run from my user's mise config and installs so that when I ran the build locally it was exactly how the CF Pages worker would run it.

I was eventually able to get it to work, here is what I did:

```toml
[env]
_.python.venv.create = true

[tools]
python = '3.12'

[tasks.site-build]
description = "build site"
run = 'mkdocs build --clean'

[tasks.prep-deploy-mise]
description = "Update mise used by CF Pages build"
run = 'mise generate bootstrap --localize --write deploy/mise'

[tasks.cf-pages-build]
# To trully simulate the worker environment, run this with the deployed mise instead of your
# system mise.  I.e.

# ❯ deploy/mise cf-pages-build
description = "Builds the project on CF Pages workers"
env = { MISE_ENV = 'deploy' }
run = [
    # Ensure this task is being ran with `deployed/mise` and not the system mise.  It works b/c
    # deploy/mise is a shim and the real bin being executed is named like .mise/mise-2025.5.13.
    'case "$(ps -o comm= -p $PPID)" in mise-*) ;; *) echo "\n\n--> Use ./deployed/mise to run instead\n\n"; exit 1 ;; esac',

    # Delete everything but the mise bins since the mise shim will have downloaded it already in order
    # to run this task and, if we delete it here, the shim will have to download it again.  This
    # Doesn't matter in CI but does matter when ran locally to simulate the CI environment.
    "find .mise -mindepth 1 -not -name 'mise-*' -delete",

    # This also won't matter in CI but for a local run isolates it from the host user's config.
    'deploy/mise trust --ignore ~/.config/mise/config.toml',

    # Worker build
    'deploy/mise trust mise.toml',
    'deploy/mise install python ubi:astral-sh/uv',
    'deploy/mise doctor || true',
    'deploy/mise env | printenv PATH | tr ":" "\n"',
    'deploy/mise exec -- uv sync',
    'deploy/mise site-build',
]
```

## Difficulties / Feature Request

Similar to the discussion in #5136, I struggled to get mise to only use the project's `mise.toml`.  I looked for cli and environment options first and tried a few of them but couldn't get the isolation I wanted.  
  - The bootstrap script is a fantastic feature BTW!  Very helpful once I found it and figured out what it could do.
  - Using the trust system with the localized bootstrap script to isolate the user's config ended up being a pretty clean solution but a non-obvious one.

**Feature request**: make a more obvious way to tell mise to isolate itself from the system and to the project.  I'm not sure the best way to do this, but a one-stop option like `--isolate` (uses `.mise` directory) or `--isolate-dir` which acts the same but let's you choose the path to put the isolation in would make sense to me.  Obviously, having the corresponding ENV variables for those CLI options would be helpful.

## Cookbook

Is this worth putting in the Python cookbook docs to demonstrate how to bootstrap mise and uv in a CI environment?  If so, I'll create a PR for your review.

---

jdx: BTW, I really appreciate mise.  It has revolutionized so much of how we do local dev and CI setup.  The fear of including different tools in the dev environment due to making the DX more complicated has all but disappeared.  And being able to do it all locally instead of having to rely on a container based solution is so much faster and cleaner.  Thanks so much for the TON of effort you have put into this!
