### DISCUSSION TITLE
Tasks: post-dependency that always runs

### DISCUSSION THREAD

**Discussion by reitzig** [jdx/mise#5206] [Ideas]
Currently, `depends_post` only run if the tasks they are declared on _succeed_.

I would like a way to run some cleanup in any case (i.e. also on failure).

_Alternatives_: With`run` tasks, I could undo `set -e`, or complicate the script to implement `try-finally`.

**Comment by roele** [comment]
This sounds like something that might relate to #3525

**Reply by reitzig** [reply]
Yup. The discussion there seems to focus on running stuff _only_ after failure.

A shared abstraction could be adding a "long" form to `depends_post` that allows to set when the post-task should run (always, on-success, on-failure).

For example:

```toml
[tasks.push]
depends = ['build']
run = """
#!/usr/bin/env bash
docker login "${DOCKER_REGISTRY}"
docker tag "my-image:$(date -Idate)" "${DOCKER_REGISTRY}/my-image:$(date -Idate)"
docker push ""${DOCKER_REGISTRY}/my-image:$(date -Idate)""
"""
depends_post = [
  { name = 'push-cleanup', when = 'always' }
]

[tasks.push-cleanup]
hide = true
run = """
#!/usr/bin/env bash
docker image rm "${DOCKER_REGISTRY}/my-image:$(date -Idate)"
docker logout
"""
```

FWIW, in this example it would also be useful if `push` could set/forward to `push-cleanup`, but that's another discussion.
