### DISCUSSION TITLE
Different task output (and input?) based on flags

### DISCUSSION THREAD

**Discussion by calebhearth** [jdx/mise#5229] [Q&A]
This is possibly related to https://github.com/jdx/mise/discussions/4237 and https://github.com/jdx/mise/issues/4238, but it's not exactly the same.

I'm in a situation where I've defined several TOML tasks in the general pattern of `tasks.build-*-debug` and `tasks.build-*-release` because the run script and the outputs both need to vary based on what configuration I'm building a project in.

Generally, they look something like:

```toml
[tasks.build-x-debug]
outputs = ['build/Debug/X.framework/**/*']
run = [
  'xcodebuild build -project x.xcodeproj -scheme X-package -configuration Debug',
  'touch --no-create -m "build/Debug/X.framework/X"',
]
sources = ["..."]

[tasks.build-x-release]
outputs = ['build/Release/X.framework/**/*']
run = [
  'xcodebuild build -project x.xcodeproj -scheme X-package -configuration Release',
  'touch --no-create -m "build/Release/X.framework/X"',
]
sources = ["..."]

# repeat for y, z, etc.
```

I made an attempt to handle this by using Tera templates to specify a `--release` flag along the lines of:

```tera
{% if flag(name="release") == "test" %}Release{% else %}Debug{% endif %}
```

...but besides specifying the flag multiple times in the help competions, the `flag` function appears to only be available in `tasks.*.run` scripts, so I can't use it in outputs. I also tried setting an env var as a run step but the value wasn't exported to the subsequent scripts (solvable with multiline) or read in the `outputs` value (not so much):

```toml
[tasks.build-x]
  description = "Build X.framework"
  outputs = ['build/$TARGET/X.framework/**/*']
  run = [
    'export TARGET={% if flag(name="release") == "test" %}Release{% else %}Debug{% endif %}',
    'xcodebuild build -project x.xcodeproj -scheme X-package -configuration "$TARGET"',
    'touch --no-create -m "build/$TARGET/X.framework/X"',
  ]
  sources = ["..."]
```

Is varying the outputs based on build step something that Mise supports now, just not the way I'm holding it? If not, is this the kind of functionality that might be introduced?

**Comment by reitzig** [comment]
Seconded.

My use case:

```toml
[tasks.validate-json]
depends = ['_some-prep']
sources = ['?']
outputs = { auto = true }
run = """
  jv --assert-format '{{arg(name="schema")}}' '{{arg(name="instance")}}'
"""
```

I would like `mise watch validate-json` to re-run the task if either of the given input files change.

Looks like evaluating templates in the items of `sources` (and `outputs`, for the OP) might be an approach here:

```toml
sources = ['{{arg(name="schema")}}', '{{arg(name="instance")}}']
```
