### DISCUSSION TITLE
Gracefully handle absent sops private key

### DISCUSSION THREAD

**Discussion by pepicrft** [jdx/mise#5280] [Ideas]
We are using Mise's functionality to unencrypt env files on the fly using sops in open source repositories:

```toml
[env]
_.file = ".env.json"
```

The feature works fine when the key is present, but the Mise's shell hook fails when absent. For open-source repositories where contributors won't have the key, it's not enjoyable. What do you think if Mise adds a new setting to make that optional? Here's an example of what the API could look like:

```toml
[settings]
sops.optional = true
```
