### DISCUSSION TITLE
Running a task for each of many versions of the same tool?

### DISCUSSION THREAD

**Discussion by AndydeCleyre** [jdx/mise#5281] [Q&A]
What's the proper workflow flow for, say, specifying a bunch of Python versions, and having a task that runs the project's tests for each one of them?

The following is an invalid templating attempt and does not work, but should help convey the idea. Even if it did work, I'm sure it's clunkier than a (hopefully) recommended pattern.

```toml
[tools]
python = ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]

[env._.python]
venv = { path = ".venv", create = true }

# ...

[tasks.test]
description = "Run all tests"
depends = ["install"]
run = [
  "uv -q pip install -U coverage",
  "coverage run -p -m pytest",
]

{% for pyver in ["3.13","3.12","3.11","3.10","3.9","3.8","3.7",] %}
[tasks.test-{{pyver}}]
description = "Run all tests, for Python {{pyver}}"
tools.python = "{{pyver}}"
run = [
  "mise run test",
]
hide = true
{% endfor %}

[tasks.test-all-pythons]
description = "Run all tests for each supported Python release"
run = """
  for pyver in 3.13 3.12 3.11 3.10 3.9 3.8 3.7; do
    mise run test-$pyver
  done
"""
```

**Comment by risu729** [comment]
`mise use` supports [`--tool`](https://mise.jdx.dev/cli/run.html#t-tool-tool-version) flag, so you can write like this:

```toml
[tasks.test-all-pythons]
description = "Run all tests for each supported Python release"
run = """
  for pyver in 3.13 3.12 3.11 3.10 3.9 3.8 3.7; do
    mise run --tool "python@$pyver" test
  done
"""
```

However, dynamic task names are not supported as far as I know.

**Reply by AndydeCleyre** [reply]
Great, thanks!

**Reply by AndydeCleyre** [reply]
@risu729 

So I have the following `mise.toml`, but when running the `test-all-pythons` task, they all run under Python 3.13.3. Maybe because it's using the same venv without recreating it? How should I be approaching this instead? It's the same if I replace `coverage run -p -m ward` with `python -m ward`.

<details>
<summary>mise.toml</summary>

```toml
[tools]
python = ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]

[env._.python]
venv = { path = ".venv", create = true }

[vars]
pip_compile_args = "-q --python python --upgrade --no-header --annotation-style=line"

[tasks.ensure-uv]
run = "command -v uv || python -m pip install uv"
hide = true

[tasks.install]
description = "Install packages required for development into the virtual environment"
depends = ["ensure-uv"]
run = "uv -q pip install -p python -Ue '.[dev,toml]' -c dev-requirements.txt -c nt2/requirements.txt -c nt2/toml-requirements.txt"

[tasks.test]
description = "Run all tests"
depends = ["install"]
run = [
  "uv -q pip install -p python -U coverage",
  "coverage run -p -m ward",
]

[tasks.test-without-toml]
description = "Run all tests, excluding optional TOML support"
run = [
  "uv -q pip sync test/test-without-toml-requirements.txt",
  "uv -q pip install -p python -Ue . -c dev-requirements.txt -c nt2/requirements.txt -c nt2/toml-requirements.txt",
  "uv -q pip install -p python -U coverage",
  "coverage run -p -m ward",
]

[tasks.test-all]
description = "Run all tests, with and without TOML support enabled"
# depends = ["test-without-toml"]
# depends_post = ["test"]
run = [
  "mise run test-without-toml",
  "mise run test"
]

[tasks.test-all-pythons]
description = "Run all tests, with and without TOML support enabled, for each supported Python release"
# mise run --tool python@$pyver test-all
run = """
  for pyver in 3.13 3.12 3.11 3.10 3.9 3.8 3.7; do
    mise run --tool python@$pyver test-without-toml
    mise run --tool python@$pyver test
  done
"""
```

</details>

**Reply by risu729** [reply]
I think it's a venv related issue, but I don't know much about the venv, so I'm not really sure about the solution.

As a minimal reproduction, both `mise run version` and `mise run --tool python@3.12 version` print `3.13.3`.
If I don't set `env._.python.venv`, the latter prints `3.12.11`.

```toml
[tools]
python = ["3.13", "3.12"]

[env._.python]
venv = { path = ".venv", create = true }

[tasks]
version = "python --version"
```

**Reply by AndydeCleyre** [reply]
Maybe it's possible to use a variable in

```toml
venv = { path = ".venv", create = true }
```

to have the venv path include the current Python version?

I'm away from the keyboard for maybe 12 hours, but will give this a try when I can.

**Reply by AndydeCleyre** [reply]
I can use a tera thing with exec and `python -V` and the slugify filter to name the venv path, but it still seems to reuse the same venv for all those runs, rather than creating new ones to match the tool.

Maybe I should lean more into uv for handling this, if mise isn't really built to support this kind of multiple Python/venv operation.

@jdx does that sound reasonable, or is there some other way to take advantage of mise's abilities here?

**Comment by JamBalaya56562** [comment]
Fixed — #11567, merged. It ships in the next release; v2026.7.18 is current and predates it.

@risu729's minimal repro was exact, and it still reproduced a year later on v2026.7.15:

| config | `mise run version` | `mise run --tool python@3.12 version` |
|---|---|---|
| with `_.python.venv` | Python 3.13.14 | **Python 3.13.14** |
| without it | Python 3.13.14 | Python 3.12.13 |

It was not the version selection. `EnvResults::venv` resolves its **own** python/uv-only toolset — deliberately, to avoid a circular wait when unrelated backends re-enter `config.env()` during env resolution — and that toolset is rebuilt from the config files. A `--tool` override only ever reaches a `Toolset` built by `ToolsetBuilder::with_args`; it is never written back to `Config`, so it could not be seen from there.

Giving the venv a version-templated path made the split visible. Under `--tool python@3.12` the directory was named for the override while its `pyvenv.cfg` recorded the other interpreter:

```
home = .../installs/python/3.13.14
version = 3.13.14
command = .../installs/python/3.13.14/python.exe -m venv .../.venv-3.12.13
```

Template rendering saw the override; interpreter selection did not. `Toolset::env` does have the right toolset, so it now passes it down and the venv directive records the active python. The rebuild and its deadlock-avoiding filter are unchanged.

**This does not make a matrix over interpreters work on its own**, and that is worth being explicit about, because it is what you were actually asking for. A venv cannot be retargeted after it is created — `venv.rs` only creates one when the path does not already exist — so `.venv` built under 3.13 stays a 3.13 venv no matter what `--tool` says on the next run. What the fix changes is that when a venv *is* created, it is created from the interpreter you selected.

For seven Python versions you still need seven venvs. Two ways, both working today:

```toml
# a distinct venv per version, named explicitly
[env._.python]
venv = { path = ".venv-312", create = true, python = "3.12" }
```

— I measured this one: `mise run version` prints `Python 3.12.13` and the venv's `pyvenv.cfg` records `version = 3.12.13`. It is static, so it means one config per version.

Or let uv own the venvs instead of `_.python.venv`, which is what I would reach for here:

```bash
for pyver in 3.13 3.12 3.11 3.10 3.9; do
  uv run --python "$pyver" -m pytest
done
```

`_.python.venv` is a one-venv-per-directory mechanism; a test matrix wants one venv per interpreter, which is uv's model rather than mise's.
