### DISCUSSION TITLE
Tasks' env overridden when predefined.

### DISCUSSION THREAD

**Discussion by 134130** [jdx/mise#5285] [Troubleshooting and bug reports] [answered]
I'm using the mise tasks like this on monorepo:

```toml
[tasks."backend:test"]
hide = true
env = { MISE_TASK_OUTPUT = 'quiet' }
run = "{{mise_bin}} -C backend run test"

[tasks."frontend:test"]
hide = true
env = { MISE_TASK_OUTPUT = 'quiet' }
run = "{{mise_bin}} -C frontend run test"

[tasks."test"]
depends = ["backend:test", "frontend:test"]
```

But the mise is overriding the `MISE_TASK_OUTPUT` as prefix. I think mise might respect the original environment variable as given.

Here is the troubleshoot configuration:

```toml
[tasks."my:test"]
hide = true
env = { "MISE_TASK_OUTPUT" = "quiet", "TASK_OUTPUT" = "quiet" }
run = '''
echo "MISE_TASK_OUTPUT=$MISE_TASK_OUTPUT" # MISE_TASK_OUTPUT=interleave
echo "TASK_OUTPUT=$TASK_OUTPUT"           # TASK_OUTPUT=quiet
'''

[tasks.test]
depends = ["my:test"]
```

Please confirm is this behavior is intended. Thanks!
