### DISCUSSION TITLE
Backend for Nexus or Artifactory

### DISCUSSION THREAD

**Discussion by Ernest0-Production** [jdx/mise#5305] [Ideas]
It would be nice to be able to add the installation of tools that are stored in the in-house Enterprise cloud, such as Artifactory:
```toml
[tool]
"my_cli" = 1.1.0 

[alias]
"my_cli" = "artifactory:http://artifactory.<company>.com/path/to/directory" 
```
