### DISCUSSION TITLE
2025.6.1: Can't disable colored output

### DISCUSSION THREAD

**Discussion by powerman** [jdx/mise#5315] [Troubleshooting and bug reports]
First issue. Looks like `mise settings color=0` has no effect on `mise ls` (didn't checked other commands).

Second issue. When `mise ls` is executed inside GitHub Actions workflow (running locally using `act`) it outputs unreadable mess like this:
```
T  V  S  R 
o  e  o  e 
o  r  u  q 
l  s  r  u 
i  c  e 
o  e  s 
n     t 
e 
d 
...  ...  ...  ...
...  ...  ...  ...
```
which is supposed to be this:
```
Tool        Version  Source                             Requested 
act         0.2.78   ~/proj/config/workflows/mise.toml  latest
actionlint  1.7.7    ~/proj/config/workflows/mise.toml  latest
```

Here is actual part of workflow:
```yml
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }} # Increase GitHub API rate limits.

      - run: mise settings color=0
      - run: mise settings
      - run: mise ls
```

Here is output of the action (which also runs `mise ls` at the end - and here it looks fine):
![изображение](https://github.com/user-attachments/assets/11be2eaf-7a8f-43bd-99f8-19ea2cb342ee)
and here is next part with settings and broken ls output:
![изображение](https://github.com/user-attachments/assets/ad59277a-0ecb-4a06-813f-0e4ee92cf745)
