### DISCUSSION TITLE
Single source of tool version

### DISCUSSION THREAD

**Discussion by dwooldridge-ctoken** [jdx/mise#5396] [General]
I need to expose the go version as an environment variable as it's used by other tools, but I don't want to specify it twice.

I currently have the following:

```toml
[env]
GO_VERSION = "1.24.4"

[tools]
golang = "1.24.4"
```

What I would like to have is something like this, but it does not work:

```toml
[env]
GO_VERSION = "1.24.4"

[tools]
golang = "{{env.GO_VERSION}}"
```

So I tried:

```toml
[env]
_.file = "tool-versions.yaml"

[tools]
golang = "{{env.GO_VERSION}}"
```

with `tool-versions.yaml` being:

```yaml
GO_VERSION: "1.24.4"
```

but this results in the error:

```
$ mise trust
mise trusted /Users/me/Repos/core/mise.toml
mise ERROR failed to parse template {{env.GO_VERSION}} in ~/Repos/core/mise.toml
mise ERROR Failed to render '__tera_one_off'
mise ERROR Variable `env.GO_VERSION` not found in context while rendering '__tera_one_off'
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Is there any way to acheive this?

Edit: version: `2025.6.5 macos-arm64 (2025-06-16)`

**Comment by dwooldridge-ctoken** [comment]
Does anyone have any idea about if this is possible?

**Comment by jc00ke** [comment]
I've been looking for a solution for this too; I'd love a single place in the `mise.toml` file to define the version of a tool that I could also use as a variable and an env var.

Or, if the tool setting could be used to set the others? This may be a bad idea, but what about:

```toml
[tools]
foo = { version = "1.2.3" }

[vars]
foo_version = "{{ tools.foo.version }}"

[env]
FOO_VERSION = "{{ tools.foo.version }}"
```

**Reply by jc00ke** [reply]
@jdx how feasible do you think this would be? Or is there another approach you'd rather implement?

**Reply by jdx** [reply]
I think you can do this today with vars but I may be wrong

**Reply by jc00ke** [reply]
I had hoped so but it looks like `vars` is available to the `tools` context:
<img width="1306" height="1023" alt="image" src="https://github.com/user-attachments/assets/507db445-268c-434e-bf95-908c21bae21f" />

I thought I remembered seeing in the docs that `vars` are only available to the `tasks` context?

This is on version `2025.8.4`.

**Comment by dwooldridge-ctoken** [comment]
@jdx I've just seen [PR6401](https://github.com/jdx/mise/pull/6401) and given it a quick test, This now works:

```toml
[vars]
GO_VERSION = "1.24.6"
PYTHON_VERSION = "3.12.3"
NODE_VERSION = "18.18.0"

[env]
GO_VERSION = "{{vars.GO_VERSION}}"
PYTHON_VERSION = "{{vars.PYTHON_VERSION}}"
NODE_VERSION = "{{vars.NODE_VERSION}}"

[tools]
go = "{{vars.GO_VERSION}}"
node = "{{vars.NODE_VERSION}}"
python = "{{vars.PYTHON_VERSION}}"
```

Presumably, this is now the correct way to achieve this? I can't just set the real versions as env vars and use them in the tools? e.g.:

```toml
[env]
GO_VERSION = "1.24.6"
PYTHON_VERSION = "3.12.3"
NODE_VERSION = "18.18.0"

[tools]
go = "{{env.GO_VERSION}}"
node = "{{env.NODE_VERSION}}"
python = "{{env.PYTHON_VERSION}}"
```
