### DISCUSSION TITLE
Mise crashes with "Infinitive loop detected" with multiple `depends_post`

### DISCUSSION THREAD

**Discussion by dijitali** [jdx/mise#5409] [Troubleshooting and bug reports]
I've simplified my `mise.toml` to the below reproduction for clarity:

```toml
[tools]
hugo = "0.147.8"

[tasks.taska]
run = "echo 'task A'"

[tasks.build]
depends = ["taska"]
run = "hugo"
depends_post = ["scriptc", "taskb"]

[tasks.taskb]
run = "echo 'something'"

[tasks.scriptc]
run = "echo 'task C'"
```

Running  the build task will crash with the following error:

<details>
<summary>mise run build error</summary>
<p>

```
mise run build
[taska] $ echo 'task A'
task A
[build] $ hugo
Start building sites … 
hugo v0.147.8-10da2bd765d227761641f94d713d094e88b920ae linux/amd64 BuildDate=2025-06-07T12:59:52Z VendorInfo=gohugoio


                  │ EN 
──────────────────┼────
 Pages            │ 17 
 Paginator pages  │  0 
 Non-page files   │ 57 
 Static files     │ 17 
 Processed images │  0 
 Aliases          │  0 
 Cleaned          │  0 

Total in 123 ms
=== Async Backtrace (panic occurred in tokio runtime) ===
[no accessible async backtrace]
------- TASK DUMP TREE -------

=== End Async Backtrace ===

The application panicked (crashed).
Message:  Infinitive loop detected, all tasks are finished but the graph isn't empty scriptc, taskb Graph {
    Ty: "Directed",
    node_count: 2,
    edge_count: 2,
    edges: (0, 1), (1, 0),
    node weights: {
        0: Task {
            name: "scriptc",
            display_name: "scriptc",
            description: "",
            aliases: [],
            config_source: "/home/ieuan/repos/ieuan-net-basic/mise.toml",
            cf: None,
            config_root: Some(
                "/home/ieuan/repos/ieuan-net-basic",
            ),
            confirm: None,
            depends: [],
            depends_post: [],
            wait_for: [],
            env: {},
            dir: None,
            hide: false,
            global: false,
            raw: false,
            sources: [],
            outputs: Files(
                [],
            ),
            shell: None,
            quiet: false,
            silent: false,
            tools: {},
            usage: "",
            run: [
                "echo 'task C'",
            ],
            run_windows: [],
            args: [],
            file: None,
        },
        1: Task {
            name: "taskb",
            display_name: "taskb",
            description: "",
            aliases: [],
            config_source: "/home/ieuan/repos/ieuan-net-basic/mise.toml",
            cf: None,
            config_root: Some(
                "/home/ieuan/repos/ieuan-net-basic",
            ),
            confirm: None,
            depends: [],
            depends_post: [],
            wait_for: [],
            env: {},
            dir: None,
            hide: false,
            global: false,
            raw: false,
            sources: [],
            outputs: Files(
                [],
            ),
            shell: None,
            quiet: false,
            silent: false,
            tools: {},
            usage: "",
            run: [
                "echo 'something'",
            ],
            run_windows: [],
            args: [],
            file: None,
        },
    },
}
Location: src/task/deps.rs:97

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
</details>

Similiarly, running `mise tasks deps` will get stuck in a loop outputting a deeper and deeper dependency tree:

```shell
mise tasks deps
build
└── taska
scriptc
├── build
│   └── taska
├── taska
└── taskb
    ├── build
    │   └── taska
    ├── taska
    └── scriptc
        ├── build
        │   └── taska
        ├── taska
        └── taskb
            ├── build
            │   └── taska
            ├── taska
            └── scriptc
                ├── build
                │   └── taska
                ├── taska
                └── taskb
                    ├── build
                    │   └── taska
                    ├── taska
                    └── scriptc
...
```

If I remove the second `depends_post` for the `build` task, it will work fine and the dependency tree also generates.

My full config is as below.
<details>
<summary>full config</summary>
<p>

```toml
[tools]
caddy = "2.10.0"
hugo = "0.147.8"
node = "lts"

[settings]
python.uv_venv_auto = true

[env]
_.source = "scripts/get-git-info.sh"

[tasks.generateimages]
description = "Strip image EXIF and geneate web-friendly formats"
sources = ["**/*.jpg"]
outputs = ["public/**/*.jpg", "public/**/*.avif", "public/**/*.webp"]
run = "scripts/image_generator.sh"

[tasks.build]
depends = ["generateimages"]
description = "Hugo build"
run = "hugo"
depends_post = ["compresspublic", "prettier"]

[tasks.prettier]
sources = ["public/**"]
outputs = ["public/**"]
description = "Run Prettier over HTML/CSS files"
run = "npx prettier --write ./public"

[tasks.compresspublic]
sources = ["public/**/*.html", "public/**/*.css"]
description = "Generate zstd, brotli and gzip files for web"
run = "scripts/compress_public.sh"

[tasks.caddyserve]
description = "Run caddy web server (note Playwright runs this internally via webServer config)"
run = "caddy file-server --root ./public --listen :3000"

[tasks.installnpmpackages]
run = "npm install"

[tasks."test:validator"]
depends = "build"
run = "vnu --skip-non-html --also-check-css --also-check-svg --verbose public"

[tasks."test:playwright"]
depends = ["build","installnpmpackages"]
run = "npx playwright test"
```

</details>

<details>
<summary>mise doctor output</summary>
<p>

```text
mise doctor
version: 2025.6.7 linux-x64 (2025-06-23)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Mon, 23 Jun 2025 11:37:12 +0000
  Rust Version: rustc 1.87.0 (17067e9ac 2025-05-09)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.9 (x86_64-ubuntu-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/snap/code/196/.local/share/mise
  shims: ~/snap/code/196/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  ~/repos/ieuan-net-basic/mise.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  aqua:gohugoio/hugo@0.147.8
  core:ruby@3.4.4

path:
  ~/snap/code/196/.local/share/mise/installs/hugo/0.147.8
  ~/snap/code/196/.local/share/mise/installs/ruby/3.4.4/bin
  /run/user/1000/fnm_multishells/106943_1750683848663/bin
  /home/linuxbrew/.linuxbrew/bin
  /home/linuxbrew/.linuxbrew/sbin
  ~/.nix-profile/bin
  /nix/var/nix/profiles/default/bin
  /run/user/1000/fnm_multishells/5062_1750679181062/bin
  /home/linuxbrew/.linuxbrew/bin
  /home/linuxbrew/.linuxbrew/sbin
  ~/.nix-profile/bin
  /nix/var/nix/profiles/default/bin
  /usr/local/sbin
  /usr/local/bin
  /usr/sbin
  /usr/bin
  /sbin
  /bin
  /usr/games
  /usr/local/games
  /snap/bin
  /snap/bin
  ~/.local/bin
  ~/.local/bin
  ~/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/scripts/noConfigScripts
  ~/.local/bin

env_vars:
  MISE_SHELL=zsh

settings:
  idiomatic_version_file_enable_tools  ["ruby"] ~/.config/mise/config.toml

No problems found
```
</details>
