### DISCUSSION TITLE
AWS Code artifact + uv use case - Task templates / lazy env vars / expanded hooks / shared task evn vars

### DISCUSSION THREAD

**Discussion by krzysztofkusmierczyk** [jdx/mise#5421] [Ideas]
Hi,

Thank you for creating mise.

I'm using mise + uv in a python project with code artifact as an additional uv repository. My goal is to create mise configuration that will automatically log in into aws sso and code artifact. This would improve developer experience and onboarding.
I can set uv repository env variable in the `[env]` section like this:
```toml
[env]
UV_INDEX_XXX_CODEARTIFACT_PASSWORD = "{{ exec(command='aws codeartifact get-authorization-token --domain XXX --domain-owner XXX --query authorizationToken --output text', cache_key='token', cache_duration='12h') }}"
```
This will run when entering the repository directory even if I don't plan on running any commands that need access to the repository, resulting in errors when I only wanted to quickly check something in the code.

To solve this issue I moved env variable to tasks definitions. This works how I want it to, but it results in duplication and bloated task definitions. With this setup the code artifact env variable is not available when running uv commands in the terminal, I need to wrap it with mise which is not the nicest solution.
My mise.toml below, some parts were removed for brevity. `aws_login` is a file task that triggers `aws sso login` if the tokens are expired.
```toml
[tools]
python = "3.12.10"
uv = "0.7"

[env]
_.python.venv = { path = ".venv", create = true }

UV_INDEX_XXX_CODEARTIFACT_USERNAME = "aws"

[tasks.uv]
run = 'uv {{arg(name="uv_args", var=true)}}'
depends = ["aws_login"]
[tasks.uv.env]
UV_INDEX_XXX_CODEARTIFACT_PASSWORD = "{{ exec(command='aws codeartifact get-authorization-token --domain XXX --domain-owner XXX --query authorizationToken --output text', cache_key='token', cache_duration='12h') }}"

[tasks.deps]
run = ["uv sync"]
depends = ["aws_login"]
[tasks.deps.env]
UV_INDEX_XXX_CODEARTIFACT_PASSWORD = "{{ exec(command='aws codeartifact get-authorization-token --domain XXX --domain-owner XXX --query authorizationToken --output text', cache_key='token', cache_duration='12h') }}"


[tasks.format]
run = ["ruff format", "ruff check --fix"]


[tasks.build]
depends = ["aws_login"]
run = ["docker compose build"]
[tasks.build.env]
UV_INDEX_XXX_CODEARTIFACT_PASSWORD = "{{ exec(command='aws codeartifact get-authorization-token --domain XXX --domain-owner XXX --query authorizationToken --output text', cache_key='token', cache_duration='12h') }}"
```

I'm out of ideas and it looks like this is the limit I can achieve with mise, but maybe there is a potential to add new features that will improve this workflow.

My vague ideas:
- Task templates - a way to put repeated parts of tasks into single place. Like subtypes in OOP.
- Lazy env vars - env vars that would be evaluated only for specific tasks or cli commands
- Expanded hooks that would evaluate env vars on specifie actions, like some mise tasks or cli commands (uv sync).
- Shared taks envs - option to pass env vars from one task to another. This would decrease duplication by putting env setup in a single task.

Any other solutions would be appreciated.
