### DISCUSSION TITLE
Parallel execution is unreliable since 2025.5.14

### DISCUSSION THREAD

**Discussion by pietrodn** [jdx/mise#5451] [Troubleshooting and bug reports]
Hi, I'm trying to define a Mise task to run in parallel other tasks. This is my `mise.toml` reproduction case:

```toml
[tasks.process1]
run = "echo 'process1 begin' && sleep 5 && echo 'process1 done'"

[tasks.process2]
run = "echo 'process2 begin' && sleep 5 && echo 'process2 done'"

[tasks.process3]
run = "echo 'process3 begin' && sleep 5 && echo 'process3 done'"

[tasks.process4]
run = "echo 'process4 begin' && sleep 5 && echo 'process4 done'"

[tasks.process5]
run = "echo 'process5 begin' && sleep 5 && echo 'process5 done'"

[tasks.process6]
run = "echo 'process6 begin' && sleep 5 && echo 'process6 done'"

[tasks.run-all]
run = "mise run process1 ::: process2 ::: process3 ::: process4 ::: process5 ::: process6"
```

## What I do

I run `mise r run-all`

## What I expect

```
$ mise r run-all
[run-all] $ mise run process1 ::: process2 ::: process3 ::: process4 ::: process5 ::: process6
[process6] $ echo 'process6 begin' && sleep 5 && echo 'process6 done'
[process2] $ echo 'process2 begin' && sleep 5 && echo 'process2 done'
[process4] $ echo 'process4 begin' && sleep 5 && echo 'process4 done'
[process3] $ echo 'process3 begin' && sleep 5 && echo 'process3 done'
[process1] $ echo 'process1 begin' && sleep 5 && echo 'process1 done'
[process5] $ echo 'process5 begin' && sleep 5 && echo 'process5 done'
process6 begin
process4 begin
process1 begin
process2 begin
process3 begin
process5 begin
process6 done
process4 done
process1 done
process2 done
process3 done
process5 done
Finished in 5.03s
```

(this _sometimes_ happens)

## What is happening

```
$ mise r run-all
[run-all] $ mise run process1 ::: process2 ::: process3 ::: process4 ::: process5 ::: process6
[process5] $ echo 'process5 begin' && sleep 5 && echo 'process5 done'
process5 begin
process5 done
[process4] $ echo 'process4 begin' && sleep 5 && echo 'process4 done'
process4 begin
process4 done
[process1] $ echo 'process1 begin' && sleep 5 && echo 'process1 done'
[process3] $ echo 'process3 begin' && sleep 5 && echo 'process3 done'
process3 begin
process1 begin
process3 done
process1 done
[process6] $ echo 'process6 begin' && sleep 5 && echo 'process6 done'
process6 begin
process6 done
[process2] $ echo 'process2 begin' && sleep 5 && echo 'process2 done'
process2 begin
process2 done
Finished in 25.18s
```

(This happens intermittently.)

## The problem

After bisecting a bit, I found out that the parallel execution of task has become unreliable since Mise 2025.5.14.
The tasks are sometimes launched all in parallel and sometimes one at a time. Until Mise 2025.5.13, they were all launched together and in parallel.

## Info

I am running `version: 2025.6.8 macos-arm64 (2025-06-26)`
`mise doctor` reports no issues.
Setting `MISE_JOBS` does not change the behavior.

**Comment by jdx** [comment]
I seem unable to reproduce this: https://github.com/jdx/mise/pull/6221

**Comment by pavelzherdin** [comment]
I think the test case is incomplete. With just that config in isolation, `run-all` works for me. There's probably ~/.config/mise/config.toml with something more.

Some attempts to reproduce point at needing a few tools to actually see the problem. F.e. these were enough for me inside a container:
```toml
[tools]
python = "3.12"
pipx = "latest"
pipenv = "latest"
```
I don't know if there's a way to have a "dummy" tool. And I tried picking tools that have "depends" in the registry.toml.
