### DISCUSSION TITLE
.NET as a core tool

### DISCUSSION THREAD

**Discussion by kimsagro1** [jdx/mise#5484] [General]
Are the any plans to support [.NET](https://dotnet.microsoft.com/en-us/download) as a core tool, and / or would you be open to a PR?

**Comment by JamBalaya56562** [comment]
This landed — .NET is a core tool now, not just a backend.

#8326 ("feat: add core dotnet plugin for .NET SDK management") added `core:dotnet`, first released in **v2026.2.22**. It is the registry default, so plain `dotnet` resolves to it:

```console
$ mise tool dotnet
Backend:            core:dotnet
```

`registry/dotnet.toml` also aliases `dotnet-core` to it (#9807) and registers `global.json` as an idiomatic version file, so an existing `global.json` is honoured without extra configuration.

Worth separating from this, because the names collide: there is *also* a **`dotnet:` backend**, which is a different thing. That one installs .NET global tools from NuGet (`dotnet tool install`) and needs an SDK present first — `core:dotnet` is what installs the SDK itself. So:

```toml
[tools]
dotnet = "9"                      # the SDK, via core:dotnet
"dotnet:dotnet-ef" = "latest"     # a .NET global tool from NuGet
```
