### DISCUSSION TITLE
How to run post install script for plugins

### DISCUSSION THREAD

**Discussion by Pilgrim1379** [jdx/mise#605] [Q&A] [answered]
For python, node and go, I have some global packages that I install everytime I upgrade. I've created a script that installs all the packages for each plugin.
Is there a way to run scripts post install of a plugin automatically?

**Comment by Marukome0743** [comment, marked as answer]
This is supported in current mise versions with a per-tool `postinstall` command:

```toml
[tools]
node = { version = "22", postinstall = "npm install -g <packages>" }
python = { version = "3.12", postinstall = "python -m pip install <packages>" }
go = { version = "1.24", postinstall = "go install <packages>" }
```

The command runs after that specific tool version has been installed successfully. The newly installed tool's bin directory is already on `PATH`, and the command can use:

- `MISE_TOOL_NAME`
- `MISE_TOOL_VERSION`
- `MISE_TOOL_INSTALL_PATH`

There is also a global install hook if one script should run after the complete `mise install` operation:

```toml
[hooks]
postinstall = "./install-default-packages.sh"
```

The global hook receives `MISE_INSTALLED_TOOLS` as a JSON array, so the script can determine which tools were installed.

I verified the per-tool form against the current main branch with a clean mise data directory. The command ran immediately after installing the configured tool and successfully received its name, version, and installation path.

Mise also still recognizes files such as `.default-python-packages`, `.default-npm-packages`, and `.default-go-packages`, but these are now considered legacy functionality. The explicit `postinstall` option is the more flexible approach for new configurations.

*AI-assisted — Tool: Codex; model: OpenAI/GPT-5; version: unavailable.*
