### DISCUSSION TITLE
Ansible role for rtx

### DISCUSSION THREAD

**Discussion by dfang** [jdx/mise#678] [Show and tell]
https://github.com/dfang/ansible-role-rtx

will update after it's stable

**Comment by fgimian** [comment]
Great job, one of the challenges I have when integrating rtx into my Ansible playbooks is the ability to get global tool versions. Currently, `rtx global` only shows the global versions in `.tool-versions` files which are going to be removed in a future version and are only for asdf compatibility.

Using `rtx ls` or `rtx current` may show a local installation if a `.rtx.toml` file is present in a parent directory.

Have you found an easy way to obtain the currently selected global versions for each plugin as defined in `~/.config/rtx/config.toml` short of parsing this file yourself?

**Reply by dfang** [reply]
run rtx activate before install？ i will try it later. currently i install tool versions by passing varibles not reading ~/.config/rtx/config.toml

**Reply by fgimian** [reply]
Thanks heaps for the reply, I understand yeah. Sadly activating rtx could still show locally defined versions with `rtx current`. I've opened this issue https://github.com/jdxcode/rtx/issues/803 to request the ability to show global versions including those in the TOML files.

My simple solution (without involving additional galaxy components which parse TOML) looks like this:

```yaml
    - name: Determine if the requested global Perl version is configured
      ansible.builtin.lineinfile:
        name: ~/.config/rtx/config.toml
        line: 'perl = "5.38.0"'
      check_mode: true
      changed_when: false
      failed_when: false
      register: perl_global_version_config
    - ansible.builtin.debug:
        msg: Must use rtx use -g if this condition is true
      when: 'perl_global_version_config.msg != ""'
```

Thanks heaps
Fotis

**Reply by herda05** [reply]
@fgimian curious if you ever continued with this?
I'm currently using ansible_python_interpreter var to make sure we are using a standard python. However, the way mise creates the things in .local has posed a problem.
I'm also trying to understand if ansible is doing an interactive or non-interactive login.

**Reply by fgimian** [reply]
I am actually automating mise via Ansible, this is how I've done it:

Variables being passed in:

```yaml
core_mise_version: 2024.2.15
```

And the mise tasks:

```yaml
---
- name: Install mise
  ansible.builtin.get_url:
    url: 'https://github.com/jdx/mise/releases/download/v{{ core_mise_version }}/mise-v{{ core_mise_version }}-linux-x64'
    dest: /usr/local/bin/mise
    mode: '0755'
  become: true

- name: Enable mise
  ansible.builtin.copy:
    dest: ~/.bashrc.d/mise.sh
    content: |
      eval "$(mise activate bash)"
    mode: '0644'

- name: Enable mise Bash completions
  ansible.builtin.shell:
    cmd: mise completion bash > /etc/bash_completion.d/mise.sh
    creates: /etc/bash_completion.d/mise.sh
  become: true
```

And for installing Python, here are the variables:

```yaml
    python_versions:
      - 3.10.13
      - 3.11.8
      - 3.12.2
    python_default_version: 3.10.13
```

And the tasks:

```yaml
---
# See https://github.com/pyenv/pyenv/wiki for further information
- name: Install dependencies required to build Python
  ansible.builtin.apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  become: true

- name: Enable the Python mise plugin
  ansible.builtin.command:
    cmd: mise plugin install python https://github.com/asdf-community/asdf-python.git
    creates: ~/.local/share/mise/plugins/python/bin/install

- name: Install the required Python versions with mise
  ansible.builtin.command:
    cmd: 'mise install python@{{ item }}'
  args:
    creates: '~/.local/share/mise/installs/python/{{ item }}/bin/python'
  loop: '{{ python_versions }}'

- name: Determine if the requested global Python version is configured
  ansible.builtin.command:
    cmd: mise ls -p python -g
  changed_when: false
  failed_when: false
  register: python_global_version

- name: Set the global Python version
  ansible.builtin.command:
    cmd: 'mise use -g python@{{ python_default_version }}'
  changed_when: python_global_version.stdout.split() | last | default('') != python_default_version
```

The playbook is run as a regular user so that `become` is only used where necessary.

Hope this helps
Fotis
