### ISSUE TITLE
Provide way to specify simple post-install hooks/commands to run for tools (e.g NodeJS corepack)

### ISSUE THREAD

**Issue by chadlwilson** [jdx/mise#1014]
Currently every time I install or upgrade a NodeJS version I need to remember to do a `corepack enable` afterwards since [corepack](https://nodejs.org/api/corepack.html) is now recommended for use with yarn, pnpm etc - despite the functionality being considered experimental from Node's perspective. At least with `mise` there is no need to `reshim` :-)

Not quite sure where/how might make sense to specify this, or perhaps whether something specific could be done for the Node plugin, e.g

```toml
node = {version='20', corepack: true}
node = [{version='16' corepack: true}, 'prefix:16', 'ref:master', 'path:~/.nodes/16']
```

This may be a bad idea, or there may be an alternate/existing approach that I could not find.
