### ISSUE TITLE
TASK_OUTPUT=prefix with color

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#1290]
I'm trying to start the backend (django) and frontend (vite) of my dev environment.

```toml
[tasks.dev-all]
description = 'Start backend and frontend'
depends = ['backend', 'frontend']
```

Problem: I lose colors. `TASK_OUTPUT=interleave`/`-i` works, but then I lose the prefix, which is useful.

edit, as a workaround I've added `env = {FORCE_COLOR = '1'}` to both tasks.

- [x] set FORCE_COLOR/CLICOLOR_FORCE #1364 
- [x] use interleaved if dep graph is linear
