### ISSUE TITLE
virtualenv / poetry not loading

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#1295]
How can I debug this? The same .rtx.toml file that loads the virtualenv on my mac, doesn't load it on an ubuntu server.

```toml
[tools]
poetry = { version = 'latest', pyproject = 'pyproject.toml' }
python = '3.11'
```

I ran `whereis` in the app folder which contains .rtx.toml on my mac and the ubuntu server.

mac:
```
$> whereis python
python: ~/Library/Caches/pypoetry/virtualenvs/:app-:hash-py3.11/bin/python
```

ubuntu:
```
$> whereis python
python: ~/.local/share/rtx/installs/python/3.11.6/bin/python
```
