### ISSUE TITLE
new venv syntax

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1303]
I think I want to move venv configuration for python/poetry into the `[env]` section rather than putting it on individual tools:

```toml
[env]
_.python.venv = "~/.venv/myvenv"
_.poetry.pyproject = "pyproject.toml"
```

this would make it still driven by the plugin (allowing other plugins to do similar things), but also make it possible to use with the system python resolving #1248.

More importantly though, this just feels like the more correct place to put it since it's configuring the "environment"—not the python installation. That said it will depend on that so a bit of care around making sure if there is a python version set it needs to be installed _before_ setting the venv.
