### ISSUE TITLE
`watch` should recurse task dependencies (or some other way to watch wildcard/all tasks)

### ISSUE THREAD

**Issue by innermatrix** [jdx/mise#1371]
I have a task `a` with `sources` and `outputs`, a task `b` with `sources` and `outputs`, and a task `all` which is `depends` on `a` and `b`. If I run `mise run all`, things work as expected (`a` or `b` or neither run, depending on the state of the sources). If I run `mise watch all`, and then modify one of the source files, no tasks rerun. 

I would like better support for watching tasks with dependencies.

**Comment by jdx** [comment]
gah I thought this would come up, but I was actually thinking it _shouldn't_ do that! I was thinking if maybe you had a `build` task that depended on a `clean`—then you would only want the `build` part to run and if I did all dependencies you wouldn't have a way to control that.

As it is, with the current behavior you _can_ control it because you can just specify the dependencies you want to watch explicitly.

This is why it's experimental though, so we can noodle with this behavior and figure out what works.

I also think that https://github.com/jdx/mise/issues/1271 might be able to solve this problem in a slightly different way at least in a subset of use-cases.

Anyhow, I welcome as many people's input on this behavior as possible so we can figure out what mise should do here.

**Comment by innermatrix** [comment]
My take on this is that `watch` should behave exactly the same as `run`, in the sense that the end result of running `watch foo` and then changing a file should (after the `watch` run completes) have the exact same output as changing the same file and then running `run foo`. That seems like the least surprising invariant to me.

To apply that to your specific example: if I have `build` that depends on `clean` and `build` has file `x` in `sources`, then changing `x` and running `run build` would first run `clean` (because it has no `sources` and therefore always runs) and then run `build` (because it has one source, and that source is modified). 

And therefore, I think that running `watch build` followed by changing `x` should rerun both `clean` (because it always runs) and `build` (because its input was changed).

**Comment by sirenkovladd** [comment]
I agree with @innermatrix 

But looking ahead in case I run `D` and change the `sources` only in `A` it can be simplified to running 
`A`->`B`->`D` (omitted `C` `E`)

But of course, at first it will be enough to simply restart the `mise run D` command in case of changing any of the dependencies

```
        ┌─┐   
    ┌──►│D│◄┐ 
    │   └─┘ │ 
   ┌┴┐     ┌┴┐
 ┌►│B│◄┐   │E│
 │ └─┘ │   └─┘
┌┴┐   ┌┴┐     
│A│   │C│     
└─┘   └─┘     
```

**Comment by powerman** [comment]
v2024.11.0 runs task which does not define own `sources` but depends on other tasks with `sources` in an infinite loop.

```toml
[tasks."convert"]
description="Convert all versions"
depends=['convert/*']

# When we'll have a lot of these we can replace them all with a task-to-generate-tasks. :-D
[tasks."convert/1.60.3"]
sources=['1.60.3/reference/.golangci.yml']
outputs=['1.60.3/.golangci.yml']
run='scripts/convert 1.60.3 1.60'

[tasks."convert/1.61.0"]
sources=['1.61.0/reference/.golangci.yml']
outputs=['1.61.0/.golangci.yml']
run='scripts/convert 1.61.0 1.60'
```

```
$ mise watch -t convert
mise $ watchexec -- mise run convert
[Running: mise run convert]
[convert/1.60.3] sources up-to-date, skipping
[convert/1.61.0] sources up-to-date, skipping
[Command was successful]
[Running: mise run convert]
[convert/1.60.3] sources up-to-date, skipping
[convert/1.61.0] sources up-to-date, skipping
[Command was successful]
...
```

Running just one task with `sources` works fine:

```
$ mise watch -t convert/1.61.0
mise $ watchexec -f 1.61.0/reference/.golangci.yml -- mise run convert/1.61.0
[Running: mise run convert/1.61.0]
[convert/1.61.0] sources up-to-date, skipping
[Command was successful]
```
