### ISSUE TITLE
Unclear global settings migration path

### ISSUE THREAD

**Issue by GreyTeardrop** [jdx/mise#1391]
First of all, thank you for this awesome tool!

Today I upgraded mise from 2024.1.7 to 2024.1.9 and got a warning message
```
2024.1.9 macos-arm64 (2024-01-07)
mise [settings] inside of ~/.config/mise/config.toml is deprecated. A separate ~/.config/mise/config.toml file should be used instead.
mise Removing the [settings] section from ~/.config/mise/config.toml will remove this warning
```

My `config.toml` looks like this
```toml
[settings]
experimental = true

[tools]
direnv = "system"
go = "prefix:1.21"
java = "temurin-21"
kubectl = "system"
node = "20"
python = "3.12"
ruby = "3.3"
talos = "system"
teleport-community = "14.3.0"
```

I tried removing the `[settings]` section from it but got another error
```
Error loading settings file: TOML parse error at line 1, column 1
  |
1 | [tools]
  | ^
missing field `settings`
```

Finally, I completely removed the file and reproduced the configuration by first running
```
mise settings set experimental true
```
and then `mise use --global` for all the tools I needed. That resulted in a valid setup, with new `settings.toml`:
```toml
#:schema https://mise.jdx.dev/schema/settings.json
experimental = true
```
and an updated `config.toml`:
```toml
[tools]
direnv = "system"
go = "prefix:1.21"
java = "temurin-21"
kubectl = "system"
node = "20"
python = "3.12"
ruby = "3.3"
talos = "system"
teleport-community = "14.3.0"
```

PS. The schema URL from the `settings.toml` returns "404 You are not authorized to view this object" to me for some reason.
