### ISSUE TITLE
Running python tasks is not hitting the venv binaries

### ISSUE THREAD

**Issue by alikefia** [jdx/mise#1394]
**Describe the bug**
When using python in tasks, the used binary is the on on `mise` installed folders and not the `venv` one. Typically tasks to `pip install` are not targeting the venv

**To Reproduce**
```toml
[tools]
python = { version = "3.12", virtualenv = "{{config_root}}/.venv" }

[tasks.deps]
description = "install deps"
run = [
  "pip install -U pip",
  "pip install -U -r requirements.txt",
  "pip install -U -r requirements.dev.txt",
]
```
**Expected behavior**
Expecting the venv `python` to be called.
