### ISSUE TITLE
tasks: default to cwd

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1445]
initially I thought it would be good to default task directories to the "project root" because a common bug is developers not making their stuff work outside of it. Defaulting to there would make for consistency.

After working with it for a bit I'm less convinced. In the case of nested configs, which should it default to? It also makes global tasks weird.

I think this should change to the more obvious behavior of just running in the user's current directory, being able to use the project root with the following:

```toml
[tasks.build]
run = 'cargo build'
dir = '{{config_root}}'
```
