### ISSUE TITLE
`env._.source`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1447]
Support sourcing bash files in `[env]`:

```toml
[env]
_.source = "./script.sh"
```

The variables exported within the script should be imported. This will require running scripts in bash. I'll make a separate ticket for other types of scripts/binaries.
