### ISSUE TITLE
support `[[env]]`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1449]
It needs to be possible to use multiple `[env]` in-case of using multiple directives, e.g.:

```toml
[[env]]
_.source = "./script_1.sh"
[[env]]
_.source = "./script_2.sh"
```

This would not be possible with just `[env]`. `[env]` will still work and be the preferred syntax, this is just to account for the rare case when this is needed.
