### ISSUE TITLE
Cannot install tool on go backend

### ISSUE THREAD

**Issue by Jomik** [jdx/mise#1532]
**Describe the bug**
I am trying to install `github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen` but it fails.
I have tried two methods..

**To Reproduce**
Run `mise use go:github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen`
Results in 
`mise missing field `Versions` at line 10 column 1`
```yaml
// go list -m -versions -json github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen
{
        "Path": "github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen",
        "Origin": {
                "VCS": "git",
                "URL": "https://github.com/deepmap/oapi-codegen",
                "Subdir": "v2/cmd/oapi-codegen",
                "TagPrefix": "v2/cmd/oapi-codegen/",
                "TagSum": "t1:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
        }
}
```

Run `mise use go:github.com/deepmap/oapi-codegen/v2`
Results in
```text
mise failed to remove ~/.cache/mise/go-github.com-deepmap-oapi-codegen-v2/latest: failed rm -rf: ~/.cache/mise/go-github.com-deepmap-oapi-codegen-v2/latest
go: downloading github.com/deepmap/oapi-codegen/v2 v2.1.0
go: downloading github.com/deepmap/oapi-codegen v1.16.2
go: github.com/deepmap/oapi-codegen/v2@latest: module github.com/deepmap/oapi-codegen/v2@latest found (v2.1.0), but does not contain package github.com/deepmap/oapi-codegen/v2
mise go failed
go: downloading github.com/deepmap/oapi-codegen/v2 v2.1.0
go: downloading github.com/deepmap/oapi-codegen v1.16.2
go: github.com/deepmap/oapi-codegen/v2@latest: module github.com/deepmap/oapi-codegen/v2@latest found (v2.1.0), but does not contain package github.com/deepmap/oapi-codegen/v2
mise go exited with non-zero status: exit code 1
```
```yaml
// go list -m -versions -json github.com/deepmap/oapi-codegen/v2
{
        "Path": "github.com/deepmap/oapi-codegen/v2",
        "Version": "v2.1.0",
        "Versions": [
                "v2.0.0",
                "v2.1.0"
        ],
        "Time": "2024-01-25T14:59:31Z",
        "Indirect": true,
        "Dir": "~/.local/share/mise/installs/go/1.21.5/packages/pkg/mod/github.com/deepmap/oapi-codegen/v2@v2.1.0",
        "GoMod": "~/.local/share/mise/installs/go/1.21.5/packages/pkg/mod/cache/download/github.com/deepmap/oapi-codegen/v2/@v/v2.1.0.mod",
        "GoVersion": "1.20"
}
```

**Expected behavior**
Expected to have `oapi-codegen` v2 available on my PATH.

**`mise doctor` output**

```text
mise version:
  2024.1.26 macos-arm64 (2024-01-25)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Thu, 25 Jan 2024 18:30:56 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.7.0

mise data directory:
  ~/.local/share/mise

mise environment variables:
  MISE_SHELL=fish

settings:
  {
    "activate_aggressive": false,
    "all_compile": false,
    "always_keep_download": false,
    "always_keep_install": false,
    "asdf_compat": false,
    "cargo_binstall": true,
    "color": true,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "experimental": true,
    "jobs": 4,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "node_compile": false,
    "not_found_auto_install": true,
    "paranoid": false,
    "plugin_autoupdate_last_check_duration": "7d",
    "python_compile": false,
    "python_default_packages_file": "~/.default-python-packages",
    "python_patch_url": null,
    "python_precompiled_os": null,
    "python_patches_directory": null,
    "python_precompiled_arch": null,
    "python_pyenv_repo": "https://github.com/pyenv/pyenv.git",
    "python_venv_auto_create": false,
    "raw": false,
    "shorthands_file": null,
    "task_output": null,
    "trusted_config_paths": [],
    "quiet": false,
    "verbose": false,
    "yes": false,
    "ci": false,
    "cd": null,
    "debug": false,
    "env_file": null,
    "trace": false,
    "log_level": "info"
  }

config files:
  ~/.config/mise/config.toml
  ~/projects/work/.mise.toml

plugins:
  bun      (core)
  deno     (core)
  erlang   (core)
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  node@lts, go@latest, python@latest

No problems found
```
