### ISSUE TITLE
tasks: tool dependencies

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1572]
I feel like it'd be great if you could do the following to automatically install tools for certain tasks:

```toml
[tasks.run]
tools = ['node', 'go']
run = '...'
```

and it would make sure that whatever version for node and go are set would be automatically installed. Maybe we could accept a wildcard here as well.

**Comment by jdx** [comment]
on second thought I think this is too dicey. You might not want to use mise for these tools

**Comment by ramnes** [comment]
Interesting. How do you enforce that a task is run with a specific version of a tool? I'm looking for a way to replicate [pre-commit](https://pre-commit.com/) `rev:` thing, that makes runs kind of "reproducible", and just ended up here. :)

**Comment by jdx** [comment]
I'm not so sure we should offer that. I think it's better for a config to be "global" to a project rather than provide ways to customize it per tasks right now.

**Comment by ramnes** [comment]
Yes, the tools definitions and their versions should be global, 100% agree!

What I'd like to see is a way to link a task to a tool. Right now I can run `mise run lint` with a version that isn't controlled by mise, and that's a problem, especially if I expect the other people that are collaborating to my project to use the same tools than me.

Linking tasks to tools would also allow `mise` to automatically install missing tools, which I currently have to do in my task scripts.

**Comment by AntoninRousset** [comment]
I am extensively using tasks in my project and my CI jobs are basically thin wrapper that calls the corresponding task:
```yaml
.mise:
  before_script:
    - curl https://mise.run | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - mise install
    - mise settings set experimental true
  script:
    - mise tasks run "$CI_JOB_NAME"
```
As one example, one of these tasks generates HTTP clients using [openapi-generator](https://github.com/OpenAPITools/openapi-generator) which requires java. Installing every libraries for each job considerably slows down my pipeline and I would like to be able to specify what tools need to be installed for each task.
