### ISSUE TITLE
Cross-package dependencies

### ISSUE THREAD

**Issue by sirenkovladd** [jdx/mise#1590]
I have a multi-repository and would not like to duplicate commands
It would be great to be able to call a task from another directory
a great example is https://github.com/google/wireit?tab=readme-ov-file#cross-package-dependencies

for now if you try to do something like
```toml
[tasks.repo1]
dir = "./repo1"
run = "mise run command1"
```
We will see several levels of nesting
```sh
[repo1] $ mise run command1
[repo1] [command1] output
```
