### ISSUE TITLE
Allow to force virtualenv creation by default

### ISSUE THREAD

**Issue by noirbizarre** [jdx/mise#1726]
To enable virtualenv creation, we need to add this to the `.mise.toml`:
```toml
[env]
_.python.venv = { path = ".venv", create = true }
```
This form prevent from applying it globally and doing it with a single command line `mise use python@<version>`.

It would be nice to have a way to say "I always want a virtualenv created in `.venv`" so when I run `mise use python@<version>` it automatically creates the `.venv` whatever the directory I am into.

(If there is already a way of doing this, I might have missed it, links are welcome)
