### ISSUE TITLE
Glob support for `env._.file` and `env._.source` directive

### ISSUE THREAD

**Issue by noirbizarre** [jdx/mise#1916]
As of today, it is possible to source one dotfile:
```toml
[env]
_.file = "my.env"
```

It is possible to source multiple dotfiles:
```toml
[env]
_.file = [
  "my.env",
  "other.env",
]
```

Would it be possible to support glob patterns (ideally with double star support) for those 2 forms ?

```toml
[env]
_.file = "env.d/*.env"
```

```toml
[env]
_.file = [
  "my.env",
  "env.d/**/*.env",
]
```

This would be very practical (at least for cases where you don't know which file would exists before entering the directory)

Having the same for `env._.source` too would be perfect.
