### ISSUE TITLE
Support for $MISE_ENV in config file

### ISSUE THREAD

**Issue by vanyauhalin** [jdx/mise#1928]
Hi Jeff. I have been using Mise and could not be happier. I have been pondering over an idea. Often, I find myself writing simple programs where the config file does not exceed a few lines. 

```sh
$ cat .mise.toml
[tools]
go = "prefix:1.22"

$ cat .mise.production.toml
[tools]
go = "prefix:1.17"
```

Would not it be great if we could consolidate everything into a single file?

```toml
# [tools:{MISE_ENV}]

[tools]
go = "prefix:1.22"

[tools:production]
go = "prefix:1.17"
```

... or:

```toml
# [{MISE_ENV}.tools]

[tools]
go = "prefix:1.22"

[production.tools]
go = "prefix:1.17"
```

Personally, I prefer the first.

I think this aligns perfectly with the Mise philosophy. This tool was crafted to combine all vendor-specific dotfiles into a single entity. Similarly, we can apply this concept to define different environments.
