### ISSUE TITLE
Alternative backends for python venv 

### ISSUE THREAD

**Issue by Adirelle** [jdx/mise#1971]
The core python plugin can [be set up to automatically create a virtual environment](https://mise.jdx.dev/lang/python.html#automatic-virtualenv-activation) if it does not exist. In its current state, it only uses `venv` but there are alternative tools, like [pipenv](https://pipenv.pypa.io/en/latest/), [poetry](https://python-poetry.org/) or [pdm](https://pdm-project.org/en/stable/), to cite a few.

Would it be possible to add an option to the python core plugin to select which backend to use? This could be handled either by hardcoding the list of the backends in the plugin with the right commands to use, or by allowing the user to specify the command to create the virtual environment.

e.g. either
```toml
[env]
_.python.venv = { path = ".venv", create = true, backend = "pdm" } 
```
or 
```toml
[tools]
pdm = "latest"
[env]
_.python.venv = { path = ".venv", create = true, command = "pdm sync" } 
```
