### ISSUE TITLE
`tasks.toml`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1974]
I think it would be nice if you could add tasks in a dedicated file like `tasks.toml`. This could be configured in `.mise.toml` probably like this:

```toml
tasks = {import = './tasks.toml'}
```

Then inside of `tasks.toml` everything can live at the top level which can keep it quite a bit cleaner:

```toml
test = 'make test'
lint = 'make lint'
```
