### ISSUE TITLE
Different plug-in download orders may cause mise-action to fail

### ISSUE THREAD

**Issue by rakuyoMo** [jdx/mise#2045]
Hello! Dear author, I use mise in Github Action, the key content in the `.yaml` file is as follows:

```yaml
name: Swift Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Xcode ${{ matrix.xcode }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        xcode: ["15"]
    steps:
      - name: Set up debug
        if: ${{ runner.debug == '1' }}
        run: env
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          MISE_VERBOSE: ${{ runner.debug == '1' }}
          RUST_BACKTRACE: ${{ runner.debug == '1' }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

...
```

My `.mise.toml` file looks like this:
```toml
[plugins]
swift-style-guide = 'https://github.com/RakuyoKit/asdf-swift-style-guide.git#archive/1.2.0'

[tools]
pre-commit = "3.7.0"
swift-style-guide = "1.1.3"
swiftformat = "0.53.8"
swiftlint = "0.54.0"
tuist = "4.12.0"
```

The problem is with my custom plugin `swift-style-guide`. I found that when executing `mise-action`, different download orders will cause the `swift-style-guide` plug-in to **fail to download**.

Failure is not guaranteed, it depends on the download order. I intercepted the log and attached it: [tuist_issue_resource.zip](https://github.com/jdx/mise/files/15275341/tuist_issue_resource.zip)

> I used 5 blank lines as separation: the content before the blank line is consistent, and the content after it starts to be different.

Judging from the logs, it seems that there is a problem with the `list-all` command of the `swift-style-guide` plugin. I tried to [fix](https://github.com/RakuyoKit/asdf-swift-style-guide/pull/17) it in the 1.2.1 version, ~~using the `archive/1.2.1` branch to download `swift- After style-guide` plugin, its behavior in Github Action became normal.~~

EDIT: `archive/1.2.1` still has a probability of causing failure

what puzzles me is, if it is a problem with `list-all`, then **why does it sometimes succeed**? But if it’s not a problem with `swift-style-guide`, then why is it the error reported every time?

I suspect this could be a potential bug in `mise` or `mise-action`? I'm not sure, but I thought I'd report it and see who could have any clues.
