### ISSUE TITLE
create cargo-binstall plugin

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2062]
might be ideal to wait for vfox for this. If we had this, it would be possible to make bootstrapping a lot faster when using the cargo backend, e.g.:

```toml
[tools]
cargo-binstall = "latest"
"cargo:eza" = "latest"
```
