### ISSUE TITLE
install dependencies before resolving

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2073]
if you have a config like the following:

```toml
[settings]
experimental = true

[tools]
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
```

and from a clean setup run `mise install`, it will install go but fail to install gopls. This is because mise tries to resolve everything before installing anything, however gopls can't resolve without gopls installed.

This is likely a tricky change since mise has an extremely naive "dependency" setup. A robust solution probably involves building a dependency graph and traversing the leaf nodes.

A related issue is that if resolving requires any non-declared dependencies also provided by mise, they won't work either. Yet another related issue is that asdf plugins have no way to specify dependencies (they're just hardcoded).

This is related to #2068
