### ISSUE TITLE
mise pre-commit and gha generate commands

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2115]
It's pretty easy to setup a git pre-commit hook that calls a mise task by creating a `.git/hooks/pre-commit` hook in a repo like this:

```bash
#!/usr/bin/env bash
mise run pre-commit
```

I think we could create a command to generate this like `mise generate pre-commit` which could just write that file and `chmod +x` on it. Similarly, I find myself creating github action workflows that are similar to this:

```yml
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run ci
```

which could also be generated with something like `mise generate github-action test`.

These could accept parameters to change the output, like `--task` to change which mise task it runs.
