### ISSUE TITLE
tasks: pass env vars to dependent tasks

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#2162]
```toml
[tasks.foo]
run = 'echo $DEBUG'

[tasks.bar]
run = 'echo $DEBUG'

[tasks.prod]
env = {DEBUG = '0'}
depends = ['foo', 'bar']
run = 'echo $DEBUG'

[env]
DEBUG = '1'
```
```bash
$> mise r prod
[bar] $ echo $DEBUG
[foo] $ echo $DEBUG
[foo] 1
[bar] 1
[prod] $ echo $DEBUG
[prod] 0
```

It would be nice if it was possible to set DEBUG=0 for all dependent tasks of `prod`.

- per discussion at: https://discord.com/channels/1066429325269794907/1066429326687473776/1238442675783598181
- related: #1959
