### ISSUE TITLE
Make `$schema` a valid `.mise.toml` setting key

### ISSUE THREAD

**Issue by milas** [jdx/mise#2281]
At least in the JetBrains (IntelliJ) suite, it's possible to trigger JSON schema validation & autocomplete by associating a schema with the file by the `$schema` key.

However, this is not valid within the schema itself, causing the file to fail loading when used.

<img width="1261" alt="screenshot of IntelliJ showing a .mise.toml file with a $schema key and code completion" src="https://github.com/jdx/mise/assets/841263/df94d018-989b-4635-adc3-5fedaf6f0931">

```shell
mise error parsing config file: /path/to/.mise.toml
mise TOML parse error at line 1, column 1
  |
1 | "$schema" = 'https://raw.githubusercontent.com/jdx/mise/main/schema/mise.json'
  | ^^^^^^^^^
unknown field `$schema`, expected one of `min_version`, `dotenv`, `env_file`, `env`, `env_path`, `alias`, `tools`, `plugins`, `task_config`, `tasks`, `settings`
```

Here's how Starship has handled the issue in their schema:
https://github.com/starship/starship/blob/46b54ebc7d012908dc5ea7001d4d118cd14019bb/.github/config-schema.json#L6-L9
```json
"$schema": {
  "default": "https://starship.rs/config-schema.json",
  "type": "string"
}
```

(The default is a nice self-referential touch, but not necessary.)

**Comment by milas** [comment]
My workaround for the moment: keep the `"$schema"` at the top of the file, uncomment it while editing, and then re-comment it on save.

```toml
# HACK(milas): uncomment while editing to get autocomplete in IntelliJ
# "$schema" = 'https://raw.githubusercontent.com/jdx/mise/main/schema/mise.json'

[tools]
go = '1.22'
```
