### ISSUE TITLE
Support envars in plugin urls

### ISSUE THREAD

**Issue by jbadeau** [jdx/mise#2364]
Hello,

We have internal mise plugin repos that require authentications like:

[plugins]
release-cli = 'https://$TOKEN_USERNAME:$TOKEN@gitlab.com/foo/bar/asdf/release-cli.git'

We would line to request support for interpolating the envvars like $TOKEN_USERNAME

**Comment by roele** [comment]
Support should be added via [templates](https://mise.jdx.dev/templates.html#templates).

```toml
[plugins]
release-cli = 'https://{{env.TOKEN_USERNAME}}:{{env.TOKEN}}@gitlab.com/foo/bar/asdf/release-cli.git'
```
