### ISSUE TITLE
MISE_DATA_DIR not used during ansible task

### ISSUE THREAD

**Issue by herda05** [jdx/mise#2369]
**Describe the bug**
When setting  the value of MISE_DATA_DIR=/work/ansible/python into ~/.config/mise/config.toml and calling "mise install python@3.12.3" at the command line, an install of python is correctly done into /work/ansible/python.

However, running the same task within ansible using the command plugin installs python into ~/.local/share/mise/installs/python/3.12.3/bin/python even though mise finds the config.toml and seems to import the values.

ansible debug output:

```json
ok: [175.0.3.218] => {
    "msg": {
        "changed": true,
        "cmd": [
            "mise",
            "install",
            "python@3.12.3",
            "-v"
        ],
        "delta": "0:00:01.265897",
        "end": "2024-07-12 06:36:11.637798",
        "failed": false,
        "msg": "",
        "rc": 0,
        "start": "2024-07-12 06:36:10.371901",
        "stderr": "\u001b[0m\u001b[36m[DEBUG] \u001b[0mARGS: mise install python@3.12.3 -v\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mConfig {\n    Config Files: [\n        \"~/.config/mise/config.toml\",\n    ],\n}\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mToolRequestSet.build(11.117µs): ToolRequestSet: \n\n\u001b[0m\u001b[36m[DEBUG] \u001b[0minstall_versions: python@3.12.3\n\u001b[0m\u001b[33m[WARN] \u001b[0minstalling precompiled python from indygreg/python-build-standalone\n\u001b[0m\u001b[33m[WARN] \u001b[0mif you experience issues with this python (e.g.: running poetry), switch to python-build\n\u001b[0m\u001b[33m[WARN] \u001b[0mby running: mise settings set python_compile 1\ndownloading cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET Downloading https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz to ~/.local/share/mise/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mstarting new connection: https://github.com/\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mredirecting 'https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz' to 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/162334160/725a4f9a-b96d-471a-a8de-48eb372c729b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240712T063610Z&X-Amz-Expires=300&X-Amz-Signature=92b2d11797db83a6324d8adac7cbbad0381ed9cb67a745402caeb7e232a3e646&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=162334160&response-content-disposition=attachment%3B%20filename%3Dcpython-3.12.3%2B20240415-aarch64-unknown-linux-gnu-install_only.tar.gz&response-content-type=application%2Foctet-stream'\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mstarting new connection: https://objects.githubusercontent.com/\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz 200 OK\ninstalling cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz\n\u001b[0m\u001b[36m[DEBUG] \u001b[0mtar -xzf /home/ansadmin/.local/share/mise/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz -C /home/ansadmin/.local/share/mise/downloads/python/3.12.3\npython --version\n\u001b[0m\u001b[36m[DEBUG] \u001b[0m$ ~/.local/share/mise/installs/python/3.12.3/bin/python --version\nPython 3.12.3\nmise python@3.12.3 ✓ installed",
        "stderr_lines": [
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mARGS: mise install python@3.12.3 -v",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mConfig {",
            "    Config Files: [",
            "        \"~/.config/mise/config.toml\",",
            "    ],",
            "}",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mToolRequestSet.build(11.117µs): ToolRequestSet: ",
            "",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0minstall_versions: python@3.12.3",
            "\u001b[0m\u001b[33m[WARN] \u001b[0minstalling precompiled python from indygreg/python-build-standalone",
            "\u001b[0m\u001b[33m[WARN] \u001b[0mif you experience issues with this python (e.g.: running poetry), switch to python-build",
            "\u001b[0m\u001b[33m[WARN] \u001b[0mby running: mise settings set python_compile 1",
            "downloading cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET Downloading https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz to ~/.local/share/mise/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mstarting new connection: https://github.com/",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mredirecting 'https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz' to 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/162334160/725a4f9a-b96d-471a-a8de-48eb372c729b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240712T063610Z&X-Amz-Expires=300&X-Amz-Signature=92b2d11797db83a6324d8adac7cbbad0381ed9cb67a745402caeb7e232a3e646&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=162334160&response-content-disposition=attachment%3B%20filename%3Dcpython-3.12.3%2B20240415-aarch64-unknown-linux-gnu-install_only.tar.gz&response-content-type=application%2Foctet-stream'",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mstarting new connection: https://objects.githubusercontent.com/",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mGET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz 200 OK",
            "installing cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0mtar -xzf /home/ansadmin/.local/share/mise/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz -C /home/ansadmin/.local/share/mise/downloads/python/3.12.3",
            "python --version",
            "\u001b[0m\u001b[36m[DEBUG] \u001b[0m$ ~/.local/share/mise/installs/python/3.12.3/bin/python --version",
            "Python 3.12.3",
            "mise python@3.12.3 ✓ installed"
        ],
        "stdout": "",
        "stdout_lines": []
    }
}
```

output of ~/.config/mise/config.toml
```
[ansadmin@XXXXXX ~]$ cat .config/mise/config.toml
[env]
MISE_DATA_DIR="/var/ansible/work/python"
```

A reinstall on the command line actually picks up the value:
```
[ansadmin@XXXXXXX ~]$ mise install -f python@3.12.3 -v
[DEBUG] ARGS: /usr/local/bin/mise install -f python@3.12.3 -v
[DEBUG] Config {
    Config Files: [
        "~/.config/mise/config.toml",
    ],
}
[DEBUG] ToolRequestSet.build(10.486µs): ToolRequestSet:

[DEBUG] install_versions: python@3.12.3
[WARN] installing precompiled python from indygreg/python-build-standalone
[WARN] if you experience issues with this python (e.g.: running poetry), switch to python-build
[WARN] by running: mise settings set python_compile 1
downloading cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz
[DEBUG] GET Downloading https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz to /var/ansible/work/python/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz
[DEBUG] GET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz
[DEBUG] starting new connection: https://github.com/
[DEBUG] redirecting 'https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz' to 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/162334160/725a4f9a-b96d-471a-a8de-48eb372c729b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240712T064946Z&X-Amz-Expires=300&X-Amz-Signature=bd02374fb5140c66e081dd80499ce5c86a382b1a702a00da56e901327bf286b6&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=162334160&response-content-disposition=attachment%3B%20filename%3Dcpython-3.12.3%2B20240415-aarch64-unknown-linux-gnu-install_only.tar.gz&response-content-type=application%2Foctet-stream'
[DEBUG] starting new connection: https://objects.githubusercontent.com/
[DEBUG] GET https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz 200 OK
installing cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz
[DEBUG] tar -xzf /var/ansible/work/python/downloads/python/3.12.3/cpython-3.12.3+20240415-aarch64-unknown-linux-gnu-install_only.tar.gz -C /var/ansible/work/python/downloads/python/3.12.3
python --version
[DEBUG] $ /var/ansible/work/python/installs/python/3.12.3/bin/python --version
Python 3.12.3
mise python@3.12.3 ✓ installed
```

**To Reproduce**
create an ansible playbook with the following values:
```yaml   
    # Install mise on the system
    - name: Add mise globally for all users
      ansible.builtin.include_role:
        name: mise_en_place/install
        apply:
          tags: initial_install

    # create our mise user config
    - name: Create ansadmin local mise config
      ansible.builtin.file:
        path: /home/ansadmin/.config/mise/config.toml
        state: touch
        owner: ansadmin
        group: ansadmin

    # now use the ansible work dir as the place for a global version of python
    - name: update ansadmins mise settings
      ansible.builtin.lineinfile:
        path: /home/ansadmin/.config/mise/config.toml       
        line: "{{ item }}"
      with_items:
        - "[env]"
        - MISE_DATA_DIR="/var/ansibele/work/python"

    # This runs the mise trust command to trust the new config file
    - name: trust our new mise config
      become: true
      become_user: ansadmin
      ansible.builtin.command:
        cmd: "mise trust -v"
      register: trust_out

    # This makes sure mise is active for ansible
    - name: activate mise
      become: true
      become_user: ansadmin
      ansible.builtin.command:
        cmd: "mise activate -v"
      register: act_out

    # This does the actual install of the python version
    - name: "install python {{ python_version }} for everyone"
      become: true
      become_user: ansadmin
      ansible.builtin.command:
        cmd: "mise install python@{{ python_version }} -v"
      args:
        chdir: "/var/ansibele/work"
      register: inst_out
```

**Expected behavior**
When mise gets invoked with under ansible it should read in the values from the config.toml and install python into
/var/ansibele/work/python

**`mise doctor` output**

```text
[ansadmin@XXXXXXXX ~]$ mise dr
version: 2024.7.1 linux-arm64 (fd3cc16 2024-07-08)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 8 Jul 2024 03:39:55 +0000
  Rust Version: rustc 1.79.0 (129f3b996 2024-06-10)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.15(1)-release (aarch64-amazon-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs:
  data: /var/ansible/work/python
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: /var/ansible/work/python/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi

plugins:
  bun     (core)
  deno    (core)
  erlang  (core)
  go      (core)
  java    (core)
  node    (core)
  python  (core)
  ruby    (core)

toolset:


env_vars:
  MISE_DATA_DIR=/var/ansible/work/python
  MISE_SHELL=bash

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "/home/ansadmin/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Additional context**
I'm able to get around this by symlinking the directories for mise (.local/mise, ./local/share/mise, .config/mise, .cache/mise) to /var/ansible/work/python/ but that seems hackey.
