### ISSUE TITLE
Improve multiple env directive syntax

### ISSUE THREAD

**Issue by simonrouse9461** [jdx/mise#2392]
Currently we have to do this to set multiple .env files:
```toml
[[env]]
_.file = '.env'
[[env]]
_.file = '.env.local'
```

Is it possible to do this instead?
```toml
[env]
_.file = ['.env', '.env.local']
```

I feel the latter way is easier to configure and more intuitive.
