### ISSUE TITLE
`mise install ruby@3.1.6` fails on `manylinux_2_28-cross:aarch64` in GHA

### ISSUE THREAD

**Issue by sxlijin** [jdx/mise#2400]
Expected behavior: `mise install ruby@3.1.6` works (and it does, when I `docker run` the image locally!)

Actual behavior: it implodes with errors about openssl issues.

Workflow file:

```

jobs:
  mise-in-aarch64:
    runs-on: ubuntu-latest
    container: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64
    steps:
      - uses: actions/checkout@v4
      - run: apt install libreadline-dev
      - uses: jdx/mise-action@v2
        env:
          MISE_DEBUG: 1
        with:
          version: 2024.7.4
          mise_toml: |
            [tools]
            ruby = "3.1.6"
```

Workflow logs: https://github.com/BoundaryML/baml/actions/runs/10068077016/job/27832775620?pr=824
