### ISSUE TITLE
mise hints

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2460]
I think it would be great to add some "hints" to mise—like homebrew has if you're familiar. Here's a few ideas:

```
$ mise use python@3.9
[mise hint] install multiple python versions simultaneously with `mise use python@3.9 python@3.10`
```

multiple versions is useful specifically for python

```
$ mise plugins
[mise hint] see available plugins with `mise registry`
```

I see a lot of confusion that mise is more than just the set of core plugins.

Of course we can add more as we go. We could back this with a setting, maybe for each one as well as a global one to disable all of them.

**Comment by roele** [comment]
I like the idea. 

What settings structure would make sense for this?
```toml
# configure hint messages displayed when executing commands
hints_show = true
hints_commands = { use = true, plugins = true }
```

**Comment by jdx** [comment]
idk if confique supports this but I think it might be cool if we could have different types for `hints`:

```toml
# configure hint messages displayed when executing commands
hints = false
hints = { use = true, plugins = true }
```
