### ISSUE TITLE
task tools

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2487]
I want to see tools as part of tasks, I think this could be particularly useful for file tasks where you want to modify the tools used for just a particular task, e.g.:

```bash
#!/usr/bin/env bash
# mise tools = {node = "20"}
node -p "process.versions"
```

For example, maybe you have different scripts to test your project with different node versions.

**Comment by syhol** [comment]
This can be emulated today with the following...

in file task:
```bash
#!/usr/bin/env -S mise exec cue -- bash
cue version
```

in toml tasks:
```toml
[tasks.cueversion]
run = 'mise exec cue -- cue version'
```

However I still think it would be a good addition to have proper support for declaring tools as you mention.

**Comment by jdx** [comment]
it's worth thinking about how this would impact [`task_run_auto_install`](https://mise.jdx.dev/configuration/settings.html#task_run_auto_install). I'm thinking something like: if any task tools are defined, install those tools only instead of everything. This way this config could be used for both limiting the tools to install, and for adding extra tools.

`task_run_auto_install` also might be better as an array so you could set it to `[]` to disable the behavior or `["python"]` to only auto install python.

**Comment by reverendpaco** [comment]
Hi,  came here from my own discussion at #3574 

I had specifically asked the question over there around exactly this use-case.   I currently have a dozen combos of tasks, of this form:

```
[tools]
pandoc = "3.1.9"
typst = "0.12.0"

[tasks."pdf/latex/pandoc3.6"]
run = "mise exec pandoc@3.6  -- ./bin/to_pandoc3.6_latex_pdf.sh reference_pandoc3.6_latex.pdf"

[tasks."pdf/typst/pandoc3.6"]
run = "mise exec pandoc@3.6 typst@0.12.0 -- ./bin/to_pandoc3.6_typst_pdf.sh reference_pandoc3.6_typst.pdf"

[tasks."pdf/latex/pandoc3.1.9"]
run = "mise exec pandoc@3.1.9 -- ./bin/to_pandoc3.1.9_latex_pdf.sh reference_pandoc3.1.9_latex.pdf"
```
I.e. I have tasks which want to test combinations of different tool versions together.

I thought it would be great to be able to specify an attribute on the task itself which specifies which version of the tool.

```toml
[tasks."pdf/typst/pandoc3.6"]
use = [ "pandoc@3.6", "typst@0.12.0"]  # where "use" is only in effect during the task invocation
run = "./bin/to_pandoc3.6_typst_pdf.sh reference_pandoc3.6_typst.pdf"
```

So, if this is not implemented, please count this post as a "please" for such a feature.

**Comment by iilyak** [comment]
I am trying to use this feature and curious if it is possible to avoid duplication of version

```toml
[tools]
erlang = ['25.3.2.15']
scala = '2.13.15'

[tasks.lint]
depends = ["lint-erlfmt","lint-ec","lint-scalafmt"]

[tasks.lint-erlfmt]
tools.erlang = ???
run = "erlfmt --verbose --check"
```

I want to prevent errors when user would try `lint` when the dependencies are missing.
