### ISSUE TITLE
Support for `ubi` authenticated requests

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [jdx/mise#2529]
# Why?

Repeated calls to `ubi` require hitting Github several times, which causes rate limits.

# How?

In the `ubi` backend, allow `GITHUB_TOKEN` to be accessed.

**Comment by jimeh** [comment]
This can be worked around by setting a `GITHUB_API_TOKEN` environment variable.

However I'd like to suggest an alternative approach, namely a mise configuration option that can be set to a literal token, or a command to run to get a token. Then a token could be securely fetched from a password manager, and would also work when mise is invoked from editors or other tools outside of an interactive shell session.

For example, something like this:

```toml
[github.auth]
# Literal token
token = "ghp_<...>"
# Get token from 1Password CLI tool
token_command = "op item get 'GitHub PAT: mise' --fields label=token --reveal"
```
