### ISSUE TITLE
windows alternate tasks

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2595]
because shell commands work quite differently in windows, we could allow configuration for tasks specific to OS, such as:

```toml
[tasks.echo]
run = 'echo $FOO'
run_windows = 'echo %FOO%'
```

or maybe something like this:

```toml
[tasks.echo]
run = 'echo $FOO'
[tasks-windows.echo]
run = 'echo %foo%'
```

I think the former is what I prefer, though I can think of a few different ways to present this like maybe a `tasks.os.windows` key, though that would prevent anyone from having a task labeled "os" so it would have drawbacks.

**Comment by rodvieirasilva** [comment]
I am using Mise on Windows, and I encountered some difficulties with shell command compatibility. To address the differences in shell commands across operating systems, I propose adding an os.windows/os.unix section in the TOML configuration that can override any configuration. This approach allows users to specify OS-specific settings not only for tasks but for other sections as well, such as [settings], [tools], or any other sections that may benefit from customization.

The configuration would work as follows: when an OS-specific section (e.g., [os.windows]) is provided, it will inherit properties from the main configuration, but any properties specified in the OS-specific section will override the main configuration values. This enables users to customize tasks and tools with a high degree of flexibility while keeping platform-specific variations organized and easy to manage.

Example of Proposed Structure:
Base Configuration:
```toml
[tasks.clean]
description = "Clean the build directory before building"
run = '''
    echo "Cleaning..." > clean.log
'''
```
OS-Specific Override:

```toml
[os.windows]
[tasks.clean]
description = "Windows-specific clean task"
shell = "PowerShell" # specify shell for Windows

[os.unix]
[tasks.clean]
shell = "bash" # specify shell for Unix
```
Benefits:
Consistency and Clarity: Each task can inherit tags and configurations from the base [tasks] section, while also applying OS-specific overrides as needed.
Flexibility: Beyond tasks, any other configuration sections (e.g., [settings], [tools]) can be similarly customized with platform-specific values without impacting the main configuration.
Ease of Use: This structure keeps OS-specific commands and settings consolidated, making it straightforward to understand and modify configurations for different environments.
This approach balances flexibility and clarity, allowing projects to handle platform-specific configurations more seamlessly while minimizing redundancy.

If I receive an OK with this proposal, I can implement the issue.

Thanks.
