### ISSUE TITLE
task shell

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2596]
tasks are executed (I believe) with `sh -c` on unix and `cmd.exe \c` on windows but this should be customizable:

```toml
[tasks.echo]
run = 'echo $FOO'
shell = 'bash -c'
```
