### ISSUE TITLE
Dependency-tracking phony/pure tasks with no output files

### ISSUE THREAD

**Issue by quodlibetor** [jdx/mise#2621]
There are some tasks that don't create deterministic file system outputs (e.g. building docker images) but still have deterministic sources that define when they should be built.

I regularly make tasks that touch a file after success and use that file as the output to avoid unnecessary work in the future. It would, though, be really nice if I could tell mise that task outputs are "pure but non-existent" and have it manage the dependency tracking infrastructure for me.

**Comment by jdx** [comment]
I don't think I understand this. mise compares the input and the output to know whether or not something should be run. If there is no output, it would run it every time and be equivalent to not specifying any inputs at all.

**Comment by quodlibetor** [comment]
Yes, that makes sense, I didn't want to describe an implementation in the feature request, but to make it more clear:

What I was imagining is that it would be possible to state that a task is `pure` (instead of specifying outputs):

```toml
[tasks."build:docker"]
run = "docker build src"
sources = "src/**"
pure = true
```

as this is marked as pure, mise would track the last-build time for `task.build:docker` (maybe by creating a file in `~/.cache/mise/task-times/task.build:docker`, maybe by doing something else) and only re-run it if any of the sources are newer than that tracked time.

**Comment by jdx** [comment]
I'm open to having the ability to effectively automate this pattern:

```toml
[tasks.build]
sources = "src/**"
outputs = "/tmp/ran"
run = [
  "cargo b",
  "touch /tmp/ran",
]
```

mise could generate a hash somehow and use an internal file for this tracking. That said, I don't think `pure` describes this pattern. I don't have a good suggestion for an alternative but I was thinking maybe `auto_output = true` or `no_outputs = true`, or `touch_output = true`.

**Comment by quodlibetor** [comment]
awesome! I see your point about pure not being evocative enough, some ideas:

- `virtual_output` or `synthetic_output` -- just other prefixes akin to `auto_output`, also trying to make it clear that the output is not a thing that the user provides.
- `rerun_only_if_sources_changed = true` -- extraordinarily clear, but doesn't use the word output
- `implicit_output_tracking = true` -- for some reason I don't like this but might be a good compromise?

of this I think I like `auto_output` and `virtual_output` the best.

**Comment by quodlibetor** [comment]
An additional idea that teeters between being clear and confusing is using `auto_output = "mise"` -- the goal being to suggest that the output is automatic, and it is generated by mise.

**Comment by hverlin** [comment]
I have to say, I quite like the [Gradle API](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.tasks/-task-outputs/index.html) for inputs/outputs

To specify files, it's quite similar to `mise` (except `outputs` has several properties)
```groovy
outputs.files = ...
```
And it looks like this if we don't care about the output
```groovy
outputs.upToDateWhen { true }
```

I think `mise` could eventually have a custom task/command to determine if the output is up-to-date like Gradle. Example:
```toml
# always ok
outputs.upToDateWhen = true

# run a script that needs to return true/false
outputs.upToDateWhen = './my-script'
```

**Comment by jdx** [comment]
leave it to java to come up with a solution but it has 5 words

**Comment by quodlibetor** [comment]
Honestly that does suggest some possibly better options? Changing the value of `outputs` to a map would prevent accidentally setting both outputs and some other key, and is plausibly more future-compatible with scripts:

```toml
outputs = { auto = true }
outputs = { generated_by = "mise" }
```
