### ISSUE TITLE
use templates or resolve env vars in `python.default_packages_file`

### ISSUE THREAD

**Issue by m0lson84** [jdx/mise#2820]
**Describe the bug**

When installing a new version of Python the `python.default_packages_file` setting does not seem to be used to fine the path to the default packages file. This seems to be the case for both the TOML setting and environment variable.

**To Reproduce**

- Create a default packages file in a non-default path (example: ~/.config/mise/python) and set the `python.default_packages_file` setting to the same path.
- Install a new version of Python.
  - Should not attempt to install default packages.
- Create a new default packages file in the default path (~/.default-python-packages)
- Install a new version of Python.
  - Should now install default packages

**Expected behavior**

Expect the overridden default packages file path to be used when installing a new Python version.

**Contents of `config.toml`**

```toml
[tools]
go     = "1.23"
node   = "lts"
python = "3.13"

[settings]
env_file                 = ".env"
experimental             = true
go_default_packages_file = "${XDG_CONFIG_HOME}/mise/golang"

[settings.python]
default_packages_file = "${XDG_CONFIG_HOME}/mise/python"
```

**`mise doctor` output**

```text
version: 2024.10.10 linux-x64 (2024-10-25)
activated: yes
shims_on_path: yes

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Fri, 25 Oct 2024 20:58:39 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  go@1.23.2
  node@20.18.0
  python@3.13.0

env_vars:
  MISE_ENV_FILE=.env
  MISE_GO_DEFAULT_PACKAGES_FILE=~/.config/mise/golang
  MISE_NODE_DEFAULT_PACKAGES_FILE=~/.config/mise/nodejs
  MISE_PYTHON_DEFAULT_PACKAGES_FILE=~/.config/mise/python
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cache_prune_age = "30d"
  ci = false
  color = true
  debug = false
  disable_backends = []
  disable_default_registry = false
  disable_hints = []
  disable_tools = []
  env_file = ".env"
  experimental = true
  fetch_remote_versions_cache = "1h"
  fetch_remote_versions_timeout = "10s"
  go_default_packages_file = "~/.config/mise/golang"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = "30s"
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "~/.default-python-packages"
  quiet = false
  raw = false
  trace = false
  trusted_config_paths = []
  use_versions_host = true
  verbose = false
  yes = false

  [cargo]
  binstall = true

  [node]

  [pipx]
  uvx = false

  [python]
  default_packages_file = "~/.default-python-packages"
  pyenv_repo = "https://github.com/pyenv/pyenv.git"
  venv_auto_create = false
  venv_stdlib = false

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No warnings found
No problems found
```

**Comment by jdx** [comment]
this is a feature request, you can't use env vars like that in the field

**Comment by m0lson84** [comment]
Understood that I can't use `${XDG_CONFIG_HOME}` in the `config.toml`, but I am still seeing a difference in overriding the configuration of the Python plugin compared to the others that I'm using (go and node). I've updated my config to use absolute paths (showing `~` to denote home dir).

```
[tools]
go     = "1.23"
node   = "lts"
python = "3.13"

[settings]
env_file = ".env"
experimental  = true
go_default_packages_file = "~/.config/mise/golang"

[settings.python]
default_packages_file = "~/.config/mise/python"
```

This is the relevant portions from `mise doctor`:

```
toolset:
  go@1.23.2
  node@20.18.0
  python@3.13.0

env_vars:
  MISE_ENV_FILE=.env
  MISE_NODE_DEFAULT_PACKAGES_FILE=~/.config/mise/nodejs
  MISE_SHELL=zsh

settings:
  go_default_packages_file = "~/.config/mise/golang"
  python_default_packages_file = "~/.default-python-packages"

  [python]
  default_packages_file = "~/.default-python-packages"
```

I would expect to see both `python_default_packages_file` and `python.default_packages_file` to be the value provided in my `config.toml`.

**Comment by m0lson84** [comment]
I'm very much a noob when it comes to Rust, but I'd be happy to try my hand at creating a PR for this to gain more experience if that would be okay.

**Comment by jdx** [comment]
does this work? if not it should

```toml
[settings.python]
default_packages_file = "{{env.XDG_CONFIG_HOME}}/mise/python"
```

you might also want to take a look at [hooks](https://mise.jdx.dev/hooks.html) which could run `pip install ...`

**Comment by Pydronia** [comment]
This might be a different bug, but I noticed that when setting the default packages file settings via envs
```toml
[env]
# python
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-python-packages"
# node
MISE_NODE_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-npm-packages"
# go
MISE_GO_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-go-packages"
```
Installing new Node or Go versions correctly installs the default packages, however new python versions do not install the default packages. 

Using an absolute path, or (as suggested above) `{{env.HOME}}` works, but it looks like `~` isn't working correctly specifically for the python env setting.

I'm using 2024.12.5 macos-arm64.
