### ISSUE TITLE
postinstall is not run for mise exec

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#2877]
**Describe the bug**
- `postinstall` step is not run when using `mise exec`. 
- It also forces one to do `mise install --force <tool>` again if `mise x <tool>` was already run.

**To Reproduce**
```toml
[tools]
node = { version = "23", postinstall = 'corepack enable' }
```

Here is the current behavior
```shell
> mise x node -c 'pnpm -v'
mise node@23.1.0 ✓ installed 
zsh:1: command not found: pnpm

> pnpm
zsh: command not found: pnpm

> mise install
mise all runtimes are installed
```

**Expected behavior**
Using `mise x node -c 'pnpm -v'` I would expect:
- `mise` to install `node` specified in my `mise.toml` file
- run the `postinstall`
- successfully run `pnpm -v`

i.e. same behavior as:
```shell
mise install
mise x -c 'pnpm -v'
9.12.2
```

**mise version**
```
mise -v
2024.10.13 macos-arm64 (ee83488 2024-10-28)
```

**Comment by jdx** [comment]
We can fix this, but since node is in your config there isn't any need to also specify it on the command line. If you didn't include it then it would work.

**Comment by hverlin** [comment]
I have noticed that it's not always working as it should if I don't specify the tool. 
Let's say I only update `mise.toml` file and try to run `mise -x`.

Here is what happens:
```toml
[tools]
node = "23"
```

```shell
> mise x -c 'node -v'
mise WARN  missing: node@23.1.0
zsh:1: command not found: node
```

However, if I just type `node` it works (given that my shell had `mise` activated)
```shell
node
mise node@23.1.0 ✓ installed 
Welcome to Node.js v23.1.0.
Type ".help" for more information.
> 
```

**Comment by jdx** [comment]
Oh right, I forgot that is by design. It doesn't auto install if no other versions are installed

**Comment by hverlin** [comment]
For additional context, this is how I was thinking of using this. 
In GitLab CI, I was thinking I could just do:
```yaml
build:
  stage: build
  image: some-image-with-mise
  script: |
    mise x -c 'pnpm i'
```
without `mise install`
