### ISSUE TITLE
aliases for tool backend

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2885]
right now the `[aliases]` portion of `mise.toml` is designed for tool versions:

```toml
[alias.node]
lts = "20"
```

however, what we don't have is a way for us to do this with the tool backend:

```toml
[alias]
docuum = "cargo:docuum"
```

I'm not sure how we might want to present this. The above is my first thought, but it wouldn't allow having both aliased versions and aliased backend, so that would need to be figured out. A couple of alternatives:

```toml
[default_backends]
docuum = "cargo:docuum"
```

```toml
[registry]
docuum = "cargo:docuum"
```

"registry" might be ideal here since it maps reasonably well to the codebase, and maybe it could allow for alternate registries like we have for the old asdf-specific shortname stuff

**Comment by travbale** [comment]
I have what I think is a practical example of the usefulness of this.

I was trying to use the `ubi` backend with https://github.com/psastras/sarif-rs. The project publishes each cli tool it has as separate releases as opposed to a zip of all tools. I couldn't figure out a way to make it so I could grab multiple cli tools from the same source.

Something like perhaps:

```toml
[registry]
sarif-fmt = "ubi:psastras/sarif-rs"
shellcheck-sarif = "ubi:psastras/sarif-rs"

[tool]
sarif-fmt = "sarif-fmt-v0.6.6"
shellcheck-sarif = "shellcheck-sarif-v0.6.6"
```

That said my issue might be hinting more at a way to have multiple versions of the same tool (with an alias for the command) active at the same time.

**Comment by jdx** [comment]
thinking about this more I'm starting to prefer this as the config:

```toml
[alias]
docuum = "cargo:docuum"
[alias.node.versions]
lts = "20"
```

Then if you want to alias the name and the versions:

```toml
[alias.node]
name = "altnode"
versions = {lts = "20"}
```

Of course this would still do the same thing for backwards-compatibility, but I probably would remove it from the docs:

```toml
[alias.node]
lts = "20"
```
