### ISSUE TITLE
JSON schema needs some updates

### ISSUE THREAD

**Issue by powerman** [jdx/mise#2894]
Current schema does not know about:
```toml
[[env]]    # <-- this
  
[tasks.a]
shell = 'zsh -c'   # <-- and this
```
