### ISSUE TITLE
Print the command including the arguments

### ISSUE THREAD

**Issue by Hentioe** [jdx/mise#2921]
When outputting task commands, would it be more reasonable to display the arguments?

For example:

```toml
[tasks.dev-env]
run = "docker compose -f docker-compose.dev.yml"
```

Run it:

```bash
mise run dev-env up -d
```

Current output:

```plaintext
[dev-env] $ docker compose -f docker-compose.dev.yml
...
```

The actual command to run (should include arguments):

```plaintext
[dev-env] $ docker compose -f docker-compose.dev.yml up -d
...
```
