### ISSUE TITLE
keep tools sorted

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3140]
if the tools in mise.toml are already sorted, e.g.:

```toml
[tools]
a = '1'
c = '3'
d = '4'
```

then running `mise use b@2` should insert it between "a" and "b". In the case where they are not sorted, the current behavior where it gets added to the end should be retained.
