### ISSUE TITLE
Auto run task on hook-env

### ISSUE THREAD

**Issue by miguelmig** [jdx/mise#3183]
Any plans to allow running a task automatically upon entering a certain directory?

**Comment by jdx** [comment]
I'm thinking we could have a few different kind of events:

```toml
[events]
enter = 'mise run when-i-enter-the-project'
leave = 'mise run when-i-leave-the-project'
cd = 'mise run on-any-cwd-change'
preinstall = 'mise run before-i-install-something'
postinstall = 'mise run after-i-install-something'
```
