### ISSUE TITLE
Request for cookbook contributions

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3304]
I'd like to create a cookbook section for the docs. Show me parts of your mise.toml you think are interesting.

In particular I think tasks would be really helpful for people to see examples of.

**Comment by hverlin** [comment]
There is already an example for a Node.js project here (https://mise.jdx.dev/templates.html#a-node-js-project). Here is what I usually do with `pnpm`. This ensures that dependencies are installed before running any scripts in the `package.json`.
```toml
[tools]
node = '22'

[tasks.pnpmInstall]
alias = 'pi'
description = 'Installs dependencies with pnpm'
run = 'corepack enable && pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'node --run dev'
depends = ['pnpmInstall']

[tasks.nodeRun]
alias = 'nr'
description = 'Call any script in your package.json file. Example: mise nr lint'
run = 'node --run {{arg(name="script")}}'
depends = ['pnpmInstall']
```

Note that `pnpm run` will support such feature behind a setting in the next release (https://github.com/pnpm/pnpm/issues/8585)

**Comment by syhol** [comment]
presets: https://github.com/jdx/mise/issues/3320#issuecomment-2510282208

**Comment by erickguan** [comment]
For additional context on the "template documentation". I wrote a few to demonstrate templates without readers needed to try in mise.toml.

I would merge them into cookbooks to demonstrate the real world setup.

I would also reduce the template documentation examples when cookbooks have good examples.

**Comment by hverlin** [comment]
Agree that the existing examples could be moved to cookbooks now. We can do a page for each language (example: one page for Node.JS, one for terraform, one for python, etc.)

Also, when seeing `templates` the first time in the sidebar, I thought this was going to be a page showing some example projects using `mise`. I think the page should probably be renamed to something like `Templating` or `Templating mise.toml files`

**Comment by syhol** [comment]
Mise search

https://github.com/jdx/mise/issues/3364#issue-2719788807

```toml
[tasks.search]
run = "mise use --pin $(mise registry -b aqua | fzf --multi | awk '{print $2}')"
```

Might want to adapt it to not be aqua specific

**Comment by syhol** [comment]
I know skim can be imported as a library and has a very similar feature set to fzf.

**Comment by jdx** [comment]
we don't need no skim, we have [demand](https://github.com/jdx/demand)

**Comment by syhol** [comment]
> we don't need no skim, we have [demand](https://github.com/jdx/demand)

Not sure I trust the author of that library. I hear bad things 👀

**Comment by jdx** [comment]
this is a way to convert from `.tool-versions` to `mise.toml`:

```
cat ~/.tool-versions | tr ' ' '@' | xargs -n2 mise use -g
```

though I'd like this to be a part of `mise config generate`, which maybe should be `mise generate config` to match the other generators

**Comment by syhol** [comment]
I've been using docker to debug issues in a clean environment over the weekend:
```toml
[tasks.docker]
run = "docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest"
```
Puts me in a fresh debian shell with mise installed. I then normally run the following manually:
```console
❯ mise docker
[docker] $ docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest
latest: Pulling from jdxcode/mise
Digest: sha256:eecc479b6259479ffca5a4f9c68dbfe8631ca62dc59aa60c9ab5e4f6e9982701
Status: Image is up to date for jdxcode/mise:latest
root@75f179a190a1:/mise# eval "$(mise activate bash)"
root@75f179a190a1:/mise# echo "" >/mise/config.toml
root@75f179a190a1:/mise# mise prune --yes
mise pruned configuration links
mise python@3.13.1 ✓ remove /mise/cache/python/3.13.1
```
But it might be nice to automate that bit too.
