### ISSUE TITLE
Print stdout from postinstall hook

### ISSUE THREAD

**Issue by Ernest0-Production** [jdx/mise#3308]
It's not obvious whether the postinstall hook worked:
```toml
[tools]
my_tool = { version = "1", postinstall = "echo 'Hello'" }

[hooks]
postinstall = "echo 'Hello'"
```

To understand that
- it does work for me
- it's only called on first install (or with --force flag)
I had to use `touch new_file.txt` to learn this functionality.

I'd like the output of the script in `postinstall` to be printed to stdout as well

-----

Real use case scenario:
```
[tools]
git-lfs = { version = "3.6.0", postinstall = "git lfs install" }

[alias]
git-lfs = "asdf:https://github.com/DanieleIsoni/asdf-git-lfs"
```
