### ISSUE TITLE
run task directly in hook

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3314]
basically:

```toml
[hooks]
postinstall = {task = "build"}
```

this would make things a bit faster since mise wouldn't need to run a second time with `mise -q build`
