### ISSUE TITLE
Automatically remove asdf Rust plugin when upgrading to the version with the built-in Rust plugin

### ISSUE THREAD

**Issue by trustin** [jdx/mise#3315]
**Describe the bug**

Since mise has built-in Rust plugin (v2024.11.31), mise fails to self-update with the following ambiguous error:

```
Updated mise to 2024.11.37
mise ERROR [usage] plugin update
mise ERROR [rust] plugin update
mise ERROR 2 plugins failed to update
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
mise ERROR command ["/home/trustin/.local/bin/mise", "plugins", "update"] exited with code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

**To Reproduce**

1. Install mise older than v2024.11.31.
2. Install asdf-rust plugin and install a Rust version.
3. Run `mise self-update`

**Expected behavior**

When asdf-rust plugin is installed, remove it automatically or suggest its removal while updating plugins.

**`mise doctor` output**

`mise doctor` reports 'no problem' with a warning, which probably should be an error?

```text
version: 2024.11.37 linux-x64 (7ac5ab3 2024-11-30)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Sat, 30 Nov 2024 01:03:00 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.9 (x86_64-pc-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  rust   git@github.com:code-lever/asdf-rust.git#95acf4f
  usage  git@github.com:jdx/mise-usage.git#fe3888a

toolset:
  asdf:rust@1.82.0
  asdf:usage@1.3.3
  cargo:grcov@0.8.20
  cargo:hwatch@0.3.18
  cargo:svgbob_cli@0.7.3
  core:java@temurin-21.0.5+11.0.LTS
  core:node@22.11.0
  ubi:cargo-bins/cargo-binstall@1.10.14

env_vars:
  MISE_SHELL=zsh

settings:
  cargo_binstall  true ~/.config/mise/config.toml

1 warning found:

1. plugin rust overrides a core plugin

No problems found
```

**Additional context**

My `~/.config/mise/config.toml`:

```toml
❯ cat ~/.config/mise/config.toml
[settings]
cargo_binstall = true

[tools]
cargo-binstall = "latest"
"cargo:grcov" = "latest"
"cargo:hwatch" = "latest"
"cargo:svgbob_cli" = "latest"
usage = "latest"
node = "22"
java = "temurin-21"
rust = { version = "1", postinstall = "rustup component add rust-src rust-analyzer llvm-tools" }
```
