### ISSUE TITLE
Preset support

### ISSUE THREAD

**Issue by noirbizarre** [jdx/mise#3320]
`mise` is awesome tool to make dev environments replayable. But as soon as you are working on a lot of different projects, doing frequent small contributions to projects you don't own, it comes an initialization cost. 
In my case, on Python projects, I have to redo those tasks for each project:
- set python version using `mise use python@version`
- use the right package management tool using `mise use pdm|poetry@latest`
- edit `mise.toml` to add `_.python.venv = { path = ".venv", create = true }`
- display a prompt to have the venv created
- install tools in venv
- define some common tasks

My idea is that it could be factorized using preset, defined like this:

```toml
[preset.python.env]
_.python.venv = { path = ".venv", create = true }

[preset.python.tools]
pre-commit = "latest"

[preset.python.tasks.lint]
run = "pre-commit run -a"

[preset.pdm.tools]
preset = "python"
pdm = "latest"

[preset.pdm.hooks]
postinstall = "pdm sync"

[preset.poetry.tools]
preset = "python"
poetry = "latest"

[preset.poetry.hooks]
postinstall = "poetry sync"
```

Then, when entering on a new project, I could just do `mise use preset@pdm python@3.12` and be ready to contribute.
It would result in the following `mise.toml` content:

```toml
[tools]
preset = "pdm"
python = "3.12"
```

I suggest using a special `preset` tool as:
- it allows reusing the `mise use` command
- it doesn't create an extra dedicated section
- it already supports multiple preset (aka. `preset = ["python", "typescript"]`)

Using the `.config/mise/conf.d/*.toml` layout, it would allow to defined single file preset like this:
`.config/mise/conf.d/preset-python.toml`
```toml
[preset.python.env]
_.python.venv = { path = ".venv", create = true }

[preset.python.tools]
pre-commit = "latest"

[preset.python.tasks.lint]
run = "pre-commit run -a"
```

**Comment by syhol** [comment]
You can create something pretty similar with tasks:

I created the file `~/.config/mise/tasks/preset/python` with a `chmod +x`:
```bash
#!/usr/bin/env bash
#MISE dir="{{cwd}}"

touch mise.toml
mise trust
mise use pre-commit
mise config set env._.python.venv.path .venv
mise config set env._.python.venv.create true -t bool
mise config set tasks.lint.run "pre-commit run -a"
```

and `~/.config/mise/tasks/preset/pdm` with a `chmod +x`:
```bash
#!/usr/bin/env bash
#MISE dir="{{cwd}}"
#MISE depends=["preset:python"]
#USAGE arg "<version>"

touch mise.toml
mise trust
mise use python@$usage_version
mise use pdm@latest
mise config set hooks.postinstall "pdm sync"
```

Then in any directory you can run `mise preset:python 3.10`

```console
Code/sandbox/mise-presets
❯ mise preset:pdm 3.10
[preset:python] $ ~/.config/mise/tasks/preset/python
mise WARN  No untrusted config files found.
mise ~/Code/sandbox/mise-presets/mise.toml tools: pre-commit@4.0.1
[preset:pdm] $ ~/.config/mise/tasks/preset/pdm 3.10
mise WARN  No untrusted config files found.
mise ~/Code/sandbox/mise-presets/mise.toml tools: python@3.10.15
mise ~/Code/sandbox/mise-presets/mise.toml tools: pdm@2.21.0
mise creating venv with uv at: ~/Code/sandbox/mise-presets/.venv
Using CPython 3.10.15 interpreter at: /Users/simon/.local/share/mise/installs/python/3.10.15/bin/python
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate.fish

Code/sandbox/mise-presets via 🐍 v3.10.15 (.venv)
❯
```

and mise.toml is generated:

```toml
[tools]
pdm = "latest"
pre-commit = "latest"
python = "3.10"

[env]

[env._]

[env._.python]

[env._.python.venv]
path = ".venv"
create = true

[tasks]

[tasks.lint]
run = "pre-commit run -a"

[hooks]
postinstall = "pdm sync"
```

The generated TOML is a little messy with unnecessary tables, but it all works as expected. We could create a bug issue for that.

I think this would fit really well in the [new cookbook](https://mise.jdx.dev/mise-cookbook.html)
