### ISSUE TITLE
Consider merging hooks into tasks

### ISSUE THREAD

**Issue by dudicoco** [jdx/mise#3333]
Hi,

It would be great if we could define within a task if it should run as a hook as well instead of having separate definitions for hooks.

With the new hooks feature I can run some commands when files changed:
```toml
[hooks]
[[watch_files]]
patterns = [".mise.toml"]
run = "mise install"

[[watch_files]]
patterns = ["pyproject.toml", "uv.lock"]
run = "uv sync"

[[watch_files]]
patterns = ["package.json", "pnpm-lock.yaml"]
run = "pnpm install"
```

This is great, but there are a few problems:
1. The hooks won't run when I enter the repository, so I need to add another hook:
```toml
enter = "mise install && uv sync && pnpm install"
```
2. I can't run these hooks in CI
3. The hooks run sequentially while I could run uv sync and pnpm install in parallel

As a workaround, we could do the following:
```toml
[tasks.mise-install]
sources = ['.mise.toml']
run = "mise install"

[tasks.uv-sync]
sources = ["pyproject.toml", "uv.lock"]
depends = ["mise-install"]
run = "uv sync"

[tasks.pnpm-install]
sources = ["package.json", "pnpm-lock.yaml"]
depends = ["mise-install"]
run = "pnpm install"

[tasks.all]
depends = ["mise-install", "uv-sync", "pnpm-install"]

[hooks]
enter = "mise run all"

[[watch_files]]
patterns = [".mise.toml"]
run = "mise run mise-install"

[[watch_files]]
patterns = ["pyproject.toml", "uv.lock"]
run = "mise run uv-sync"

[[watch_files]]
patterns = ["package.json", "pnpm-lock.yaml"]
run = "mise run pnpm-install"
```

We now have some unnecessary duplication.

What I suggest is to add a new field within tasks to also run them as a hook:
```toml
[tasks.mise-install]
sources = ['pyproject.toml']
run = "mise install"
hook = "watch"

[tasks.uv-sync]
sources = ["pyproject.toml", "uv.lock"]
depends = ["mise-install"]
run = "uv sync"
hook = "watch"

[tasks.pnpm-install]
sources = ["package.json", "pnpm-lock.yaml"]
depends = ["mise-install"]
run = "pnpm install"
hook = "watch"

[tasks.all]
depends = ["mise-install", "uv-sync", "pnpm-install"]
hook = "enter"
```
