### ISSUE TITLE
Invalid type: string in asdf-gitlfs

### ISSUE THREAD

**Issue by Ernest0-Production** [jdx/mise#3348]
**Describe the bug**

My mise config looks like this:
```toml
[tools]
tuist = "4.36.0"
swiftlint = "0.54.0"
swiftgen = "6.6.3"
ruby = "3.2.2"
xcodes = "1.6.0"
bundler = "2.4.13"
eza = "0.18.23"
xchtmlreport = "2.5.0"
xcbeautify = "2.15.0"
git-lfs = { version = "3.6.0", postinstall = "git lfs install" }
xcresults = "1.19.1"
allure = "2.32.0"
"spm:mikeger/XcodeSelectiveTesting" = "0.11.0"


[alias]
git-lfs = "asdf:https://github.com/DanieleIsoni/asdf-git-lfs"
xcresults = "asdf:https://github.com/Ernest0-Production/asdf-xcresults"

[settings]
yes = true
activate_aggressive = true
experimental = true

```

This in some case produce error:
```
Message:  [36mcalled `Result::unwrap()` on an `Err` value: 
    0: [91merror parsing config file: [1m~/workspace/PR-8112@94/.mise/config.toml[0m[0m
    1: [91mTOML parse error at line 69, column 11
    1:    |
    1: 69 | git-lfs = "asdf:https://github.com/DanieleIsoni/asdf-git-lfs"
    1:    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    1: invalid type: string "asdf:https://github.com/DanieleIsoni/asdf-git-lfs", expected a map
    1: [0m
 
 Location:
    [35msrc/config/config_file/mise_toml.rs[0m:[35m92[0m
 
 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
 Run with RUST_BACKTRACE=full to include source snippets.[0m
 Location: [35msrc/config/mod.rs[0m:[35m60[0m
```

**To Reproduce**

I can't reproduce this error myself. It happens in my Jenkins CI.

I don't get any error when calling `mise install`. At some point when trying to call `bundle exec fastlane <some_lane>` it gives me this error.

**Expected behavior**

Not exception

**`mise doctor` output**

```text
version: 2024.11.37 macos-arm64 (7ac5ab3 2024-11-30)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Sat, 30 Nov 2024 01:03:28 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  cache: ~/Library/Caches/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml
  ~/path/to/project/Gemfile
  ~/path/to/project/.mise/config.toml
  ~/path/to/project/.mise.local.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  allure        https://github.com/comdotlinux/asdf-allure.git#1e8bd7a
  bundler       https://github.com/jonathanmorley/asdf-bundler.git#a461ac4
  create-dmg    https://github.com/tuist/asdf-create-dmg.git#de7c6c1
  eza           https://github.com/lwiechec/asdf-eza.git#11f578d
  git-cliff     https://github.com/jylenhof/asdf-git-cliff.git#f274b35
  pnpm          https://github.com/jonathanmorley/asdf-pnpm.git#85221d3
  sonarscanner  https://github.com/virtualstaticvoid/asdf-sonarscanner#c42dd95
  sourcedocs    https://github.com/tuist/asdf-sourcedocs#1d8b6b7
  swiftformat   https://github.com/younke/asdf-swiftformat.git#ab1f91f
  swiftgen      https://github.com/younke/asdf-swiftgen.git#072ce84
  swiftlint     https://github.com/klundberg/asdf-swiftlint.git#447f94c
  tuist         https://github.com/asdf-community/asdf-tuist.git#44c87b2
  xcbeautify    https://github.com/mise-plugins/asdf-xcbeautify.git#48563a3
  xchtmlreport  https://github.com/younke/asdf-xchtmlreport.git#139fb86
  xcodes        https://github.com/younke/asdf-xcodes.git#9f037bf

toolset:
  asdf:allure@2.32.0
  asdf:bundler@2.4.13
  asdf:eza@0.18.23
  asdf:https://github.com/DanieleIsoni/asdf-git-lfs@3.6.0
  asdf:https://github.com/Ernest0-Production/asdf-xcresults@1.19.1
  asdf:swiftgen@6.6.3
  asdf:swiftlint@0.54.0
  asdf:tuist@4.36.0
  asdf:xcbeautify@2.15.0
  asdf:xchtmlreport@2.5.0
  asdf:xcodes@1.6.0
  core:node@22.9.0
  core:ruby@3.2.2
  spm:mikeger/XcodeSelectiveTesting@0.11.0

env_vars:
  MISE_SHELL=zsh

settings:
  experimental         true ~/.config/mise/config.toml
  activate_aggressive  true ~/path/to/project/.mise/config.toml
  experimental         true ~/path/to/project/.mise/config.toml
  yes                  true ~/path/to/project/.mise/config.toml

No problems found
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.
