### ISSUE TITLE
Universal (project-language-dependent) task

### ISSUE THREAD

**Issue by eugenesvk** [jdx/mise#3399]
Would be great to be able to have a single conditional formatting command which you could commit to any project (or maybe just your global config) that would run a command dependent on the local project's language resolution (if it's set)

So `mise run format` would run
  - formatting with `cargo fmt --all` in a rust project
  - formatting with `go fmt` in a go project
  - formatting with `ruff check --fix **.py` in a python project
  - ...

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a new 'format' task to mise.toml that conditionally runs formatting commands based on the project's detected language.

You can review changes in this commit: https://github.com/mnmnk43434/jdx-mise-3399/commit/e0dd2ceac80815bbe731fa2c4516a44f528c737c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jdx** [comment]
can't you just create a global command that does this? I don't see what mise should do here

**Comment by eugenesvk** [comment]
How would I depend on existing tasks depending on the current project's resolved tool?

My idea was that you define commands like 
```toml
[tasks.fmt_rust]
run = ['cargo fmt {{arg(name="cargo_fmt_scope",var=false,default="--all")}}',]
```
```toml
[tasks.fmt_go]
run = ['go fmt',]
```

And then the global command would call this specific project's `check`
```toml
[tasks.fmt_any]
depends_if_Rust = ['fmt_rust']
depends_if_Go   = ['fmt_go']
```

So mise would evaluate the conditions and the ability to call via specifying existing mise tasks
