### ISSUE TITLE
hooks for shell code

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3412]
from an HN comment https://news.ycombinator.com/item?id=42359359

here's my idea:

```toml
[hooks.enter]
shell = true
run = ". completions/mycli.sh"
```

it's worth considering though that this would likely only work well in a single shell, so there would need to be a way to only run this in bash, maybe this instead:

```toml
[[hooks.enter]]
shell = "bash"
run = ". completions/mycli.sh"
```

but we'd need to make the hooks accept arrays, which probably isn't a bad idea anyways
