### ISSUE TITLE
Task `tools`-dependencies

### ISSUE THREAD

**Issue by Ernest0-Production** [jdx/mise#3438]
I would like to be able to explicitly specify the dependency of not only one task on another, but also on the list of tools that need to be installed before that.

Sometimes there is no need to install the entire set of tools.

**Comment by jdx** [comment]
you can already do this:

```toml
[tasks.setup]
run = "mise install node python"
```

just disable [task.run_auto_install](https://mise.jdx.dev/configuration/settings.html#task_run_auto_install)

**Comment by syhol** [comment]
Another way to do this would be to use mise exec inside a task:
```toml
[tasks.monitor]
run = "mise exec viddy@1.0.1 kubectl@1.31.3 -- viddy kubectl get pods"
```
This would also install the project tools though.
