### ISSUE TITLE
Use regular argument vector for passing files to `pre-commit` tasks

### ISSUE THREAD

**Issue by joshbode** [jdx/mise#3446]
With the default `pre-commit` hook generated by #3410, the staged files are provided to the referenced task via the `STAGED` environment variable, which makes passing files with whitespace difficult since space is being used as the delimiter.

If we used something like this for the pre-commit hook template we could pass the arguments to the task, which can then simply use `"$@"` and friends to process the staged files and avoid quoting issues:

```sh
#! /bin/sh

set -eu

PIPE=$(mktemp -u mise.pre-commit.XXXXXXXX)
mkfifo -m 600 "${PIPE}"

cleanup() {
  rm -f "${PIPE}"
}
trap 'cleanup' EXIT INT TERM

git diff-index --cached --name-only HEAD > "${PIPE}" &
while read -r ARG; do
  set -- "$@" "${ARG}"
done < "${PIPE}"

exec mise run {task_name} "$@"
```

By doing this, we can support a use-case something like [husky](https://typicode.github.io/husky/) + [lint-staged](https://github.com/lint-staged/lint-staged) and have dependent sub-tasks to the pre-commit, which could feed the arguments to the sub-tasks (not the current behaviour, I believe) which can then filter the arguments using `sources` (not the current behaviour, I believe) or similar.

Something like this:
```toml
[tasks.eslint]
sources = ["app/**/*.ts", "app/**/*.tsx", "app/**/*.js"]
run = '''eslint --fix "$@"'''

[tasks.sqlfluff]
sources = ["app/**/*.sql"]
run = '''sqlfluff fix "$@"'''

[tasks.pre-commit]
depends = ["eslint", "sqlfluff"]
```

Compared to this setup in `package.json` for `lint-staged`:
```
{
  "scripts": {
    "pre-commit": "lint-staged"
  }
  "lint-staged": {
    "app/**/*.(js|ts|tsx)": [
      "eslint --fix"
    ],
    "app/**/*.sql": [
      "sqlfluff fix"
    ]
  },
}
```
which we use with a pre-commit for `husky`:
```sh
#! /bin/sh
npx lint-staged -q
```

**Comment by jdx** [comment]
I think the current functionality works ok, the spaces are escaped so you should be able to use `$*` in a script to get all the files

**Comment by jdx** [comment]
sorry I got mixed up a bit, it's an env var so I think this should work:

```toml
[tasks.eslint]
sources = ["app/**/*.ts", "app/**/*.tsx", "app/**/*.js"]
run = '''eslint --fix $STAGED'''
```

**Comment by joshbode** [comment]
that won't work if the file has spaces:
```
[tasks.pre-commit]
run = '''printf '+ %s\n' $STAGED'''
```

```
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .mise.toml
        modified:   xxx/a b.txt

$ git commit -am "dummy"
[pre-commit] $ printf '+ %s\n' $STAGED
+ .mise.toml
+ xxx/a
+ b.txt
```

**Comment by joshbode** [comment]
BTW, I've (belatedly) realised that `$@` doesn't actually resolve to anything:
```toml
[tasks.test]
run = '''printf '+ %s\n' start "$@" end'''
```
yields the following:
```
$ mise run test 1 2 "3 4"
[test] $ printf '+ %s\n' start "$@" end 1 2 3 4
+ start
+ end
+ 1
+ 2
+ 3 4
```
which I presume is because the arguments are being templated in.

I'd assumed that the command being run was something like:
```
{shell} "{run}" -- "$@"
```
(with `shell = "sh -c"`) but maybe it's more like this?
```
{shell} "{run} $@"
```

if it was the former I don't think the command would even need to be trimmed:
```
$ sh -c '
printf "%s\n" start "$@" end
' -- 1 2 "3 4"

start
1
2
3 4
end
```
vs:
```
$ sh -c '
printf "%s\n" start "$@" end
1 2 "3 4"'

start
end
sh: line 2: 1: command not found
```

**Comment by jdx** [comment]
I wanted to go with env vars because I feel it could be more extensible to add things later like ADDED or DELETED—but I can't see a good way to escape the spaces unless we use a delimiter like ":" but that's probably going to be just as annoying to read back in.

I believe this is the code where we concat the args together:

https://github.com/jdx/mise/blob/5d17c3472fbe5f68489d92ec64fa3fc9bddb9c1c/src/cli/run.rs#L492

**Comment by joshbode** [comment]
I think if it was more like this (pseudocode - I don't know Rust well enough!) it would like I'm expecting:
```
full_args = [shell, script, "--", ...args];  // the "--" is to tell the shell that the remaining args are all to go to $@
```
it's possibly going to break some existing tasks if they're relying on the arguments to be magically concatenated, though

**Comment by jdx** [comment]
so I think you're thinking about this as a user that is running a shell script as a "script" but that's actually not the most common way to use tasks. Commonly people will do this:

```toml
[tasks.build]
run = "npm run build"
```

the way mise works is you can call `mise run build foo bar` and (I think) that ultimately results in `sh -c "npm run build foo bar"`. `$@` isn't the way this is supposed to be used, the arguments just get concatenated onto the last line of the script.

I think in your other thread you were doing something with `$@` but that actually won't be anything, you'll end up with `npm run "$@" foo bar` ultimately with nothing in `$@`. So it works, but not for the reason you thought.

**Comment by jdx** [comment]
of course if you want more control you should be actually defining the arguments: https://mise.jdx.dev/tasks/toml-tasks.html#positional-arguments

**Comment by joshbode** [comment]
ah - I missed that in the docs. I'm not sure it's quite right for my use-case, though - I can't see how to process arguments with a spaces in them:

```toml
[tasks.test-no-quote]
run = '''printf '+ %s\n' start {{arg(var=true)}} end'''

[tasks.test-quote]
run = '''printf '+ %s\n' start "{{arg(var=true)}}" end'''

[tasks.test-array]
shell = "bash -c"
run = '''ARGS=({{arg(var=true)}})
printf '+ %s\n' start "${ARGS[@]}" end'''
```

```
❱ mise run test-no-quote 1 2 "3 4"
[test-no-quote] $ printf '+ %s\n' start 1 2 3 4 end
+ start
+ 1
+ 2
+ 3
+ 4
+ end

❱ mise run test-quote 1 2 "3 4"
[test-quote] $ printf '+ %s\n' start "1 2 3 4" end
+ start
+ 1 2 3 4
+ end

❱ mise run test-array 1 2 "3 4"
[test-array] $ ARGS=(1 2 3 4)
+ start
+ 1
+ 2
+ 3
+ 4
+ end
```
