### ISSUE TITLE
Take into account the task definition for the up-to-date check

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#3499]
```toml
[tasks.test]
run = 'python test.py > test.txt'
sources = ['test.py']
outputs = ['test.txt']
```

If I change the task definition, the task still appears to be up-to-date. 

```toml
[tasks.test]
run = 'python -v test.py > test.txt'
# ...
```

```shell
❯ mise run test
[test] sources up-to-date, skipping
```

I believe that the task definition itself should be included in the up-to-date check
