### ISSUE TITLE
`--no-config`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3580]
mise should have a `--no-config` flag, it'd allow something like this:

```toml
[env]
USR="{{exec(command='mise x --no-config vault -- vault kv get -address=http://localhost:8200 -mount test -field=usr myapp')}}"
```

where normally you couldn't do that because mise would endlessly loop
