### ISSUE TITLE
os field on backends in registry

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3624]
instead of this:

```toml
bat.backends = ["ubi:sharkdp/bat", "asdf:https://gitlab.com/wt0f/asdf-bat"]
bat.os = ["linux"]
```

do this
```toml
bat.backends = [{backend = "ubi:sharkdp/bat", os = ["linux"]}, "asdf:https://gitlab.com/wt0f/asdf-bat"]
```
