### ISSUE TITLE
un-nest `mise run` outputs inside tasks

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3674]
currently this happens:

```toml
[a]
run = "echo a"
[b]
run = ['mise run a', 'echo b']
[c]
depends = ['a', 'b']
run = ['mise run a', 'mise run b', 'echo c']
```

```
> mise run c
[a] $ echo a 
[a] a
[a] finished in 104.5ms
[c] $ mise run a 
[c] [a] $ echo a 
[c] a
[c] $ mise run b 
[c] [build] $ cargo build --all-features 
[c]     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
[c] $ echo c 
[c] c
[c] finished in 1.82s
Finished in 13.88s
```

the whole `[c] [a]` thing is correct but we should probably just flatten it to `[a]`
