### ISSUE TITLE
Autocompletion does not work for `mise <task>` shorthand when task name is quoted

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#3678]
```toml
[tasks."test"]
run = "echo 'Running test'"
```

`fish`

![image](https://github.com/user-attachments/assets/6fe71abe-22c6-4185-bca6-b6391eb184cb)

`zsh`

![image](https://github.com/user-attachments/assets/51893e0d-d3a4-474f-b0a7-5091cb065e89)

If I select the suggestion, I get 
```sh
mise \"tes 
```

When using  `mise run <task>`, the autocompletion works correctly
