### ISSUE TITLE
More complete mise task toml support

### ISSUE THREAD

**Issue by reteps** [jdx/mise#3700]
```
#!/usr/bin/env bash
set -e

#USAGE flag "-c --clean" help="Clean the build directory before building"
#USAGE flag "-p --profile <profile>" help="Build with the specified profile" {
#USAGE   choices "debug" "release"
#USAGE }
#USAGE flag "-u --user <user>" help="The user to build for"
#USAGE complete "user" run="mycli users"
#USAGE arg "<target>" help="The target to build"

if [ "$usage_clean" = "true" ]; then
  cargo clean
fi

cargo build --profile "${usage_profile:-debug}" --target "$usage_target"
```

In this snippet, I can define flags with help messages, shorthand flags, and choices. The current .toml support is quite limited:

```
[tasks.test]
run = 'cargo test {{option(name="file")}}'
```

I propose a section called `flags` that lets you do deeper customization.

```toml
[tasks.test]
flags = { mything = {
alias = ["-c"]
help =["more info"]
choices = ["debug", "release"]
} }
run = 'cargo test {{option(mything)}}'
```
