### ISSUE TITLE
method for running tasks in series

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3750]
I've been trying to avoid having the capability of defining tasks in series as an explicit feature just to keep things simple since it's trivially done just by calling `mise run` inside of a task:

```toml
[tasks.build]
run = ['mise run a', 'mise run b', 'mise run c']
```

however, because of several reasons (which I can explain if people are curious but I don't think it matters all that much), this just isn't good enough. I think we may need a way to explicitly define dependencies should run in series. I think users will like this because `mise run` I've often thought users see as a bit of a kluge even though it works fine. How do you think this could look in `mise.toml`? I think I only have terrible ideas:

```toml
[tasks.build]
depends_series = ['a', 'b', 'c']
```

```toml
[tasks.build]
depends = ['a', '+', 'b', '+', 'c']
```
