### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by jdx** [jdx/mise#393]
Plugins need the ability to declare dependencies on other plugins. Exactly how this would be defined is unclear, and it will be fairly complex to try to implement it, but I think we _will_ eventually need it.

This is a problem currently for plugins like rtx-poetry which will call `python3` on PATH. Presumably some people may want that python to be installed via rtx. Right now because these get installed in parallel, it would almost certainly fail the first time since python takes a lot longer to install.

For now, you'll need to run `rtx i python` if you have this problem to explicitly install python first.

However long term, poetry should be able to declare that python is a dependency. This would likely go into rtx.plugin.toml, I can think of a few different ways to represent this:

```toml
# this is naive, it wouldn't allow different versions of poetry to require different versions of python
[dependencies]
python = {version="^3.11,^3.12"} # semver selector (not the same as typical versions)

# this uses semver to set dependencies for a particular version
[dependencies.^3]
python = {version="3.11", optional=true} # optional means it will use the system python unless python is used in `.rtx.toml`
```

Alternatively a script might be a better way to represent this:

```bash
#!/usr/bin/env bash

if [ "$RTX_POETRY_VERSION" = "1."* ]; then
  # poetry is version: 1.*
  echo "python ^3.10,^3.11"
else
  echo "python ^3.12"
fi
```

I'm thinking rather than putting these things on PATH we'd just make env vars like `RTX_PYTHON_PATH` which can be used to find their location. This way we keep PATH pristine since a plugin's dependencies might not be the same as what is in `.rtx.toml`.
