### ISSUE TITLE
Checksum dont seem to generate on latest version for Ubi tool

### ISSUE THREAD

**Issue by jdx** [jdx/mise#4168]
### Discussed in https://github.com/jdx/mise/discussions/4167

<div type='discussions-op-text'>

<sup>Originally posted by **Sytten** January 20, 2025</sup>
Hello!
It looks like the checksums are not being written to the lockfile anymore on MacOS on the latest version for ubi provider.

Given
```toml
[settings]
lockfile = true
experimental = true

[tools]
yq = '4.44.3'
```

It will generate:
```toml
[tools.yq]
version = "4.44.3"
backend = "ubi:mikefarah/yq"
```

where it used to generate:
```toml
[tools.yq]
version = "4.44.3"
backend = "ubi:mikefarah/yq"

[tools.yq.checksums]
yq-macos-aarch64 = "sha256:559a594ef7a6ebc5b81a67b7717fb3accedd266d8fa7d8352da7fec9e463f48b"
```

Happy to help debug, the code seem to have changed a lot in that section so maybe a bug?</div>
