### ISSUE TITLE
Sometimes mise just hangs when executing a task

### ISSUE THREAD

**Issue by jdx** [jdx/mise#4303]
### Discussed in https://github.com/jdx/mise/discussions/4301

<div type='discussions-op-text'>

<sup>Originally posted by **rsyring** February  3, 2025</sup>
uv's default is to use `.venv` for a project's virtualenv.  However, a different path can be provided by using [UV_PROJECT_ENVIRONMENT](https://docs.astral.sh/uv/configuration/environment/#uv_project_environment).

Currently, mise [doesn't check](https://github.com/jdx/mise/blob/67eb899d6ef306c25c83281ff9c750b7e377cff7/src/uv.rs#L70) for an alternate location.

This is probably obvious, but the variable being used should come from the result of mise's environment variable processing pipeline.  

My current workaround is to set:

```toml
[env]
_.python.venv.path = '{{ env.UV_PROJECT_ENVIRONMENT }}'
_.python.venv.create = true
```

But it would be cleaner if I could just:

```toml
[settings]
python.uv_venv_auto = true
```

and trust that whatever uv is doing, mise will play along.

FWIW, my higher-level goal is to support some of our users wanting to use `.venv` and some users wanting to put those files in a temporary/cache location.  So, our actual project files look like:

```toml
[env]
VENV_IDENT = 'foo-app'

_.python.venv.path = '{{ env.VIRTUALENV_DIR }}'
_.python.venv.create = true
```

And then `~/mise.toml` has:

```toml
[env]
# VIRTUALENV_DIR = '.venv'
```

or:

```toml
[env]
VIRTUALENV_DIR = { value='{% if env.VENV_IDENT %}~/.cache/venvs/{{ env.VENV_IDENT }}{% endif %}', tools = true }
UV_PROJECT_ENVIRONMENT = { value='{% if env.VIRTUALENV_DIR %}{{ env.VIRTUALENV_DIR }}{% endif %}', tools = true }
```</div>
