### ISSUE TITLE
Using flag in run array causes error "unexpected word"

### ISSUE THREAD

**Issue by jdx** [jdx/mise#4379]
### Discussed in https://github.com/jdx/mise/discussions/4370

<div type='discussions-op-text'>

<sup>Originally posted by **kehm** February 11, 2025</sup>
Hi. Assuming the error encountered in the below example is not intended?

Description:
The task below works fine in v2025.2.1 but returns "ERROR unexpected word: echo abc" in v2025.2.2 or higher.
This issue only seem to occur when using a flag on the second or later entry in the run array.

To reproduce:
[tasks.test]
run = [
  'echo abc',
  './script.sh {{flag(name="test", default="false")}}',
]

mise run test --test

Environment:
2025.2.2 macos-arm64 (2025-02-08)
zsh 5.9 (arm64-apple-darwin24.0)
experimental  true</div>

**Comment by hverlin** [comment]
This is caused by #4159. 

```sh
TRACE 20 [~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usage-lib-2.0.4/src/parse.rs:35] ParseOutput { cmds: "multi-template", args: [], available_flags: ["--test: --test"], flags: [], flag_awaiting_value: None, errors: [] }
[src/cli/run.rs:615:13] args.clone() = [
    "echo abc",
    "echo {{flag(name=\"test\", default=\"false\")}}",
]
[src/cli/run.rs:616:13] spec.cmd.args.clone() = []
[src/cli/run.rs:617:13] spec.cmd.flags.clone() = [
    SpecFlag {
        name: "test",
        usage: "--test",
        help: None,
        help_long: None,
        help_md: None,
        help_first_line: None,
        short: [],
        long: [
            "test",
        ],
        required: false,
        deprecated: None,
        var: false,
        hide: false,
        global: false,
        count: false,
        arg: None,
        default: Some(
            "false",
        ),
        negate: None,
    },
]
TRACE 20 [~/cargo/registry/src/index.crates.io-6f17d22bba15001f/usage-lib-2.0.4/src/parse.rs:65] parse_partial: ["echo abc", "echo {{flag(name=\"test\", default=\"false\")}}"]
[multi-template] ERROR 
   0: unexpected word: echo {{flag(name="test", default="false")}}

```

**Comment by hverlin** [comment]
@gturi Do you know what a potential fix might be here?

**Comment by gturi** [comment]
I added the following debug log `println!("Usage parsing args {:?}", args);` after  `let args: Vec<String> = get_args();` and it seems that usage `usage::parse` does not like the input when it is a vector with more than one argument.

```toml
[tasks.test-ok]
run = 'echo {{flag(name="test", default="false")}}'

# Output: Usage parsing args ["echo {{flag(name=\"test\", default=\"false\")}}"]
```

```toml
[tasks.test-ko]
run = [
'echo abc',
'echo {{flag(name="test", default="false")}}',
]

# Output: Usage parsing args ["echo abc", "echo {{flag(name=\"test\", default=\"false\")}}"
```

A possible quick fix could be to iterate over the arg vector and create a new "singleton" vector for each element, so that `usage::parse` will work again.

Unfortunately, I am going to be pretty busy in the next weeks, so I do not think I will be able to troubleshoot this issue more in depth than this 😔

Let me know how we want to move forward, I may find some time to implement the fix with some non regression integration test if it is not something too complex.
