### ISSUE TITLE
tasks dependencies should permit env var modifications

### ISSUE THREAD

**Issue by jdx** [jdx/mise#5100]
similar to how args can be provided, e.g.:

```toml
[tasks.test]
run = "test.sh"
[tasks.test-all]
depends = [
  {task = "test", env = {PROP = "a"}},
  {task = "test", env = {PROP = "b"}},
]
```

alternate syntax:
```toml
[tasks.test]
run = "test.sh"
[tasks.test-all]
depends = ["PROP=a test", "PROP=b test"]
```

alternate involves parsing and I feel is less obvious so I think I like it less. Also weird it's `{env} {task}` when you would actually need `{env} mise run {task}` if it was actually bash (which it isn't)
