### ISSUE TITLE
Non-Reproducible Deadlock during mise run on GitHub Actions

### ISSUE THREAD

**Issue by jdx** [jdx/mise#5149]
### Discussed in https://github.com/jdx/mise/discussions/5144

<div type='discussions-op-text'>

<sup>Originally posted by **atty303** May 21, 2025</sup>
We've observed an intermittent deadlock issue when running `mise run` within our GitHub Actions workflows. This appears to happen in about 5% of executions. While the exact cause remains unknown, we're currently investigating whether the way tasks are defined in our files contributes to this problem. We wanted to share our current findings.

<details>
<summary>Backtrace of threads</summary>

```
Thread 10 (Thread 0x725600c006c0 (LWP 11072) "mise"):
#0  0x0000725600f2bc1a in __libc_recv (flags=<optimized out>, len=1, buf=0x725600bff208, fd=4) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  __libc_recv (fd=4, buf=0x725600bff208, len=1, flags=0) at ../sysdeps/unix/sysv/linux/recv.c:23
#2  0x000056490a27ea94 in <signal_hook::iterator::Forever<E> as core::iter::traits::iterator::Iterator>::next ()
#3  0x000056490972db8b in std::sys::backtrace::__rust_begin_short_backtrace ()
#4  0x000056490974d38b in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#5  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#6  0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 9 (Thread 0x7256008006c0 (LWP 11073) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005649096d9ce7 in rayon_core::sleep::Sleep::sleep ()
#2  0x00005649096d87b4 in rayon_core::registry::WorkerThread::wait_until_cold ()
#3  0x000056490971e1ee in rayon_core::scope::ScopeBase::complete ()
#4  0x000056490971cba1 in rayon_core::scope::scope::{{closure}} ()
#5  0x00005649097802a8 in <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute ()
#6  0x00005649096d9464 in rayon_core::registry::WorkerThread::wait_until_cold ()
#7  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#8  0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#9  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#10 0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#11 0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 8 (Thread 0x7256004006c0 (LWP 11074) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000056490a6ec179 in once_cell::imp::initialize_or_wait ()
#2  0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#3  0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#4  0x000056490a2ba53e in mise::task::Task::render ()
#5  0x000056490a2b9947 in mise::task::Task::from_path ()
#6  0x0000564909d01960 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#7  0x00005649097782f5 in <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute ()
#8  0x00005649096d9464 in rayon_core::registry::WorkerThread::wait_until_cold ()
#9  0x000056490a51ba0c in rayon_core::join::join_context::{{closure}} ()
#10 0x0000564909d01412 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#11 0x000056490a0529cd in mise::toolset::Toolset::resolve ()
#12 0x000056490a64eac4 in once_cell::imp::OnceCell<T>::initialize::{{closure}} ()
#13 0x000056490a6ec1fd in once_cell::imp::initialize_or_wait ()
#14 0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#15 0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#16 0x000056490a2ba53e in mise::task::Task::render ()
#17 0x000056490a074829 in alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter ()
#18 0x0000564909d13a9a in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#19 0x000056490a52726c in rayon_core::join::join_context::{{closure}} ()
#20 0x0000564909d13ecf in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#21 0x000056490a039c52 in mise::config::Config::load_tasks_in_dir ()
#22 0x0000564909cf984b in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#23 0x000056490a517eda in rayon_core::join::join_context::{{closure}} ()
#24 0x0000564909cf9b77 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#25 0x000056490a517eda in rayon_core::join::join_context::{{closure}} ()
#26 0x0000564909cf9b77 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#27 0x000056490a517eda in rayon_core::join::join_context::{{closure}} ()
#28 0x0000564909cf9b77 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#29 0x000056490976fe67 in <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute ()
#30 0x00005649096d9464 in rayon_core::registry::WorkerThread::wait_until_cold ()
#31 0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#32 0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#33 0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#34 0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#35 0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 7 (Thread 0x7255fbe006c0 (LWP 11075) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005649096d9ce7 in rayon_core::sleep::Sleep::sleep ()
#2  0x00005649096d87b4 in rayon_core::registry::WorkerThread::wait_until_cold ()
#3  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#4  0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#5  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#6  0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 6 (Thread 0x7255fba006c0 (LWP 11076) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000056490a6ec179 in once_cell::imp::initialize_or_wait ()
#2  0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#3  0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#4  0x000056490a2ba53e in mise::task::Task::render ()
#5  0x000056490a2b9947 in mise::task::Task::from_path ()
#6  0x0000564909d01960 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#7  0x000056490a53147a in rayon_core::join::join_context::{{closure}} ()
#8  0x0000564909d01eeb in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#9  0x000056490a03c16c in mise::config::Config::load_tasks_includes ()
#10 0x0000564909d166de in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#11 0x000056490a03a43e in mise::config::Config::load_tasks_in_dir ()
#12 0x0000564909cf984b in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#13 0x000056490a517eda in rayon_core::join::join_context::{{closure}} ()
#14 0x0000564909cf9b77 in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#15 0x000056490977528c in <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute ()
#16 0x00005649096d9464 in rayon_core::registry::WorkerThread::wait_until_cold ()
#17 0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#18 0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#19 0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#20 0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#21 0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 5 (Thread 0x7255fb6006c0 (LWP 11077) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005649096d9ce7 in rayon_core::sleep::Sleep::sleep ()
#2  0x00005649096d87b4 in rayon_core::registry::WorkerThread::wait_until_cold ()
#3  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#4  0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#5  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#6  0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 4 (Thread 0x7255fb2006c0 (LWP 11078) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000056490a6ec179 in once_cell::imp::initialize_or_wait ()
#2  0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#3  0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#4  0x000056490a2ba53e in mise::task::Task::render ()
#5  0x000056490a074829 in alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter ()
#6  0x0000564909d13a9a in rayon::iter::plumbing::bridge_producer_consumer::helper ()
#7  0x000056490977da19 in <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute ()
#8  0x00005649096d9464 in rayon_core::registry::WorkerThread::wait_until_cold ()
#9  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#10 0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#11 0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#12 0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#13 0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 3 (Thread 0x7255fae006c0 (LWP 11079) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005649096d9ce7 in rayon_core::sleep::Sleep::sleep ()
#2  0x00005649096d87b4 in rayon_core::registry::WorkerThread::wait_until_cold ()
#3  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#4  0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#5  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#6  0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7255faa006c0 (LWP 11080) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005649096d9ce7 in rayon_core::sleep::Sleep::sleep ()
#2  0x00005649096d87b4 in rayon_core::registry::WorkerThread::wait_until_cold ()
#3  0x000056490a7141f5 in std::sys::backtrace::__rust_begin_short_backtrace ()
#4  0x000056490a713984 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#5  0x000056490a9b2fab in std::sys::pal::unix::thread::Thread::new::thread_start ()
#6  0x0000725600e9caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#7  0x0000725600f29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7256011fca00 (LWP 11071) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000056490a714455 in rayon_core::latch::LockLatch::wait_and_reset ()
#2  0x00005649096c869f in rayon_core::registry::Registry::in_worker_cold ()
#3  0x000056490a03891d in mise::config::Config::load_all_tasks ()
#4  0x000056490a66fb01 in once_cell::imp::OnceCell<T>::initialize::{{closure}} ()
#5  0x000056490a6ec1fd in once_cell::imp::initialize_or_wait ()
#6  0x00005649096cebf8 in once_cell::imp::OnceCell<T>::initialize ()
#7  0x000056490a0367b2 in mise::config::Config::tasks_with_aliases ()
#8  0x0000564909eec9b1 in <itertools::flatten_ok::FlattenOk<I,T,E> as core::iter::traits::iterator::Iterator>::next ()
#9  0x000056490a4b74ad in core::iter::adapters::try_process ()
#10 0x000056490a1d5b99 in mise::cli::run::Run::run ()
#11 0x000056490a1fb756 in mise::cli::Commands::run ()
#12 0x000056490a1f9eec in mise::cli::Cli::run ()
#13 0x000056490a069434 in mise::main ()
#14 0x0000564909740d03 in std::sys::backtrace::__rust_begin_short_backtrace ()
#15 0x000056490a067f65 in main ()
```

</details>

```
Thread 8 (Thread 0x7256004006c0 (LWP 11074) "mise"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000056490a6ec179 in once_cell::imp::initialize_or_wait ()
#2  0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#3  0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#4  0x000056490a2ba53e in mise::task::Task::render ()
#5  0x000056490a2b9947 in mise::task::Task::from_path ()
...
#11 0x000056490a0529cd in mise::toolset::Toolset::resolve ()
#12 0x000056490a64eac4 in once_cell::imp::OnceCell<T>::initialize::{{closure}} ()
#13 0x000056490a6ec1fd in once_cell::imp::initialize_or_wait ()
#14 0x00005649096cdbdb in once_cell::imp::OnceCell<T>::initialize ()
#15 0x000056490a2baf49 in mise::task::Task::tera_ctx ()
#16 0x000056490a2ba53e in mise::task::Task::render ()
...
#21 0x000056490a039c52 in mise::config::Config::load_tasks_in_dir ()
...
```

While the full stack trace of the deadlock is collapsed, Thread 8 is particularly interesting. It shows `tera_ctx` being called(#15) within `load_task_in_dir`(#21), which in turn calls `Config::get_toolset`. It appears `get_toolset` is inlined, as it doesn't explicitly appear in the stack trace.

https://github.com/jdx/mise/blob/4e7d2ca0d89906213615d9ce391ed93b29c585af/src/config/mod.rs#L229-L235

The deadlock stems from OnceCell's initialization calling `Toolset::resolve`. This then indirectly calls `tera_ctx`(#3) again via `task_from_path`(#5), leading to an attempt to access the OnceCell before its initialization is complete, causing the deadlock.

The low reproducibility is attributed to Rayon's parallel collection scheduling during task loading. This appears to be specific to the task loading mechanism and occurs exclusively with file tasks. (The file tasks include `#MISE` and `#USAGE` directives and also use Tera templates.)

This has never reproduced on local Linux environments, so it's possible the issue is specific to our self-hosted Runner environment (which uses the official image).

My next step is to experiment with avoiding file tasks and templates to see if that resolves the issue. Despite this potential workaround, I'm reporting this because these deadlocks are indeed happening.

## The relevant Mise settings are

Since this is production code, I'll only extract the relevant sections.

### workflow.yaml

```yaml
env:
  MISE_ENV: ci
  MISE_LOG_FILE: ${{ github.workspace }}/mise.log
  MISE_LOG_FILE_LEVEL: trace
  MISE_LOG_HTTP: 1
jobs:
  ci:
    defaults:
      run:
        shell: bash
        working-directory: ${{ fromJson(inputs.config).root-dir || format('module/{0}', inputs.module) }}
    steps:
# ... checkout etc ...
      - name: Prepare mise
        id: mise
        uses: ./.github/actions/mise
        with:
          cache_key_prefix: ${{ inputs.module }}-mise-${{ vars.CACHE_VERSION }}
          working_directory: ${{ steps.vars.outputs.module-dir }}
          cache: ${{ !inputs.no-cache }}
          cache_save: ${{ env.CI_IS_DEFAULT_BRANCH == 'true' || inputs.force-cache-save }}

      - name: Configure from module CI task
        id: ci-config
        run: |
          export CI_GITHUB_OUTPUT="$GITHUB_OUTPUT"
          # strace -f -o /tmp/mise_trace_config.log -yy -s 2048 -T mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          mise run ci:config
          # The actions hang here. We're running them repeatedly to improve reproducibility.
```

### /.github/actions/mise/action.yml

```yaml
    - uses: jdx/mise-action@v2
      id: mise
      env:
        MISE_ENV: ci
        # ubiが利用するPublic GitHub APIのレート制限を回避するため
        GITHUB_TOKEN: ${{ github.token }}
      with:
        version: ${{ inputs.version }}
        mise_dir: ${{ inputs.mise_dir }}
        tool_versions: ${{ inputs.tool_versions }}
        mise_toml: ${{ inputs.mise_toml }}
        install: ${{ inputs.install }}
        install_args: ${{ inputs.install_args }}
        install_dir: ${{ inputs.install_dir }}
        cache_key_prefix: ${{ inputs.cache_key_prefix }}
        experimental: ${{ inputs.experimental }}
        log_level: ${{ inputs.log_level }}
        working_directory: ${{ inputs.working_directory }}
        cache: false
        cache_save: false

    - name: Report cache miss
      if: inputs.cache == 'true' && (steps.cache.outputs.cache-hit != 'true' && steps.cache.outputs.cache-size == '') && (steps.cache-restore.outputs.cache-hit != 'true' && steps.cache-restore.outputs.cache-size == '')
      shell: bash
      run: |
        echo "::notice::Cache miss \`${{ steps.cache_key.outputs.result }}\`"

    - name: Configure global mise config
      shell: bash
      run: |
        mkdir -p ~/.config/mise
        cat <<EOF > ~/.config/mise/config.toml
        [settings]
        ignored_config_paths = [ "${{ github.workspace }}/.config/mise/config.toml" ]
        # 可視性のためにprefixにしたいがActionsのecho "::group::"の前に文字列が出力されてしまいコマンドが認識されなくなる
        task_output = "interleave"
        task_timings = true
        unix_default_file_shell_args = "env time -f '📏 [🕒 Elapsed: %E 🧠 Memory: %M KB 📥 In: %I 📤 Out: %O 🚪 Exit: %x]' bash -eu -o pipefail -o errexit"
        unix_default_inline_shell_args = "env time -f '📏 [🕒 Elapsed: %E 🧠 Memory: %M KB 📥 In: %I 📤 Out: %O 🚪 Exit: %x]' bash -eu -o pipefail -o errexit -c"
        EOF

        echo "::group::~/.config/mise/config.toml"
        cat ~/.config/mise/config.toml
        echo "::endgroup::"
```

Output:

```
> Running mise --version
  /home/runner/.local/share/mise/bin/mise --version
  2025.5.8 linux-x64 (2025-05-18)
```

### /module/name/.mise.ci.toml

```toml
[tools]

[vars]
# ...snip...

[tasks."ci:config"]
description = "Configure CI workflow (call from CI workflow)"
run = [
  'mise run ci:output cache-deps -- true',
  'mise run ci:output cache-deps-path -- "{{vars.cache_path}}"',
  'mise run ci:output cache-deps-build-path -- "{{vars.cache_build_path}}"',
  'mise run ci:output cache-incremental -- true',
  'mise run ci:output cache-incremental-path -- "{{vars.cache_incremental_path}}"',
  'mise run ci:output test-report-path -- "{{vars.test_report_path}}"',
  'mise run ci:output test-report-reporter -- "{{vars.test_report_reporter}}"',
]

# ...snip... other after step tasks
```

### /module/name/.mise.toml

```toml
[tools]
java = "corretto-21"
yq = "latest" # android-sdk mise plugin needs yq
android-sdk = "19"

[vars]
android_sdk_licenses = ".android-sdk-licenses"

[tasks.export-licenses]
description = """Export android-sdk licenses
    gradleが参照するAndroid SDKを変更したときはCIでビルドできるようにこのタスクを実行する必要があります。"""
run = """
DIR=$(mise where android-sdk)/licenses
OUT={{vars.android_sdk_licenses}}

# 出力ファイルを空にする
: > "$OUT"

for f in "$DIR"/*; do
  name=$(basename "$f")
  hash=$(tr -d '\r\n' < "$f")
  printf '%s:%s\n' "$name" "$hash"
done >> "$OUT"
"""

[tasks.import-licenses]
description = "Import android-sdk licenses"
run = """
IN={{vars.android_sdk_licenses}}
DIR=$(mise where android-sdk)/licenses

mkdir -p "$DIR"
while IFS=: read -r name hash; do
  target="$DIR/$name"
  printf '%s\n' "$hash" > "$target"
done < "$IN"
"""
```

### /.config/mise/tasks/ci/output.sh

```bash
#!/usr/bin/env -S bash -euo pipefail
#MISE dir="{{cwd}}"
#MISE silent=true
#MISE hide=true

key="${1:?Required argument}"
shift

[ "$1" = "--" ] && shift

{
  echo "${key}<<__EOF__"
  echo "$@"
  echo "__EOF__"
} >> "${CI_GITHUB_OUTPUT:?Required variable not set}"
```

### /.config/mise/tasks/ci/step.sh

```bash
#!/usr/bin/env -S bash -o pipefail
#MISE dir="{{cwd}}"
#MISE silent=true
#MISE hide=true
#USAGE arg "<group-name>"
#USAGE arg "<command>" var=#true var_min=1 double_dash="optional"

echo "::group::$1"
shift

if [ "$1" = "--" ]; then shift; fi

"$@"
status=$?

echo "::endgroup::"
exit $status
```
</div>
